const ApiConstants = {
  API_LOGIN_LOAD: "API_LOGIN_LOAD",
  API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
  API_LOGIN_FAIL: "API_LOGIN_FAIL",
  API_LOGIN_ERROR: "API_LOGIN_ERROR",

  API_QR_CODE_LOAD: 'API_QR_CODE_LOAD',
  API_QR_CODE_SUCCESS: 'API_QR_CODE_SUCCESS',
  API_QR_CODE_FAIL: 'API_QR_CODE_FAIL',
  API_QR_CODE_ERROR: 'API_QR_CODE_ERROR',

  API_ROLE_LOAD: "API_ROLE_LOAD",
  API_ROLE_SUCCESS: "API_ROLE_SUCCESS",
  API_ROLE_FAIL: "API_ROLE_FAIL",
  API_ROLE_ERROR: "API_ROLE_ERROR",

  API_URE_LOAD: "API_URE_LOAD",
  API_URE_SUCCESS: "API_URE_SUCCESS",
  API_URE_FAIL: "API_URE_FAIL",
  API_URE_ERROR: "API_URE_ERROR",

  MENU_NAVIGATION_CHANGE: "MENU_NAVIGATION_CHANGE",

  ///////registration reducer
  API_REGISTRATION_FAIL: "API_REGISTRATION_FAIL",
  API_REGISTRATION_ERROR: "API_REGISTRATION_ERROR",

  /////registration competition list
  API_REG_COMPETITION_LIST_LOAD: "API_REG_COMPETITION_LIST_LOAD",
  API_REG_COMPETITION_LIST_SUCCESS: "API_REG_COMPETITION_LIST_SUCCESS",

  /////registration competition list
  API_REG_MEMBERSHIP_LIST_LOAD: "API_REG_MEMBERSHIP_LIST_LOAD",
  API_REG_MEMBERSHIP_LIST_SUCCESS: "API_REG_MEMBERSHIP_LIST_SUCCESS",

  /////registration competition list delete product
  API_REG_COMPETITION_LIST_DELETE_LOAD: "API_REG_COMPETITION_LIST_DELETE_LOAD",
  API_REG_COMPETITION_LIST_DELETE_SUCCESS:
    "API_REG_COMPETITION_LIST_DELETE_SUCCESS",

  /////registration membership list delete product
  API_REG_MEMBERSHIP_LIST_DELETE_LOAD: "API_REG_MEMBERSHIP_LIST_DELETE_LOAD",
  API_REG_MEMBERSHIP_LIST_DELETE_SUCCESS:
    "API_REG_MEMBERSHIP_LIST_DELETE_SUCCESS",

  ///////app reducer
  API_APP_FAIL: "API_APP_FAIL",
  API_APP_ERROR: "API_APP_ERROR",

  //registration form Save
  API_REG_FORM_LOAD: "API_REG_FORM_LOAD",
  API_REG_FORM_SUCCESS: "API_REG_FORM_SUCCESS",

  //registration Form Venue get

  API_REG_FORM_VENUE_LOAD: "API_REG_FORM_VENUE_LOAD",
  API_REG_FORM_VENUE_SUCCESS: "API_REG_FORM_VENUE_SUCCESS",

  //registration Form Advanced Settings
  API_REG_FORM_SETTINGS_LOAD: "API_REG_FORM_SETTINGS_LOAD",
  API_REG_FORM_SETTINGS_SUCCESS: "API_REG_FORM_SETTINGS_SUCCESS",

  //registration Form Advanced Settings
  API_REG_FORM_METHOD_LOAD: "API_REG_FORM_METHOD_LOAD",
  API_REG_FORM_METHOD_SUCCESS: "API_REG_FORM_METHOD_SUCCESS",

  // registration form MEMBERSHIP_PRODUCT list
  API_REG_FORM_MEMBERSHIP_PRODUCT_LOAD: "API_REG_FORM_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_FORM_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_FORM_MEMBERSHIP_PRODUCT_SUCCESS",

  //Get registration Form
  API_GET_REG_FORM_LOAD: "API_GET_REG_FORM_LOAD",
  API_GET_REG_FORM_SUCCESS: "API_GET_REG_FORM_SUCCESS",

  //update registration form
  API_UPDATE_REG_FORM_LOAD: "API_UPDATE_REG_FORM_LOAD",
  API_UPDATE_REG_FORM_SUCCESS: "API_UPDATE_REG_FORM_SUCCESS",

  //clear particular reducer data
  REG_CLEARING_PARTICULAR_REDUCER_DATA: "REG_CLEARING_PARTICULAR_REDUCER_DATA",

  /////registration get membership product details
  API_REG_GET_MEMBERSHIP_PRODUCT__LOAD: "API_REG_GET_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_GET_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_GET_MEMBERSHIP_PRODUCT_SUCCESS",

  /////registration save membership product details
  API_REG_SAVE_MEMBERSHIP_PRODUCT__LOAD: "API_REG_SAVE_MEMBERSHIP_PRODUCT_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_SUCCESS",

  /////get the common year list reference
  API_YEAR_LIST_LOAD: "API_YEAR_LIST_LOAD",
  API_YEAR_LIST_SUCCESS: "API_YEAR_LIST_SUCCESS",
  API_ONLY_YEAR_LIST_LOAD: "API_ONLY_YEAR_LIST_LOAD",
  API_ONLY_YEAR_LIST_SUCCESS: "API_ONLY_YEAR_LIST_SUCCESS",

  /////get the common membership product validity type list reference
  API_PRODUCT_VALIDITY_LIST_LOAD: "API_PRODUCT_VALIDITY_LIST_LOAD",
  API_PRODUCT_VALIDITY_LIST_SUCCESS: "API_PRODUCT_VALIDITY_LIST_SUCCESS",

  /////get the common Competition type list reference
  API_COMPETITION_TYPE_LIST_LOAD: "API_COMPETITION_TYPE_LIST_LOAD",
  API_COMPETITION_TYPE_LIST_SUCCESS: "API_COMPETITION_TYPE_LIST_SUCCESS",

  ///////////get the default membership  product types in registartion membership fees
  API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES__LOAD:
    "API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES__LOAD",
  API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES_SUCCESS:
    "API_REG_GET_DEFAULT_MEMBERSHIP_PRODUCT_TYPES_SUCCESS",

  /////registration save membership product Fees
  API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES__LOAD:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_FEES_SUCCESS",

  /////registration save membership product Discount
  API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT__LOAD:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_LOAD",
  API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_SUCCESS:
    "API_REG_SAVE_MEMBERSHIP_PRODUCT_DISCOUNT_SUCCESS",

  /////get the common Membership Product Fees Type
  API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_LOAD:
    "API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_LOAD",
  API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_SUCCESS:
    "API_COMMON_MEMBERSHIP_PRODUCT_FEES_TYPE_SUCCESS",

  //////chnage the membership fees table data
  CHANGE_MEMBERSHIP_FEES_TABLE_INPUT: "CHANGE_MEMBERSHIP_FEES_TABLE_INPUT",

  /////get the common discount Type
  API_COMMON_DISCOUNT_TYPE_LOAD: "API_COMMON_DISCOUNT_TYPE_LOAD",
  API_COMMON_DISCOUNT_TYPE_SUCCESS: "API_COMMON_DISCOUNT_TYPE_SUCCESS",

  /////get the membership product discount Types
  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD:
    "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE__LOAD",
  API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS:
    "API_MEMBERSHIP_PRODUCT_DISCOUNT_TYPE_SUCCESS",

  //////add new membership type in the membership fees section
  ADD_NEW_MEMBERSHIP_TYPE: "ADD_NEW_MEMBERSHIP_TYPE",

  //for clear competition data
  API_CLEAR_COMPETITION: "API_CLEAR_COMPETITION",

  //for change membership category
  REG_FORM_UPDATE_MEMBERSHIP_CATEGORY: "REG_FORM_UPDATE_MEMBERSHIP_CATEGORY",

  ////add another discount in the membership fees
  ADD_ANOTHER_DISCOUNT_MEMBERSHIP_FEES: "ADD_ANOTHER_DISCOUNT_MEMBERSHIP_FEES",

  ///updated discount in membership fees section
  UPDATE_DISCOUNT_DATA_MEMBERSHIP_FEES: "UPDATE_DISCOUNT_DATA_MEMBERSHIP_FEES",

  ////membership fees radip apply fees on change
  ON_CHANGE_RADIO_APPLY_FEES_MEMBERSHIP_FEES: "ON_CHANGE_RADIO_APPLY_FEES_MEMBERSHIP_FEES",

  ////age mandate and membershipTypes onchange selection checkbox
  ON_CHANGE_SELECTION_MEM_TYPE_AGE_MANDATE_CHECKBOX: "ON_CHANGE_SELECTION_MEM_TYPE_AGE_MANDATE_CHECKBOX",

  ///////onchange date data in age restriction in the membership types
  ON_CHANGE_DATE_AGE_MANDATE_MEMBERSHIP_TYPES: "ON_CHANGE_DATE_AGE_MANDATE_MEMBERSHIP_TYPES",

  ////remove custom membership type from the membership fees
  REMOVE_CUSTOM_MEMBERSHIP_FEES_TYPE: "REMOVE_CUSTOM_MEMBERSHIP_FEES_TYPE",


  REG_FORM_UPDATE_MEMBERSHIP_PRODUCT_TYPES:
    "REG_FORM_UPDATE_MEMBERSHIP_PRODUCT_TYPES",

  REG_FORM_UPDATE_MEMBERSHIP_REGISTRATIONLOCK:
    "REG_FORM_UPDATE_MEMBERSHIP_REGISTRATIONLOCK",

  REG_FORM_UPDATE_DISCLAIMER_TEXT: "REG_FORM_UPDATE_DISCLAIMER_TEXT",

  REG_FORM_CHECKED_VISIBLE: "REG_FORM_CHECKED_VISIBLE",


  ////Goal List
  API_LIVE_SCORE_GOAL_LIST_LOAD: "API_LIVE_SCORE_GOAL_LIST_LOAD",
  API_LIVE_SCORE_GOAL_LIST_SUCCESS: "API_LIVE_SCORE_GOAL_LIST_SUCCESS",
  API_LIVE_SCORE_GOAL_LIST_FAIL: "API_LIVE_SCORE_GOAL_LIST_FAIL",
  API_LIVE_SCORE_GOAL_LIST_ERROR: "API_LIVE_SCORE_GOAL_LIST_ERROR",


  REG_FORM_REPLY_CHECKED_VISIBLE: "REG_FORM_REPLY_CHECKED_VISIBLE",

  /**********competition fee Api constatnts */

  ///////competition feees
  API_COMPETITION_FEES_FAIL: "API_COMPETITION_FEES_FAIL",
  API_COMPETITION_FEES_ERROR: "API_COMPETITION_FEES_ERROR",

  // init api for reference in competition fee
  API_REG_COMPETITION_FEE_INIT_LOAD: "API_REG_COMPETITION_FEE_INIT_LOAD",
  API_REG_COMPETITION_FEE_INIT_SUCCESS: "API_REG_COMPETITION_FEE_INIT_SUCCESS",

  /////get the competition fees all the data in one API
  API_GET_COMPETITION_FEES_DETAILS_LOAD: "API_GET_COMPETITION_FEES_DETAILS_LOAD",
  API_GET_COMPETITION_FEES_DETAILS_SUCCESS: "API_GET_COMPETITION_FEES_DETAILS_SUCCESS",

  ///save the competition fees details
  API_SAVE_COMPETITION_FEES_DETAILS_LOAD: "API_SAVE_COMPETITION_FEES_DETAILS_LOAD",
  API_SAVE_COMPETITION_FEES_DETAILS_SUCCESS: "API_SAVE_COMPETITION_FEES_DETAILS_SUCCESS",

  ////save the competition membership tab details
  API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_LOAD: "API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_LOAD",
  API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_SUCCESS: "API_SAVE_COMPETITION_FEES_MEMBERHSIP_TAB_SUCCESS",

  ////get default competition membershipproduct tab details
  API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_LOAD: "API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_LOAD",
  API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_SUCCESS: "API_GET_DEFAULT_COMPETITION_FEES_MEMBERHSIP_PRODUCT_SUCCESS",

  ////membership product selected action tochange membership typearray data
  COMPETITION_FEES_MEMBERSHIP_PRODUCT_SELECTED_ONCHANGE: "COMPETITION_FEES_MEMBERSHIP_PRODUCT_SELECTED_ONCHANGE",

  ////membership types in competition fees onchhange function
  COMPETITION_FEES_MEMBERSHIP_TYPES_SELECTED_ONCHANGE: "COMPETITION_FEES_MEMBERSHIP_TYPES_SELECTED_ONCHANGE",

  /////save the division table data  in the competition fees section
  API_SAVE_COMPETITION_FEES_DIVISION_TAB_LOAD: "API_SAVE_COMPETITION_FEES_DIVISION_TAB_LOAD",
  API_SAVE_COMPETITION_FEES_DIVISION_TAB_SUCCESS: "API_SAVE_COMPETITION_FEES_DIVISION_TAB_SUCCESS",

  /////onchange the division table data on change
  COMPETITION_FEES_DIVISION_TABLE_DATA_ONCHANGE: "COMPETITION_FEES_DIVISION_TABLE_DATA_ONCHANGE",

  //////add or remove another division inthe divsision tab
  COMPETITION_FEES_DIVISION_ADD_REMOVE: "COMPETITION_FEES_DIVISION_ADD_REMOVE",


  //update competition fee payment  charity round up
  UPDATE_PAYMENTS_COMPETITION_FEES: "UPDATE_PAYMENTS_COMPETITION_FEES",

  UPDATE_PAYMENTS_OPTIONS_COMPETITION_FEES: 'UPDATE_PAYMENTS_OPTIONS_COMPETITION_FEES',

  //update  default casual fee 
  GET_CASUAL_FEE_DETAIL_API_LOAD: "GET_CASUAL_FEE_DETAIL_API_LOAD",
  GET_CASUAL_FEE_DETAIL_API_SUCCESS: "GET_CASUAL_FEE_DETAIL_API_SUCCESS",

  //update  default seasonal fee 
  GET_SEASONAL_FEE_DETAIL_API_LOAD: "GET_SEASONAL_FEE_DETAIL_API_LOAD",
  GET_SEASONAL_FEE_DETAIL_API_SUCCESS: "GET_SEASONAL_FEE_DETAIL_API_SUCCESS",

  //post api of competition fee payment 
  API_POST_COMPETITION_FEE_PAYMENT_LOAD: "API_POST_COMPETITION_FEE_PAYMENT_LOAD",
  API_POST_COMPETITION_FEE_PAYMENT_SUCCESS: "API_POST_COMPETITION_FEE_PAYMENT_SUCCESS",


  ADD_ANOTHER_DISCOUNT_COMPETITION_FEE: "ADD_ANOTHER_DISCOUNT_COMPETITION_FEE",
  //// Add-Edit competition details
  API_ADD_EDIT_COMPETITION_FEES_DETAILS: "API_ADD_EDIT_COMPETITION_FEES_DETAILS",

  //////Add-Edit competition  section
  API_ADD_EDIT_COMPETITION_FEES_SECTION: "API_ADD_EDIT_COMPETITION_FEES_SECTION",
  CHECK_UNCHECK_COMPETITION_FEES_SECTION: "CHECK_UNCHECK_COMPETITION_FEES_SECTION",

  ////Save competition fee section
  API_SAVE_COMPETITION_FEES_SECTION_LOAD: "API_SAVE_COMPETITION_FEES_SECTION_LOAD",
  API_SAVE_COMPETITION_FEES_SECTION_SUCCESS: "API_SAVE_COMPETITION_FEES_SECTION_SUCCESS",

  // update discount data  in competiton fee
  UPDATE_DISCOUNT_DATA_COMPETITION_FEES: "UPDATE_DISCOUNT_DATA_COMPETITION_FEES",
  // update membership product in competition fee
  UPDATE_DISCOUNT_MEMBERSHIP_PRODUCT: "UPDATE_DISCOUNT_MEMBERSHIP_PRODUCT",
  //  default charity api call
  API_REG_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS: "API_REG_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS",
  //on change competion fee discount load
  API_POST_COMPETITION_FEE_DISCOUNT_LOAD: "API_POST_COMPETITION_FEE_DISCOUNT_LOAD",
  API_POST_COMPETITION_FEE_DISCOUNT_SUCCESS: "API_POST_COMPETITION_FEE_DISCOUNT_SUCCESS",


  //default competition  Discount type
  API_COMPETITION_DISCOUNT_TYPE_LOAD: "API_COMPETITION_DISCOUNT_TYPE_LOAD",
  API_COMPETITION_DISCOUNT_TYPE_SUCCESS: "API_COMPETITION_DISCOUNT_TYPE_SUCCESS",

  //clear competition fees  reducer data
  REG_COMPETITION_FEES_CLEARING_REDUCER_DATA: "REG_COMPETITION_FEES_CLEARING_REDUCER_DATA",

  /////get default charity and government voucherss
  API_COMPETITION_FEE_DEFAULT_CHARITY_LOAD: "API_COMPETITION_FEE_DEFAULT_CHARITY_LOAD",
  API_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS: "API_COMPETITION_FEE_DEFAULT_CHARITY_SUCCESS",



  /////************************Live Score*******************Start

  ////live score player
  API_LIVE_SCORE_PLAYER_LIST_LOAD: "API_LIVE_SCORE_PLAYER_LIST_LOAD",
  API_LIVE_SCORE_PLAYER_LIST_SUCCESS: "API_LIVE_SCORE_PLAYER_LIST_SUCCESS",
  API_LIVE_SCORE_PLAYER_LIST_FAIL: "API_LIVE_SCORE_PLAYER_LIST_FAIL",
  API_LIVE_SCORE_PLAYER_LIST_ERROR: "API_LIVE_SCORE_PLAYER_LIST_ERROR",
  API_LIVE_SCORE_PLAYER_EXPORT_LOAD: "API_LIVE_SCORE_PLAYER_EXPORT_LOAD",
  API_LIVE_SCORE_PLAYER_EXPORT_SUCCESS: "API_LIVE_SCORE_PLAYER_EXPORT_SUCCESS",
  API_LIVE_SCORE_PLAYER_EXPORT_FAIL: "API_LIVE_SCORE_PLAYER_EXPORT_FAIL",
  API_LIVE_SCORE_PLAYER_EXPORT_ERROR: "API_LIVE_SCORE_PLAYER_EXPORT_ERROR",
  ////live score match division
  API_LIVE_SCORE_DIVISION_LOAD: "API_LIVE_SCORE_DIVISION_LOAD",
  API_LIVE_SCORE_DIVISION_SUCCESS: "API_LIVE_SCORE_DIVISION_SUCCESS",
  API_LIVE_SCORE_LADDERS_DIVISION_LOAD: "API_LIVE_SCORE_LADDERS_DIVISION_LOAD",
  API_LIVE_SCORE_LADDERS_DIVISION_SUCCESS: "API_LIVE_SCORE_LADDERS_DIVISION_SUCCESS",
  API_LIVE_SCORE_LADDERS_DIVISION_FAIL: "API_LIVE_SCORE_LADDERS_DIVISION_FAIL",
  API_LIVE_SCORE_LADDERS_DIVISION_ERROR: "API_LIVE_SCORE_LADDERS_DIVISION_ERROR",
  API_LIVE_SCORE_LADDERS_LIST_LOAD: "API_LIVE_SCORE_LADDERS_LIST_LOAD",
  API_LIVE_SCORE_LADDERS_LIST_SUCCESS: "API_LIVE_SCORE_LADDERS_LIST_SUCCESS",
  API_LIVE_SCORE_LADDERS_LIST_FAIL: "API_LIVE_SCORE_LADDERS_LIST_FAIL",
  API_LIVE_SCORE_LADDERS_LIST_ERROR: "API_LIVE_SCORE_LADDERS_LIST_ERROR",
  API_LIVE_SCORE_MATCH_LIST_LOAD: "API_LIVE_SCORE_MATCH_LIST_LOAD",
  API_LIVE_SCORE_MATCH_LIST_SUCCESS: "API_LIVE_SCORE_MATCH_LIST_SUCCESS",
  API_LIVE_SCORE_MATCH_LIST_FAIL: "API_LIVE_SCORE_MATCH_LIST_FAIL",
  API_LIVE_SCORE_MATCH_LIST_ERROR: "API_LIVE_SCORE_MATCH_LIST_ERROR",
  API_LIVE_SCORE_TEAM_LOAD: "API_LIVE_SCORE_TEAM_LOAD",
  API_LIVE_SCORE_TEAM_SUCCESS: "API_LIVE_SCORE_TEAM_SUCCESS",
  API_LIVE_SCORE_TEAM_FAIL: "API_LIVE_SCORE_TEAM_FAIL",
  API_LIVE_SCORE_TEAM_ERROR: "API_LIVE_SCORE_TEAM_ERROR",
  API_LIVE_SCORE_INCIDENT_LIST_LOAD: "API_LIVE_SCORE_INCIDENT_LIST_LOAD",
  API_LIVE_SCORE_INCIDENT_LIST_SUCCESS: "API_LIVE_SCORE_INCIDENT_LIST_SUCCESS",
  API_LIVE_SCORE_INCIDENT_LIST_FAIL: "API_LIVE_SCORE_INCIDENT_LIST_FAIL",
  API_LIVE_SCORE_INCIDENT_LIST_ERROR: "API_LIVE_SCORE_INCIDENT_LIST_ERROR",
  API_LIVE_SCORE_ADD_EDIT_MATCH_LOAD: "API_LIVE_SCORE_ADD_EDIT_MATCH_LOAD",
  API_LIVE_SCORE_ADD_EDIT_MATCH_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_MATCH_SUCCESS",
  API_LIVE_SCORE_ADD_EDIT_MATCH_FAIL: "API_LIVE_SCORE_ADD_EDIT_MATCH_FAIL",
  API_LIVE_SCORE_ADD_EDIT_MATCH_ERROR: "API_LIVE_SCORE_ADD_EDIT_MATCH_ERROR",
  API_LIVE_SCORE_ADD_MATCH: "API_LIVE_SCORE_ADD_MATCH",
  API_LIVE_SCORE_UPDATE_MATCH: 'API_LIVE_SCORE_UPDATE_MATCH',
  ////create match
  API_LIVE_SCORE_CREATE_MATCH_LOAD: "API_LIVE_SCORE_CREATE_MATCH_LOAD",
  API_LIVE_SCORE_CREATE_MATCH_SUCCESS: "API_LIVE_SCORE_CREATE_MATCH_SUCCESS",
  API_LIVE_SCORE_CREATE_MATCH_FAIL: "API_LIVE_SCORE_CREATE_MATCH_FAIL",
  API_LIVE_SCORE_CREATE_MATCH_ERROR: "API_LIVE_SCORE_CREATE_MATCH_ERROR",
  ////news list
  API_LIVE_SCORE_NEWS_LIST_LOAD: "API_LIVE_SCORE_NEWS_LIST_LOAD",
  API_LIVE_SCORE_NEWS_LIST_SUCCESS: "API_LIVE_SCORE_NEWS_LIST_SUCCESS",
  API_LIVE_SCORE_NEWS_LIST_FAIL: "API_LIVE_SCORE_NEWS_LIST_FAIL",
  API_LIVE_SCORE_NEWS_LIST_ERROR: "API_LIVE_SCORE_NEWS_LIST_ERROR",
  ////Banners
  API_LIVE_SCORE_BANNERS_LOAD: "API_LIVE_SCORE_BANNERS_LOAD",
  API_LIVE_SCORE_BANNERS_SUCCESS: "API_LIVE_SCORE_BANNERS_SUCCESS",
  API_LIVE_SCORE_BANNERS_FAIL: "API_LIVE_SCORE_BANNERS_FAIL",
  API_LIVE_SCORE_BANNERS_ERROR: "API_LIVE_SCORE_BANNERS_ERROR",
  ////Create Round
  API_LIVE_SCORE_CREATE_ROUND_LOAD: "API_LIVE_SCORE_CREATE_ROUND_LOAD",
  API_LIVE_SCORE_CREATE_ROUND_SUCCESS: "API_LIVE_SCORE_CREATE_ROUND_SUCCESS",
  API_LIVE_SCORE_CREATE_ROUND_FAIL: "API_LIVE_SCORE_CREATE_ROUND_FAIL",
  API_LIVE_SCORE_CREATE_ROUND_ERROR: "API_LIVE_SCORE_CREATE_ROUND_ERROR",

  API_LIVE_SCORE_ADD_NEWS_DETAILS: "API_LIVE_SCORE_ADD_NEWS_DETAILS",
  API_LIVE_SCORE_UPDATE_NEWS: 'API_LIVE_SCORE_UPDATE_NEWS',
  ////Add News
  API_LIVE_SCORE_ADD_NEWS_LOAD: "API_LIVE_SCORE_ADD_NEWS_LOAD",
  API_LIVE_SCORE_ADD_NEWS_SUCCESS: "API_LIVE_SCORE_ADD_NEWS_SUCCESS",
  API_LIVE_SCORE_ADD_NEWS_FAIL: "API_LIVE_SCORE_ADD_NEWS_FAIL",
  API_LIVE_SCORE_ADD_NEWS_ERROR: "API_LIVE_SCORE_ADD_NEWS_ERROR",
  API_LIVE_SCORE_REFRESH_NEWS: 'API_LIVE_SCORE_REFRESH_NEWS',
  ////Manager list
  API_LIVE_SCORE_MANAGER_LIST_LOAD: "API_LIVE_SCORE_MANAGER_LIST_LOAD",
  API_LIVE_SCORE_MANAGER_LIST_SUCCESS: "API_LIVE_SCORE_MANAGER_LIST_SUCCESS",
  API_LIVE_SCORE_MANAGER_LIST_FAIL: "API_LIVE_SCORE_MANAGER_LIST_FAIL",
  API_LIVE_SCORE_MANAGER_LIST_ERROR: "API_LIVE_SCORE_MANAGER_LIST_ERROR",
  //// Scorer List
  API_LIVE_SCORE_SCORER_LIST_LOAD: "API_LIVE_SCORE_SCORER_LIST_LOAD",
  API_LIVE_SCORE_SCORER_LIST_SUCCESS: "API_LIVE_SCORE_SCORER_LIST_SUCCESS",
  API_LIVE_SCORE_SCORER_LIST_FAIL: "API_LIVE_SCORE_SCORER_LIST_FAIL",
  API_LIVE_SCORE_SCORER_LIST_ERROR: "API_LIVE_SCORE_SCORER_LIST_ERROR",
  ////Bulk Match Push Back
  API_LIVE_SCORE_BULK_PUSH_BACK_LOAD: "API_LIVE_SCORE_BULK_PUSH_BACK_LOAD",
  API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS: "API_LIVE_SCORE_BULK_PUSH_BACK_SUCCESS",
  API_LIVE_SCORE_BULK_PUSH_BACK_FAIL: "API_LIVE_SCORE_BULK_PUSH_BACK_FAIL",
  API_LIVE_SCORE_BULK_PUSH_BACK_ERROR: "API_LIVE_SCORE_BULK_PUSH_BACK_ERROR",
  ////Bulk Match Bring Forward
  API_LIVE_SCORE_BULK_BRING_FORWARD_LOAD: "API_LIVE_SCORE_BULK_BRING_FORWARD_LOAD",
  API_LIVE_SCORE_BULK_BRING_FORWARD_SUCCESS: "API_LIVE_SCORE_BULK_BRING_FORWARD_SUCCESS",
  API_LIVE_SCORE_BULK_BRING_FORWARD_FAIL: "API_LIVE_SCORE_BULK_BRING_FORWARD_FAIL",
  API_LIVE_SCORE_BULK_BRING_FORWARD_ERROR: "API_LIVE_SCORE_BULK_BRING_FORWARD_ERROR",
  ////Bulk End Matches
  API_LIVE_SCORE_BULK_END_MATCHES_LOAD: "API_LIVE_SCORE_BULK_END_MATCHES_LOAD",
  API_LIVE_SCORE_BULK_END_MATCHES_SUCCESS: "API_LIVE_SCORE_BULK_END_MATCHES_SUCCESS",
  API_LIVE_SCORE_BULK_END_MATCHES_FAIL: "API_LIVE_SCORE_BULK_END_MATCHES_FAIL",
  API_LIVE_SCORE_BULK_END_MATCHES_ERROR: "API_LIVE_SCORE_BULK_END_MATCHES_ERROR",
  API_LIVE_SCORE_BULK_MATCH: 'API_LIVE_SCORE_BULK_MATCH',
  API_LIVE_SCORE_UPDATE_BULK: 'API_LIVE_SCORE_UPDATE_BULK',
  ////Remove Banner
  API_LIVE_SCORE_REMOVE_BANNER_LOAD: "API_LIVESCORE_ADD_REMOVE_BANNER_LOAD",
  API_LIVE_SCORE_REMOVE_BANNER_SUCCESS: "API_LIVESCORE_ADD_REMOVE_BANNER_SUCCESS",
  API_LIVE_SCORE_REMOVE_BANNER_FAIL: "API_LIVESCORE_ADD_REMOVE_BANNER_FAIL",
  API_LIVE_SCORE_REMOVE_BANNER_ERROR: "API_LIVESCORE_ADD_REMOVE_BANNER_ERROR",
  ////Add Banner
  API_LIVE_SCORE_ADD_BANNER_LOAD: "API_LIVESCORE_ADD_BANNER_LOAD",
  API_LIVE_SCORE_ADD_BANNER_SUCCESS: "API_LIVESCORE_ADD_BANNER_SUCCESS",
  API_LIVE_SCORE_ADD_BANNER_FAIL: "API_LIVESCORE_ADD_BANNER_FAIL",
  API_LIVE_SCORE_ADD_BANNER_ERROR: "API_LIVESCORE_ADD_BANNER_ERROR",
  //// Bulk Doble Header
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_LOAD: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_LOAD",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_SUCCESS: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_SUCCESS",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_FAIL: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_FAIL",
  API_LIVE_SCORE_BULK_DOUBLE_HEADER_ERROR: "API_LIVE_SCORE_BULK_DOUBLE_HEADER_ERROR",
  ////Api Abandon Matches
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_LOAD: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_LOAD",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_SUCCESS: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_SUCCESS",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_FAIL: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_FAIL",
  API_LIVE_SCORE_BULK_ABANDON_MATCHES_ERROR: "API_LIVE_SCORE_BULK_ABANDON_MATCHES_ERROR",

  ////************************Live Score*******************End

  ////Competition Dashboard
  API_COMPETITION_DASHBOARD_LOAD: 'API_COMPETITION_DASHBOARD_LOAD',
  API_COMPETITION_DASHBOARD_SUCCESS: "API_COMPETITION_DASHBOARD_SUCCESS",
  API_COMPETITION_DASHBOARD_FAIL: "API_COMPETITION_DASHBOARD_FAIL",
  API_COMPETITION_DASHBOARD_ERROR: "API_COMPETITION_DASHBOARD_ERROR",
  API_FIXTURE_TEMPLATE_ROUNDS_LOAD: 'API_FIXTURE_TEMPLATE_ROUNDS_LOAD',
  API_FIXTURE_TEMPLATE_ROUNDS_SUCCESS: 'API_FIXTURE_TEMPLATE_ROUNDS_SUCCESS',

  ////Get Year
  API_GET_YEAR_LOAD: 'API_GET_YEAR_LOAD',
  API_GET_YEAR_SUCCESS: "API_GET_YEAR_SUCCESS",
  API_GET_YEAR_FAIL: "API_GET_YEAR_FAIL",
  API_GET_YEAR_ERROR: "API_GET_YEAR_ERROR",


  /////////get the default competition logo api
  API_COMPETITION_FEE_DEFAULT_LOGO_LOAD: "API_COMPETITION_FEE_DEFAULT_LOGO_LOAD",
  API_COMPETITION_FEE_DEFAULT_LOGO_SUCCESS: "API_COMPETITION_FEE_DEFAULT_LOGO_SUCCESS",

  /////time slots

  API_GET_COMPETITION_WITH_TIME_SLOTS_LOAD: "API_GET_COMPETITION_WITH_TIME_SLOTS_LOAD",
  API_GET_COMPETITION_WITH_TIME_SLOTS_SUCCESS: "API_GET_COMPETITION_WITH_TIME_SLOTS_SUCCESS",

  //competition fail and eror
  API_COMPETITION_ERROR: "API_COMPETITION_ERROR",
  API_COMPETITION_FAIL: "API_COMPETITION_FAIL",



  API_GET_YEAR_COMPETITION_LOAD: 'API_GET_YEAR_COMPETITION_LOAD',
  API_GET_YEAR_COMPETITION_SUCCESS: "API_GET_YEAR_COMPETITION_SUCCESS",
  API_GET_YEAR_COMPETITION_FAIL: "API_GET_YEAR_COMPETITION_FAIL",
  API_GET_YEAR_COMPETITION_ERROR: "API_GET_YEAR_COMPETITION_ERROR",


  /* *********** Competition Management Starts ****************** */

  // Competition Generate Draw
  API_GENERATE_DRAW_SUCCESS: "API_GENERATE_DRAW_SUCCESS",
  API_GENERATE_DRAW_LOAD: "API_GENERATE_DRAW_LOAD",
  API_GENERATE_DRAW_FAIL: "API_GENERATE_DRAW_FAIL",
  API_GENERATE_DRAW_ERROR: "API_GENERATE_DRAW_ERROR",

  // Competition Format Get
  API_GET_COMPETITION_FORMAT_SUCCESS: "API_GET_COMPETITION_FORMAT_SUCCESS",
  API_GET_COMPETITION_FORMAT_LOAD: "API_GET_COMPETITION_FORMAT_LOAD",

  // Competition Format Save
  API_SAVE_COMPETITION_FORMAT_SUCCESS: "API_SAVE_COMPETITION_FORMAT_SUCCESS",
  API_SAVE_COMPETITION_FORMAT_LOAD: "API_SAVE_COMPETITION_FORMAT_LOAD",

  API_COMPETITION_FORMAT_FAIL: "API_COMPETITION_FORMAT_FAIL",
  API_COMPETITION_FORMAT_ERROR: "API_COMPETITION_FORMAT_ERROR",

  // Competition Finals Get
  API_GET_COMPETITION_FINALS_SUCCESS: "API_GET_COMPETITION_FINALS_SUCCESS",
  API_GET_COMPETITION_FINALS_LOAD: "API_GET_COMPETITION_FINALS_LOAD",

  // Competition Finals Save
  API_SAVE_COMPETITION_FINALS_SUCCESS: "API_SAVE_COMPETITION_FINALS_SUCCESS",
  API_SAVE_COMPETITION_FINALS_LOAD: "API_SAVE_COMPETITION_FINALS_LOAD",

  API_COMPETITION_FINALS_FAIL: "API_COMPETITION_FINALS_FAIL",
  API_COMPETITION_FINALS_ERROR: "API_COMPETITION_FINALS_ERROR",

  // Ladder Format Get
  API_GET_LADDER_FORMAT_SUCCESS: "API_GET_LADDER_FORMAT_SUCCESS",
  API_GET_LADDER_FORMAT_LOAD: "API_GET_LADDER_FORMAT_LOAD",

  // Ladder Format Save
  API_SAVE_LADDER_FORMAT_SUCCESS: "API_SAVE_LADDER_FORMAT_SUCCESS",
  API_SAVE_LADDER_FORMAT_LOAD: "API_SAVE_LADDER_FORMAT_LOAD",

  API_LADDER_FORMAT_FAIL: "API_LADDER_FORMAT_FAIL",
  API_LADDER_FORMAT_ERROR: "API_LADDER_FORMAT_ERROR",

  //Match Types
  API_MATCH_TYPES_LOAD: "API_MATCH_TYPES_LOAD",
  API_MATCH_TYPES_SUCCESS: "API_MATCH_TYPES_SUCCESS",

  //Update Competition Format
  UPDATE_COMPETITION_FORMAT: "UPDATE_COMPETITION_FORMAT",

  //Update Competition Finals
  UPDATE_COMPETITION_FINALS: "UPDATE_COMPETITION_FINALS",

  //Update Ladder Format
  UPDATE_LADDER_FORMAT: "UPDATE_LADDER_FORMAT",

  //Competition Types Reference
  API_COMPETITION_TYPES_LOAD: "API_COMPETITION_TYPES_LOAD",
  API_COMPETITION_TYPES_SUCCESS: "API_COMPETITION_TYPES_SUCCESS",

  //Competition Formats
  API_COMPETITION_FORMAT_TYPES_LOAD: "API_COMPETITION_FORMAT_TYPES_LOAD",
  API_COMPETITION_FORMAT_TYPES_SUCCESS: "API_COMPETITION_FORMAT_TYPES_SUCCESS",

  /* ********** Competition Management Ends ***************** */


  //competition time and slot fail and eror
  API_COMPETITION_TIMESLOT_ERROR: "API_COMPETITION_TIMESLOT_ERROR",
  API_COMPETITION_TIMESLOT_FAIL: "API_COMPETITION_TIMESLOT_FAIL",

  //update competition time and slots
  UPDATE_POST_DATA_TIME_SLOTS_COMPETITION: "UPDATE_POST_DATA_TIME_SLOTS_COMPETITION",
  updateTimeSlotData: "updateTimeSlotData",
  API_TIME_SLOT_INIT_LOAD: "API_TIME_SLOT_INIT_LOAD",
  API_TIME_SLOT_INIT_SUCCESS: "API_TIME_SLOT_INIT_SUCCESS",
  API_COMMON_SAGA_ERROR: "API_COMMON_SAGA_ERROR",
  API_COMMON_SAGA_FAIL: "API_COMMON_SAGA_FAIL",

  ////Common Refrence Constant
  API_GET_COMMON_REF_DATA_LOAD: 'API_GET_COMMON_REF_DATA_LOAD',
  API_GET_COMMON_REF_DATA_SUCCESS: "API_GET_COMMON_REF_DATA_SUCCESS",

  API_ADD_VENUE_LOAD: "API_ADD_VENUE_LOAD",
  API_ADD_VENUE_SUCCESS: "API_ADD_VENUE_SUCCESS",

  ////VENUE CONSTRAINTS List
  API_VENUE_CONSTRAINTS_LIST_LOAD: 'API_VENUE_CONSTRAINTS_LIST_LOAD',
  API_VENUE_CONSTRAINTS_LIST_SUCCESS: "API_VENUE_CONSTRAINTS_LIST_SUCCESS",
  API_VENUE_CONSTRAINTS_LIST_FAIL: "API_VENUE_CONSTRAINTS_LIST_FAIL",
  API_VENUE_CONSTRAINTS_LIST_ERROR: "API_VENUE_CONSTRAINTS_LIST_ERROR",

  API_REFRESH_VENUE_FIELDS: "API_REFRESH_VENUE_FIELDS",
  API_UPDATE_COMPETITION_LIST: "API_UPDATE_COMPETITION_LIST",
  API_UPDATE_VENUE_TIME_DATA: "API_UPDATE_VENUE_TIME_DATA",

  API_UPDATE_VENUE_CONSTRAINTS_DATA: "API_UPDATE_VENUE_CONSTRAINTS_DATA",

  ////Venue List for own competitionvenue and times
  API_VENUE_LIST_LOAD: 'API_VENUE_LIST_LOAD',
  API_VENUE_LIST_SUCCESS: "API_VENUE_LIST_SUCCESS",

  //competition part player grading fail and eror
  API_COMPETITION_PART_PLAYER_GRADING_FAIL: "API_COMPETITION_PART_PLAYER_GRADING_FAIL",
  API_COMPETITION_PART_PLAYER_GRADING_ERROR: "API_COMPETITION_PART_PLAYER_GRADING_ERROR",


  //competition part player grade calculate player grading summary get API
  API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD: "API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD",
  API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS: "API_GET_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS",

  /////////////competition part player grade calculate player grading summary data on Change table input
  ONCHANGE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_DATA: "ONCHANGE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_DATA",

  //competition own proposed team grading  fail and eror
  API_COMPETITION_OWN_TEAM_GRADING_FAIL: "API_COMPETITION_OWN_TEAM_GRADING_FAIL",
  API_COMPETITION_OWN_TEAM_GRADING_ERROR: "API_COMPETITION_OWN_TEAM_GRADING_ERROR",


  //competition own proposed team grading get api
  API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_LOAD: "API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_LOAD",
  API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_OWN_PROPOSED_TEAM_GRADING_LIST_SUCCESS",

  /////////////competition own proposed team grading data on Change table input
  ONCHANGE_COMPETITION_OWN_PROPOSED_TEAM_GRADING_DATA: "ONCHANGE_COMPETITION_OWN_PROPOSED_TEAM_GRADING_DATA",

  /* Affilaites Starts here  */

  // Affilaite Save
  API_SAVE_AFFILIATE_SUCCESS: "API_SAVE_AFFILIATE_SUCCESS",
  API_SAVE_AFFILIATE_LOAD: "API_SAVE_AFFILIATE_LOAD",

  // AffiliatesListing
  API_AFFILIATES_LISTING_SUCCESS: "API_AFFILIATES_LISTING_SUCCESS",
  API_AFFILIATES_LISTING_LOAD: "API_AFFILIATES_LISTING_LOAD",

  // UserDashboard Textual
  API_USER_DASHBOARD_TEXTUAL_SUCCESS: "API_USER_DASHBOARD_TEXTUAL_SUCCESS",
  API_USER_DASHBOARD_TEXTUAL_LOAD: "API_USER_DASHBOARD_TEXTUAL_LOAD",

  // User Module Personal Details
  API_USER_MODULE_PERSONAL_DETAIL_SUCCESS: "API_USER_MODULE_PERSONAL_DETAIL_SUCCESS",
  API_USER_MODULE_PERSONAL_DETAIL_LOAD: "API_USER_MODULE_PERSONAL_DETAIL_LOAD",

  // User Module Medical Info
  API_USER_MODULE_MEDICAL_INFO_SUCCESS: "API_USER_MODULE_MEDICAL_INFO_SUCCESS",
  API_USER_MODULE_MEDICAL_INFO_LOAD: "API_USER_MODULE_MEDICAL_INFO_LOAD",

  //Affiliate by organisation used for both our organisation and by clicking the affiliates listing item
  API_AFFILIATE_BY_ORGANISATION_SUCCESS: "API_AFFILIATE_BY_ORGANISATION_SUCCESS",
  API_AFFILIATE_BY_ORGANISATION_LOAD: "API_AFFILIATE_BY_ORGANISATION_LOAD",
  API_AFFILIATE_OUR_ORGANISATION_SUCCESS: "API_AFFILIATE_OUR_ORGANISATION_SUCCESS",
  API_AFFILIATE_OUR_ORGANISATION_LOAD: "API_AFFILIATE_OUR_ORGANISATION_LOAD",

  // This is used in drop down values for selecting the organisation to affiliate
  API_AFFILIATE_TO_ORGANISATION_SUCCESS: "API_AFFILIATE_TO_ORGANISATION_SUCCESS",
  API_AFFILIATE_TO_ORGANISATION_LOAD: "API_AFFILIATE_TO_ORGANISATION_LOAD",

  // This is used in drop down values for selecting the organisation to affiliate
  API_AFFILIATE_DELETE_SUCCESS: "API_AFFILIATE_DELETE_SUCCESS",
  API_AFFILIATE_DELETE_LOAD: "API_AFFILIATE_DELETE_LOAD",

  API_USER_FAIL: "API_USER_FAIL",
  API_USER_ERROR: "API_USER_ERROR",

  //Update Affiliate
  UPDATE_AFFILIATE: "UPDATE_AFFILIATE",
  UPDATE_NEW_AFFILIATE: "UPDATE_NEW_AFFILIATE",
  UPDATE_ORG_AFFILIATE: "UPDATE_ORG_AFFILIATE",

  UPDATE_USER_MODULE: "UPDATE_USER_MODULE",
  /*  Affiliates Ends here  */

  ///get the divisions list on the basis of year and competition
  API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_LOAD: "API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_LOAD",
  API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_SUCCESS: "API_GET_DIVISIONS_LIST_ON_YEAR_AND_COMPETITION_SUCCESS",

  ///get the grades reference data
  API_GRADES_REFERENCE_LIST_LOAD: 'API_GRADES_REFERENCE_LIST_LOAD',
  API_GRADES_REFERENCE_LIST_SUCCESS: "API_GRADES_REFERENCE_LIST_SUCCESS",

  //competition own final team grading save  api
  API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_LOAD: "API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_LOAD",
  API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_SUCCESS: "API_SAVE_COMPETITION_OWN_FINAL_TEAM_GRADING_SUCCESS",

  //clear own  competition  team grading reducer data
  OWN_COMP_TEAM_GRADING_CLEARING_PARTICULAR_REDUCER_DATA: "OWN_COMP_TEAM_GRADING_CLEARING_PARTICULAR_REDUCER_DATA",

  //////competition part  proposed team grading get api
  API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_LOAD: "API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_LOAD",
  API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_PART_PROPOSED_TEAM_GRADING_LIST_SUCCESS",


  /////////////competition part  proposed team grading data on Change table input
  ONCHANGE_COMPETITION_PART_PROPOSED_TEAM_GRADING_DATA: "ONCHANGE_COMPETITION_PART_PROPOSED_TEAM_GRADING_DATA",

  //competition part proposed team grading save  api
  API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_LOAD: "API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_LOAD",
  API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_SUCCESS: "API_SAVE_COMPETITION_PART_PROPOSED_TEAM_GRADING_SUCCESS",

  //add remove time slot 
  UPDATE_POST_DATA_TIME_SLOTS_MANUAL_COMPETITION: "UPDATE_POST_DATA_TIME_SLOTS_MANUAL_COMPETITION",
  Api_ADD_REMOVE_TIME_SLOT_TABLE: "Api_ADD_REMOVE_TIME_SLOT_TABLE",


  //post api time slot for save time slots
  API_COMPETITION_TIMESLOT_POST_LOAD: "API_COMPETITION_TIMESLOT_POST_LOAD",
  API_COMPETITION_TIMESLOT_POST_SUCCESS: "API_COMPETITION_TIMESLOT_POST_SUCCESS",

  ////save the competition part player grade calculate player grading summary or say proposed player grading toggle
  API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD: "API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_LOAD",
  API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS: "API_SAVE_COMPETITION_PART_PLAYER_GRADE_CALCULATE_SUMMMARY_LIST_SUCCESS",


  //////////get the own team grading summary listing data
  API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_LOAD: "API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_LOAD",
  API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_SUCCESS: "API_GET_COMPETITION_OWN_TEAM_GRADING_SUMMARY_LIST_SUCCESS",

  //competition part player grading get API 
  API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_LOAD: "API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_LOAD",
  API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_SUCCESS: "API_GET_COMPETITION_PART_PLAYER_GRADING_LIST_SUCCESS",


  //clear particular reducer data of competition part player grading 
  CLEARING_COMPETITION_PART_PLAYER_GRADING_REDUCER_DATA: "CLEARING_COMPETITION_PART_PLAYER_GRADING_REDUCER_DATA",

  // Competition Draws
  API_GET_COMPETITION_DRAWS_SUCCESS: "API_GET_COMPETITION_DRAWS_SUCCESS",
  API_GET_COMPETITION_DRAWS_LOAD: "API_GET_COMPETITION_DRAWS_LOAD",

  API_COMPETITION_DRAWS_FAIL: "API_COMPETITION_DRAWS_FAIL",
  API_COMPETITION_DRAWS_ERROR: "API_COMPETITION_DRAWS_ERROR",

  // Competition draws rounds 
  API_GET_COMPETITION_DRAWS_ROUNDS_LOAD: "API_GET_COMPETITION_DRAWS_ROUNDS_LOAD",
  API_GET_COMPETITION_DRAWS_ROUNDS_SUCCESS: "API_GET_COMPETITION_DRAWS_ROUNDS_SUCCESS",


  API_VENUE_CONSTRAINT_POST_LOAD: "API_VENUE_CONSTRAINT_POST_LOAD",
  API_VENUE_CONSTRAINT_POST_SUCCESS: "API_VENUE_CONSTRAINT_POST_SUCCESS",
  API_VENUE_CONSTRAINT_POST_FAIL: "API_VENUE_CONSTRAINT_POST_FAIL",
  API_VENUE_CONSTRAINT_POST_ERROR: "API_VENUE_CONSTRAINT_POST_ERROR",

  ////clear venue and time data after competition change
  CLEAR_VENUE_TIMES_DATA: "CLEAR_VENUE_TIMES_DATA",

  ////delete prefence object
  DELETE_PREFENCE_OBJECT: "DELETE_PREFENCE_OBJECT",

  /////////save the changed grade name in own competition team grading summary data
  API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_LOAD: "API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_LOAD",
  API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_SUCCESS: "API_SAVE_UPDATED_GRADE_NAME_TEAM_GRADING_SUMMARY_SUCCESS",

  ////////////team grading summary publish
  API_PUBLISH_TEAM_GRADING_SUMMARY_LOAD: "API_PUBLISH_TEAM_GRADING_SUMMARY_LOAD",
  API_PUBLISH_TEAM_GRADING_SUMMARY_SUCCESS: "API_PUBLISH_TEAM_GRADING_SUMMARY_SUCCESS",


  /////////////competition team grading summary onchange table data
  ONCHANGE_COMPETITION_TEAM_GRADING_SUMMARY_DATA: "ONCHANGE_COMPETITION_TEAM_GRADING_SUMMARY_DATA",


  //// Update draws
  API_UPDATE_COMPETITION_DRAWS_LOAD: "API_UPDATE_COMPETITION_DRAWS_LOAD",
  API_UPDATE_COMPETITION_DRAWS_SUCCESS: "API_UPDATE_COMPETITION_DRAWS_SUCCESS",

  //// Save Draws
  API_UPDATE_COMPETITION_SAVE_DRAWS_LOAD: "API_UPDATE_COMPETITION__SAVE_DRAWS_LOAD",
  API_UPDATE_COMPETITION_SAVE_DRAWS_SUCCESS: "API_UPDATE_COMPETITION__SAVE_DRAWS_SUCCESS",

  ///clear competion data
  CLEAR_COMPETITION_DATA: "CLEAR_COMPETITION_DATA",

  ////Api Add/Edit Player
  API_LIVE_SCORE_ADD_EDIT_PLAYER_LOAD: "API_LIVE_SCORE_ADD_EDIT_PLAYER_LOAD",
  API_LIVE_SCORE_ADD_EDIT_PLAYER_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_PLAYER_SUCCESS",

  ////Update Player Data
  API_LIVE_SCORE_UPDATE_PLAYER: "API_LIVE_SCORE_UPDATE_PLAYER",

  API_LIVE_SCORE_FAIL: "API_LIVE_SCORE_FAIL",
  API_LIVE_SCORE_ERROR: "API_LIVE_SCORE_ERROR",

  API_USER_PROFILE_UPDATE_PLAYER: "API_USER_PROFILE_UPDATE_PLAYER",

  ////Update Edit User Data
  API_USER_PROFILE_UPDATE_LOAD: "API_USER_PROFILE_UPDATE_LOAD",
  API_USER_PROFILE_UPDATE_SUCCESS: "API_USER_PROFILE_UPDATE_SUCCESS",

  // Get User Detail
  API_USER_DETAIL_LOAD: "API_USER_DETAIL_LOAD",
  API_USER_DETAIL_SUCCESS: "API_USER_DETAIL_SUCCESS",

  // Update User Photo
  API_USER_PHOTO_UPDATE_LOAD: "API_USER_PHOTO_UPDATE_LOAD",
  API_USER_PHOTO_UPDATE_SUCCESS: "API_USER_PHOTO_UPDATE_SUCCESS",

  // Update User Detail
  API_USER_DETAIL_UPDATE_LOAD: "API_USER_DETAIL_UPDATE_LOAD",
  API_USER_DETAIL_UPDATE_SUCCESS: "API_USER_DETAIL_UPDATE_SUCCESS",

  // Update User Detail
  API_USER_PASSWORD_UPDATE_LOAD: "API_USER_PASSWORD_UPDATE_LOAD",
  API_USER_PASSWORD_UPDATE_SUCCESS: "API_USER_PASSWORD_UPDATE_SUCCESS",

  ///Add/Edit Manager
  API_LIVE_SCORE_ADD_EDIT_MANAGER_LOAD: "API_LIVE_SCORE_ADD_EDIT_MANAGER_LOAD",
  API_LIVE_SCORE_ADD_EDIT_MANAGER_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_MANAGER_SUCCESS",


  ////Dashboard
  API_LIVE_SCORE_DASHBOARD_LOAD: "API_LIVE_SCORE_DASHBOARD_LOAD",
  API_LIVE_SCORE_DASHBOARD_SUCCESS: "API_LIVE_SCORE_DASHBOARD_SUCCESS",

  //liveScore addBanner update	
  API_LIVE_SCORE_ADD_BANNER_UPDATE: "API_LIVE_SCORE_ADD_BANNER_UPDATE",

  //liveScore clear banner reducer	
  API_LIVE_SCORE_CLEAR_BANNER_REDUCER: "API_LIVE_SCORE_CLEAR_BANNER_REDUCER",
  //// Get Competition Venue

  API_GET_COMPETITION_VENUES_LOAD: "API_GET_COMPETITION_VENUES_LOAD",
  API_GET_COMPETITION_VENUES_SUCCESS: "API_GET_COMPETITION_VENUES_SUCCESS",

  //// Added 2 March***Start

  ////News saga fail and error
  API_NEWS_SAGA_FAIL: "API_NEWS_SAGA_FAIL",
  API_NEWS_SAGA_ERROR: "API_NEWS_SAGA_ERROR",

  API_LIVE_SCORE_MANAGER_FAIL: "API_LIVE_SCORE_MANAGER_FAIL",
  API_LIVE_SCORE_MANAGER_ERROR: "API_LIVE_SCORE_MANAGER_ERROR",

  API_LIVE_SCORE_UPDATE_MANAGER_DATA: "API_LIVE_SCORE_UPDATE_MANAGER_DATA",

  API_LIVE_SCORE_BULK_MATCH_FAIL: "API_LIVE_SCORE_BULK_MATCH_FAIL",
  API_LIVE_SCORE_BULK_MATCH_ERROR: "API_LIVE_SCORE_BULK_MATCH_ERROR",

  API_LIVE_SCORE_DASHBOARD_FAIL: "API_LIVE_SCORE_DASHBOARD_FAIL",
  API_LIVE_SCORE_DASHBOARD_ERROR: "API_LIVE_SCORE_DASHBOARD_ERROR",

  API_LIVE_SCORE_GOAL_FAIL: "API_LIVE_SCORE_GOAL_FAIL",
  API_LIVE_SCORE_GOAL_ERROR: "API_LIVE_SCORE_GOAL_ERROR",

  //// Added 2 March***End
  /// get oragnasation load for add Venue
  API_ORGANISATION_LOAD: "API_ORGANISATION_LOAD",
  API_ORGANISATION_SUCCESS: "API_ORGANISATION_SUCCESS",


  //  delete add venue GameDays object
  DELETE_PREFENCE_OBJECT_ADD_VENUE: "DELETE_PREFENCE_OBJECT_ADD_VENUE",

  API_LIVE_SCORE_PLAYER_FAIL: "API_LIVE_SCORE_PLAYER_FAIL",
  API_LIVE_SCORE_PLAYER_ERROR: "API_LIVE_SCORE_PLAYER_ERROR",

  ///////////get the competition final grades on the basis of competition and division
  API_GET_COMPETITION_FINAL_GRADES_LIST_LOAD: "API_GET_COMPETITION_FINAL_GRADES_LIST_LOAD",
  API_GET_COMPETITION_FINAL_GRADES_LIST_SUCCESS: "API_GET_COMPETITION_FINAL_GRADES_LIST_SUCCESS",

  //////update draws court timing where N/A(null) is there
  API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_LOAD: "API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_LOAD",
  API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_SUCCESS: "API_UPDATE_COMPETITION_DRAWS_COURT_TIMINGS_SUCCESS",
  //clear match data
  API_LIVE_SCORE_CLEAR_MATCH_DATA: "API_LIVE_SCORE_CLEAR_MATCH_DATA",

  API_LIVE_SCORE_DELETE_MATCH_LOAD: "API_LIVE_SCORE_DELETE_MATCH_LOAD",
  API_LIVE_SCORE_DELETE_MATCH_SUCCESS: "API_LIVE_SCORE_DELETE_MATCH_SUCCESS",

  //// 6 March
  API_GET_TEAM_VIEW_PLAYER_LIST_LOAD: "API_GET_TEAM_VIEW_PLAYER_LIST_LOAD",
  API_GET_TEAM_VIEW_PLAYER_LIST_SUCCESS: "API_GET_TEAM_VIEW_PLAYER_LIST_SUCCESS",

  API_LIVE_SCORE_DELETE_TEAM_LOAD: "API_LIVE_SCORE_DELETE_TEAM_LOAD",
  API_LIVE_SCORE_DELETE_TEAM_SUCCESS: "API_LIVE_SCORE_DELETE_TEAM_SUCCESS",

  ///Favourite Team Reference List
  API_FAVOURITE_TEAM_REFERENCE_LOAD: 'API_FAVOURITE_TEAM_REFERENCE_LOAD',
  API_FAVOURITE_TEAM_REFERENCE_SUCCESS: "API_FAVOURITE_TEAM_REFERENCE_SUCCESS",

  /// Firebird Player Reference  List
  API_FIREBIRD_PLAYER_REFERENCE_LOAD: 'API_FIREBIRD_PLAYER_REFERENCE_LOAD',
  API_FIREBIRD_PLAYER_REFERENCE_SUCCESS: "API_FIREBIRD_PLAYER_REFERENCE_SUCCESS",

  //Registration Other Info Reference List
  API_REGISTRATION_OTHER_INFO_REFERENCE_LOAD: 'API_REGISTRATION_OTHER_INFO_REFERENCE_LOAD',
  API_REGISTRATION_OTHER_INFO_REFERENCE_SUCCESS: "API_REGISTRATION_OTHER_INFO_REFERENCE_SUCCESS",

  //Country Reference List
  API_COUNTRY_REFERENCE_LOAD: 'API_COUNTRY_REFERENCE_LOAD',
  API_COUNTRY_REFERENCE_SUCCESS: "API_COUNTRY_REFERENCE_SUCCESS",

  //Natiionality List
  API_NATIONALITY_REFERENCE_LOAD: 'API_NATIONALITY_REFERENCE_LOAD',
  API_NATIONALITY_REFERENCE_SUCCESS: "API_NATIONALITY_REFERENCE_SUCCESS",

  //HeardBy List
  API_HEARDBY_REFERENCE_LOAD: 'API_HEARDBY_REFERENCE_LOAD',
  API_HEARDBY_REFERENCE_SUCCESS: "API_HEARDBY_REFERENCE_SUCCESS",

  ///save end user registration
  API_SAVE_END_USER_REGISTRATION_LOAD: "API_SAVE_END_USER_REGISTRATION_LOAD",
  API_SAVE_END_USER_REGISTRATION_SUCCESS: "API_SAVE_END_USER_REGISTRATION_SUCCESS",

  ///Organisation Registration Registration Settings
  API_ORG_REGISTRATION_REG_SETTINGS_LOAD: "API_ORG_REGISTRATION_REG_SETTINGS_LOAD",
  API_ORG_REGISTRATION_REG_SETTINGS_SUCCESS: "API_ORG_REGISTRATION_REG_SETTINGS_SUCCESS",

  ///End User Registration Membership Products 
  API_MEMBERSHIP_PRODUCT_END_USER_REG_LOAD: "API_MEMBERSHIP_PRODUCT_END_USER_REG_LOAD",
  API_MEMBERSHIP_PRODUCT_END_USER_REG_SUCCESS: "API_MEMBERSHIP_PRODUCT_END_USER_REG_SUCCESS",

  ///Api End User Registration Failed
  API_END_USER_REGISTRATION_FAIL: "API_END_USER_REGISTRATION_FAIL",
  API_END_USER_REGISTRATION_ERROR: "API_END_USER_REGISTRATION_ERROR",

  UPDATE_END_USER_REGISTRATION: "UPDATE_END_USER_REGISTRATION",

  //Player Position Reference 
  API_PLAYER_POSITION_REFERENCE_LOAD: 'API_PLAYER_POSITION_REFERENCE_LOAD',
  API_PLAYER_POSITION_REFERENCE_SUCCESS: "API_PLAYER_POSITION_REFERENCE_SUCCESS",

  /// get particular user organisation
  API_GET_USER_ORGANISATION_LOAD: "API_GET_USER_ORGANISATION_LOAD",
  API_GET_USER_ORGANISATION_SUCCESS: "API_GET_USER_ORGANISATION_SUCCESS",


  ////onchange user organisation data
  ONCHANGE_USER_ORGANISATION: "ONCHANGE_USER_ORGANISATION",
  //// Live score only division 
  API_LIVE_SCORE_ONLY_DIVISION_LOAD: "API_LIVE_SCORE_ONLY_DIVISION_LOAD",
  API_LIVE_SCORE_ONLY_DIVISION_SUCCESS: "API_LIVE_SCORE_ONLY_DIVISION_SUCCESS",
  API_LIVE_SCORE_ONLY_DIVISION_FAIL: "API_LIVE_SCORE_ONLY_DIVISION_FAIL",
  API_LIVE_SCORE_ONLY_DIVISION_ERROR: "API_LIVE_SCORE_ONLY_DIVISION_ERROR",
  ///Search_Venue_updated
  Search_Venue_updated: "Search_Venue_updated",
  CLEAR_FILTER_SEARCH: "CLEAR_FILTER_SEARCH",
  // LIveScore Filter Manager by Name 
  API_LIVESCORE_MANAGER_FILTER: "API_LIVESCORE_MANAGER_FILTER",
  CLEAR_LIVESCORE_MANAGER: "CLEAR_LIVESCORE_MANAGER",
  // live score Compention dashboard
  API_LIVESCORE_COMPETITION_INITATE: "API_LIVESCORE_COMPETITION_INITATE",
  API_LIVESCORE_COMPETITION_SUCCESS: "API_LIVESCORE_COMPETITION_SUCCESS",
  API_LIVESCORE_COMPETITION_ERROR: "API_LIVESCORE_COMPETITION_ERROR",


  //live score news
  API_LIVESCORE_NEWS_NOTIFICATION_LOAD: "API_LIVESCORE_NEWS_NOTIFICATION_LOAD",
  API_LIVESCORE_NEWS_NOTIFICATION_SUCCESS: "API_LIVESCORE_NEWS_NOTIFICATION_SUCCESS",

  API_LIVESCORE_DELETE_NEWS_LOAD: "API_LIVESCORE_DELETE_NEWS_LOAD",
  API_LIVESCORE_DELETE_NEWS_SUCCESS: "API_LIVESCORE_DELETE_NEWS_SUCCESS",
  API_DEFAULT_NEWS_IMAGE_VIDEO: "API_DEFAULT_NEWS_IMAGE_VIDEO",



  //livescore Competition Venue List
  API_LIVE_SCORE_COMPETITION_VENUES_LIST_LOAD: "API_LIVE_SCORE_COMPETITION_VENUES_LIST_LOAD",
  API_LIVE_SCORE_COMPETITION_VENUES_LIST_SUCCESS: "API_LIVE_SCORE_COMPETITION_VENUES_LIST_SUCCESS",
  //Livescore UPDATE DIVISION ACTION
  API_LIVE_SCORE_UPDATE_DIVISION: "API_LIVE_SCORE_UPDATE_DIVISION",

  //LiveScore create Division 
  API_LIVE_SCORE_CREATE_DIVISION_LOAD: "API_LIVE_SCORE_CREATE_DIVISION_LOAD",
  API_LIVE_SCORE_CREATE_DIVISION_SUCCESS: "API_LIVE_SCORE_CREATE_DIVISION_SUCCESS",

  //livescore delete division
  API_LIVE_SCORE_DELETE_DIVISION_LOAD: "API_LIVE_SCORE_DELETE_DIVISION_LOAD",
  API_LIVE_SCORE_DELETE_DIVISION_SUCCESS: "API_LIVE_SCORE_DELETE_DIVISION_SUCCESS",

  //liveScore Competition Delete
  API_LIVESCORE_COMPETION_DELETE_INITIATE: "API_LIVESCORE_COMPETION_DELETE_INITIATE",
  API_LIVESCORE_COMPETION_DELETE_SUCCESS: "API_LIVESCORE_COMPETION_DELETE_SUCCESS",
  API_LIVESCORE_COMPETION_DELETE_ERROR: "API_LIVESCORE_COMPETION_DELETE_ERROR",

  //livescore gametimestatistics
  API_LIVE_SCORE_GAME_TIME_STATISTICS_LIST_LOAD: "API_LIVE_SCORE_GAME_TIME_STATISTICS_LIST_LOAD",
  API_LIVE_SCORE_GAME_TIME_STATISTICS_LIST_SUCCESS: "API_LIVE_SCORE_GAME_TIME_STATISTICS_LIST_SUCCESS",
  API_LIVE_SCORE_GAME_TIME_STATISTICS_FAIL: "API_LIVE_SCORE_GAME_TIME_STATISTICS_FAIL",
  API_LIVE_SCORE_GAME_TIME_STATISTICS_ERROR: "API_LIVE_SCORE_GAME_TIME_STATISTICS_ERROR",
  ////Venues List in User Module
  API_VENUES_LIST_LOAD: 'API_VENUES_LIST_LOAD',
  API_VENUES_LIST_SUCCESS: "API_VENUES_LIST_SUCCESS",

  ////Venues delete in User Module
  API_VENUE_DELETE_LOAD: 'API_VENUE_DELETE_LOAD',
  API_VENUE_DELETE_SUCCESS: "API_VENUE_DELETE_SUCCESS",

  //player grading
  API_ADD_NEW_TEAM_LOAD: "API_ADD_NEW_TEAM_LOAD",
  API_ADD_NEW_TEAM_SUCCESS: 'API_ADD_NEW_TEAM_SUCCESS',

  //player grading drag and drop
  API_DRAG_NEW_TEAM_LOAD: "API_DRAG_NEW_TEAM_LOAD",
  API_DRAG_NEW_TEAM_SUCCESS: "API_DRAG_NEW_TEAM_SUCCESS",
  // live Score Setting View
  LiveScore_SETTING_VIEW_INITITAE: "LiveScore_SETTING_VIEW_INITITAE",
  LiveScore_SETTING_VIEW_SUCCESS: "LiveScore_SETTING_VIEW_SUCCESS",
  LiveScore_SETTING_VIEW_ERROR: "LiveScore_SETTING_VIEW_ERROR",
  LiveScore_SETTING_CHANGE_FORM: "LiveScore_SETTING_CHANGE_FORM",
  LiveScore_SETTING_DATA_POST_INITATE: "LiveScore_SETTING_DATA_POST_INITATE",
  LiveScore_SETTING_DATA_POST_SUCCESS: "LiveScore_SETTING_DATA_POST_SUCCESS",
  LiveScore_SETTING_DATA_POST_ERROR: "LiveScore_SETTING_DATA_POST_ERROR",

  // drag player in same team
  DRAG_PLAYER_IN_SAME_TEAM: "DRAG_PLAYER_IN_SAME_TEAM",

  LiveScore_CLEAR_SETTING: "LiveScore_CLEAR_SETTING",

  API_MATCH_RESULT_LOAD: "API_MATCH_RESULT_LOAD",
  API_MATCH_RESULT_SUCCESS: "API_MATCH_RESULT_SUCCESS",
  //livescore umpires
  API_LIVE_SCORE_UMPIRES_LIST_LOAD: "API_LIVE_SCORE_UMPIRES_LIST_LOAD",
  API_LIVE_SCORE_UMPIRES_LIST_SUCCESS: "API_LIVE_SCORE_UMPIRES_LIST_SUCCESS",
  API_LIVE_SCORE_UMPIRES_FAIL: "API_LIVE_SCORE_UMPIRES_FAIL",
  API_LIVE_SCORE_UMPIRES_ERROR: "API_LIVE_SCORE_UMPIRES_FAIL",
  // team edit
  LIVE_SCORE_TEAM_EDIT: "LIVE_SCORE_TEAM_EDIT",
  GET_DIVISION_TEAM: 'GET_DIVISION_AFFILATE_TEAM',
  GET_DIVISION_SUCCESS: 'GET_DIVISION_SUCCESS',
  GET_DIVISION_ERROR: 'GET_DIVISION_ERROR',
  GET_AFFILATE_TEAM: 'GET_AFFILATE_TEAM',
  GET_AFFILATE_SUCCESS: 'GET_AFFILATE_SUCCESS',
  GET_AFFILATE_ERROR: 'GET_AFFILATE_ERROR',
  LIVESCORE_ADD_TEAM: 'LIVESCORE_ADD_TEAM',
  API_VENUE_BY_ID_SUCCESS: "API_VENUE_BY_ID_SUCCESS",
  API_VENUE_BY_ID_LOAD: "API_VENUE_BY_ID_LOAD",

  API_LIVE_SCORE_BULK_ABANDON_MATCH_LOAD: "API_LIVE_SCORE_BULK_ABANDON_MATCH_LOAD",
  API_LIVE_SCORE_BULK_ABANDON_MATCH_SUCCESS: "API_LIVE_SCORE_BULK_ABANDON_MATCH_SUCCESS",

  API_LIVE_SCORE_MATCH_IMPORT_LOAD: "API_LIVE_SCORE_MATCH_IMPORT_LOAD",
  API_LIVE_SCORE_MATCH_IMPORT_SUCCESS: "API_LIVE_SCORE_MATCH_IMPORT_SUCCESS",

  API_LIVE_SCORE_GET_SCORER_LIST_LOAD: "API_LIVE_SCORE_GET_SCORER_LIST_LOAD",
  API_LIVE_SCORE_GET_SCORER_LIST_SUCCESS: "API_LIVE_SCORE_GET_SCORER_LIST_SUCCESS",
  API_GET_LIVESCOREMATCH_DETAIL_INITAITE: 'API_GET_LIVESCOREMATCH_DETAIL_INITAITE',
  API_GET_LIVESCOREMATCH_DETAIL_SUCCESS: 'API_GET_LIVESCOREMATCH_DETAIL_SUCCESS',
  API_GET_LIVESCOREMATCH_DETAIL_ERROR: 'API_GET_LIVESCOREMATCH_DETAIL_ERROR',

  ////Team import Saga
  API_LIVE_SCORE_TEAM_IMPORT_LOAD: "API_LIVE_SCORE_TEAM_IMPORT_LOAD",
  API_LIVE_SCORE_TEAM_IMPORT_SUCCESS: "API_LIVE_SCORE_TEAM_IMPORT_SUCCESS",

  ////Division Import Saga
  API_LIVE_SCORE_DIVISION_IMPORT_LOAD: "API_LIVE_SCORE_DIVISION_IMPORT_LOAD",
  API_LIVE_SCORE_DIVISION_IMPORT_SUCCESS: "API_LIVE_SCORE_DIVISION_IMPORT_SUCCESS",

  //update incident
  API_LIVE_SCORE_UPDATE_INCIDENT: 'API_LIVE_SCORE_UPDATE_MATCH',
  API_LIVE_SCORE_CLEAR_INCIDENT: "API_LIVE_SCORE_CLEAR_INCIDENT",
  //team attendance
  API_LIVE_SCORE_TEAM_ATTENDANCE_LIST_LOAD: "API_LIVE_SCORE_TEAM_ATTENDANCE_LIST_LOAD",
  API_LIVE_SCORE_TEAM_ATTENDANCE_LIST_SUCCESS: "API_LIVE_SCORE_TEAM_ATTENDANCE_LIST_SUCCESS",
  API_LIVE_SCORE_TEAM_ATTENDANCE_FAIL: "API_LIVE_SCORE_TEAM_ATTENDANCE_FAIL",
  API_LIVE_SCORE_TEAM_ATTENDANCE_ERROR: "API_LIVE_SCORE_TEAM_ATTENDANCE_ERROR",


  UPDATE_ROUNDS_TIME: "UPDATE_ROUNDS_TIME",
  API_LIVE_SCORE_ADD_TEAM_LOAD: "API_LIVE_SCORE_ADD_TEAM_LOAD",
  API_LIVE_SCORE_ADD_TEAM_SUCCESS: "API_LIVE_SCORE_ADD_TEAM_SUCCESS",

  API_LIVE_SCORE_GET_TEAM_LOAD: "API_LIVE_SCORE_GET_TEAM_LOAD",
  API_LIVE_SCORE_GET_TEAM_SUCCESS: "API_LIVE_SCORE_GET_TEAM_SUCCESS",


  API_GET_YEAR_OWN_COMPETITION_LOAD: 'API_GET_YEAR_OWN_COMPETITION_LOAD',
  API_GET_YEAR_OWN_COMPETITION_SUCCESS: "API_GET_YEAR_OWN_COMPETITION_SUCCESS",

  API_GET_YEAR_Participate_COMPETITION_LOAD: 'API_GET_YEAR_Participate_COMPETITION_LOAD',
  API_GET_YEAR_Participate_COMPETITION_SUCCESS: "API_GET_YEAR_Participate_COMPETITION_SUCCESS",
  LiveScore_SETTING_VIEW_FAIL: "LiveScore_SETTING_VIEW_FAIL",
  LiveScore_SETTING_SUCCESS: "LiveScore_SETTING_SUCCESS",
  // User Module Activity Player
  API_USER_MODULE_ACTIVITY_PLAYER_SUCCESS: "API_USER_MODULE_ACTIVITY_PLAYER_SUCCESS",
  API_USER_MODULE_ACTIVITY_PLAYER_LOAD: "API_USER_MODULE_ACTIVITY_PLAYER_LOAD",

  // User Module Activity Parent
  API_USER_MODULE_ACTIVITY_PARENT_SUCCESS: "API_USER_MODULE_ACTIVITY_PARENT_SUCCESS",
  API_USER_MODULE_ACTIVITY_PARENT_LOAD: "API_USER_MODULE_ACTIVITY_PARENT_LOAD",

  // User Module Activity Scorer
  API_USER_MODULE_ACTIVITY_SCORER_SUCCESS: "API_USER_MODULE_ACTIVITY_SCORER_SUCCESS",
  API_USER_MODULE_ACTIVITY_SCORER_LOAD: "API_USER_MODULE_ACTIVITY_SCORER_LOAD",

  // User Module Activity Manager
  API_USER_MODULE_ACTIVITY_MANAGER_SUCCESS: "API_USER_MODULE_ACTIVITY_MANAGER_SUCCESS",
  API_USER_MODULE_ACTIVITY_MANAGER_LOAD: "API_USER_MODULE_ACTIVITY_MANAGER_LOAD",

  API_USER_MODULE_PERSONAL_BY_COMPETITION_LOAD: "API_USER_MODULE_PERSONAL_BY_COMPETITION_LOAD",
  API_USER_MODULE_PERSONAL_BY_COMPETITION_SUCCESS: "API_USER_MODULE_PERSONAL_BY_COMPETITION_SUCCESS",

  API_USER_MODULE_REGISTRATION_LOAD: "API_USER_MODULE_REGISTRATION_LOAD",
  API_USER_MODULE_REGISTRATION_SUCCESS: "API_USER_MODULE_REGISTRATION_SUCCESS",

  API_LIVE_SCORE_PLAYER_IMPORT_LOAD: "API_LIVE_SCORE_PLAYER_IMPORT_LOAD",
  API_LIVE_SCORE_PLAYER_IMPORT_SUCCESS: "API_LIVE_SCORE_PLAYER_IMPORT_SUCCESS",

  CLEAR_FILTER_SEARCH_VENUE: "CLEAR_FILTER_SEARCH_VENUE",
  Search_Venue_updated_Competition: "Search_Venue_updated_Competition",

  API_CLEARING_VENUE_DATA: "API_CLEARING_VENUE_DATA",
  API_LIVE_SCORE_UPDATE_SCORER: "API_LIVE_SCORE_UPDATE_SCORER",
  API_LIVE_SCORE_ADD_EDIT_SCORER_LOAD: "API_LIVE_SCORE_ADD_EDIT_SCORER_LOAD",
  API_LIVE_SCORE_ADD_EDIT_SCORER_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_SCORER_SUCCESS",

  cleardrawsData: "cleardrawsData",
  API_LIVESCORE_ASSIGN_MATCHES_LOAD: "API_LIVESCORE_ASSIGN_MATCHES_LOAD",
  API_LIVESCORE_ASSIGN_MATCHES_SUCCESS: "API_LIVESCORE_ASSIGN_MATCHES_SUCCESS",
  API_LIVESCORE_ASSIGN_MATCHES_FAIL: "API_LIVESCORE_ASSIGN_MATCHES_FAIL",
  API_LIVESCORE_ASSIGN_MATCHES_ERROR: "API_LIVESCORE_ASSIGN_MATCHES_ERROR",

  API_LIVESCORE_ASSIGN_CHANGE_STATUS_LOAD: "API_LIVESCORE_ASSIGN_CHANGE_STATUS_LOAD",
  API_LIVESCORE_ASSIGN_CHANGE_STATUS_SUCCESS: "API_LIVESCORE_ASSIGN_CHANGE_STATUS_SUCCESS",

  API_LIVE_SCORE_UPDATE_VENUE_CHANGE: "API_LIVE_SCORE_UPDATE_VENUE_CHANGE",

  API_LIVESCORE_MANAGER_SEARCH_LOAD: "API_LIVESCORE_MANAGER_SEARCH_LOAD",
  API_LIVESCORE_MANAGER_SEARCH_SUCCESS: "API_LIVESCORE_MANAGER_SEARCH_SUCCESS",

  API_LIVE_SCORE_ROUND_LIST_LOAD: "API_LIVE_SCORE_ROUND_LIST_LOAD",
  API_LIVE_SCORE_ROUND_LIST_SUCCESS: "API_LIVE_SCORE_ROUND_LIST_SUCCESS",

  //Unassign Matches
  API_LIVESCORE_UNASSIGN_STATUS_LOAD: "API_LIVESCORE_UNASSIGN_STATUS_LOAD",
  API_LIVESCORE_UNASSIGN_STATUS_SUCCESS: "API_LIVESCORE_UNASSIGN_STATUS_SUCCESS",

  // Enhanced Round Robin Types
  API_ENHANCED_ROUND_ROBIN_LOAD: "API_ENHANCED_ROUND_ROBIN_LOAD",
  API_ENHANCED_ROUND_ROBIN_SUCCESS: "API_ENHANCED_ROUND_ROBIN_SUCCESS",

  API_PLAYER_GRADING_COMMENT_LOAD: "API_PLAYER_GRADING_COMMENT_LOAD",
  API_PLAYER_GRADING_COMMENT_SUCCESS: "API_PLAYER_GRADING_COMMENT_SUCCESS",


  API_PLAYER_GRADING_SUMMARY_COMMENT_LOAD: "API_PLAYER_GRADING_SUMMARY_COMMENT_LOAD",
  API_PLAYER_GRADING_SUMMARY_COMMENT_SUCCESS: "API_PLAYER_GRADING_SUMMARY_COMMENT_SUCCESS",


  API_TEAM_GRADING_COMMENT_LOAD: "API_TEAM_GRADING_COMMENT_LOAD",
  API_TEAM_GRADING_COMMENT_SUCCESS: "API_TEAM_GRADING_COMMENT_SUCCESS",

  API_PART_TEAM_GRADING_COMMENT_LOAD: "API_PART_TEAM_GRADING_COMMENT_LOAD",
  API_PART_TEAM_GRADING_COMMENT_SUCCESS: "API_PART_TEAM_GRADING_COMMENT_SUCCESS",

  API_REG_DASHBOARD_LIST_LOAD: "API_REG_DASHBOARD_LIST_LOAD",
  API_REG_DASHBOARD_LIST_SUCCESS: "API_REG_DASHBOARD_LIST_SUCCESS",
  API_REG_DASHBOARD_LIST_FAIL: "API_REG_DASHBOARD_LIST_FAIL",
  API_REG_DASHBOARD_LIST_ERROR: "API_REG_DASHBOARD_LIST_ERROR",


  API_GET_GENDER_LOAD: "API_GET_GENDER_LOAD",
  API_GET_GENDER_SUCCESS: "API_GET_GENDER_SUCCESS",

  //// Scorer Search 
  API_LIVESCORE_SCORER_SEARCH_LOAD: "API_LIVESCORE_SCORER_SEARCH_LOAD",
  API_LIVESCORE_SCORER_SEARCH_SUCCESS: "API_LIVESCORE_SCORER_SEARCH_SUCCESS",

  // match clubs
  API_LIVE_SCORE_CLUB_LIST_LOAD: "API_LIVE_SCORE_CLUB_LIST_LOAD",
  API_LIVE_SCORE_CLUB_LIST_SUCCESS: "API_LIVE_SCORE_CLUB_LIST_SUCCESS",


  API_LADDER_SETTING_GET_DATA_LOAD: "API_LADDER_SETTING_GET_DATA_LOAD",
  API_LADDER_SETTING_GET_DATA_SUCCESS: "API_LADDER_SETTING_GET_DATA_SUCCESS",

  UPDATE_LADDER_SETTING: "UPDATE_LADDER_SETTING",

  API_LADDER_SETTING_POST_DATA_LOAD: "API_LADDER_SETTING_POST_DATA_LOAD",
  API_LADDER_SETTING_POST_DATA_SUCCESS: "API_LADDER_SETTING_POST_DATA_SUCCESS",

  LIVESCORE_SEARCH__SETTING: "LIVESCORE_SEARCH__SETTING",
  // API_PART_TEAM_GRADING_COMMENT_LOAD: "API_PART_TEAM_GRADING_COMMENT_LOAD",
  // API_PART_TEAM_GRADING_COMMENT_SUCCESS: "API_PART_TEAM_GRADING_COMMENT_SUCCESS",



  API_LADDER_SETTING_MATCH_RESULT_LOAD: "API_LADDER_SETTING_MATCH_RESULT_LOAD",
  API_LADDER_SETTING_MATCH_RESULT_SUCCESS: "API_LADDER_SETTING_MATCH_RESULT_SUCCESS",

  API_LIVE_SCORE_LADDER_SETTING_FAIL: "API_LIVE_SCORE_LADDER_SETTING_FAIL",
  API_LIVE_SCORE_LADDER_SETTING_ERROR: "API_LIVE_SCORE_LADDER_SETTING_ERROR",

  //// Team list with pagging
  API_LIVE_SCORE_TEAM_WITH_PAGGING_LOAD: "API_LIVE_SCORE_TEAM_WITH_PAGGING_LOAD",
  API_LIVE_SCORE_TEAM_WITH_PAGGING_SUCCESS: "API_LIVE_SCORE_TEAM_WITH_PAGGING_SUCCESS",

  ///// Player list with pagging

  API_LIVE_SCORE_PLAYER_LIST_PAGGINATION_LOAD: "API_LIVE_SCORE_PLAYER_LIST_PAGGINATION_LOAD",
  API_LIVE_SCORE_PLAYER_LIST_PAGGINATION_SUCCESS: "API_LIVE_SCORE_PLAYER_LIST_PAGGINATION_SUCCESS",
  changeHoverProposedTeamGrading: "changeHoverProposedTeamGrading",


  API_USERCOUNT_LOAD: "API_USERCOUNT_LOAD",
  API_USERCOUNT_SUCCESS: "API_USERCOUNT_SUCCESS",
  API_USERCOUNT_FAIL: "API_USERCOUNT_FAIL",
  API_USERCOUNT_ERROR: "API_USERCOUNT_ERROR",

  clearHomeDashboardData: "clearHomeDashboardData",
  changeHoverPartProposedTeamGrading: "changeHoverPartProposedTeamGrading",



  ///// On Affiliate serach 
  API_COMPETITION_FEE_INVITEES_SEARCH_LOAD: "API_COMPETITION_FEE_INVITEES_SEARCH_LOAD",
  API_COMPETITION_FEE_INVITEES_SEARCH_SUCCESS: "API_COMPETITION_FEE_INVITEES_SEARCH_SUCCESS",

  ////Competition Player import Saga
  API_COMPETITION_PLAYER_IMPORT_LOAD: "API_COMPETITION_PLAYER_IMPORT_LOAD",
  API_COMPETITION_PLAYER_IMPORT_SUCCESS: "API_COMPETITION_PLAYER_IMPORT_SUCCESS",

  ////Competition Team import Saga
  API_COMPETITION_TEAMS_IMPORT_LOAD: "API_COMPETITION_TEAMS_IMPORT_LOAD",
  API_COMPETITION_TEAMS_IMPORT_SUCCESS: "API_COMPETITION_TEAMS_IMPORT_SUCCESS",

  ////Competition Team import Saga
  API_COMPETITION_IMPORT_DATA_CLEANUP: "API_COMPETITION_IMPORT_DATA_CLEANUP",

  API_SEARCH_COURT_LIST: "API_SEARCH_COURT_LIST",
  ///// Match Search 
  API_LIVE_MATCH_LOCAL_SEARCH: "API_LIVE_MATCH_LOCAL_SEARCH",


  setHomeDashboardYearKey: "setHomeDashboardYearKey",


  /// Organisation Venue list
  API_COMPETION_ORG_VENUE_LOAD: "API_COMPETION_ORG_VENUE_LOAD",
  API_COMPETION_ORG_VENUE_SUCCESS: "API_COMPETION_ORG_VENUE_SUCCESS",
  // Template Download POC
  API_GET_TEMPLATE_DOWNLOAD_SUCCESS: "API_GET_TEMPLATE_DOWNLOAD_SUCCESS",
  API_GET_TEMPLATE_DOWNLOAD_LOAD: "API_GET_TEMPLATE_DOWNLOAD_LOAD",

  ///// Exports - Live Score
  API_EXPORT_FILES_LOAD: "API_EXPORT_FILES_LOAD",
  API_EXPORT_FILES_SUCCESS: "API_EXPORT_FILES_SUCCESS",
  API_EXPORT_FILES_FAIL: "API_EXPORT_FILES_FAIL",
  API_EXPORT_FILES_ERROR: "API_EXPORT_FILES_ERROR",

  //// SAVE VENUE CHANGE 
  API_SAVE_VENUE_CHANGE_LOAD: "API_SAVE_VENUE_CHANGE_LOAD",
  API_SAVE_VENUE_CHANGE_SUCCESS: "API_SAVE_VENUE_CHANGE_SUCCESS",
  API_SAVE_VENUE_CHANGE_FAIL: "API_SAVE_VENUE_CHANGE_FAIL",
  API_SAVE_VENUE_CHANGE_ERROR: "API_SAVE_VENUE_CHANGE_ERROR",

  CLEAR_OWN_COMPETITION_DATA: "CLEAR_OWN_COMPETITION_DATA",

  /// Registration Dashboard
  API_USER_REG_DASHBOARD_LIST_LOAD: "API_USER_REG_DASHBOARD_LIST_LOAD",
  API_USER_REG_DASHBOARD_LIST_SUCCESS: "API_USER_REG_DASHBOARD_LIST_SUCCESS",
  API_USER_REG_DASHBOARD_LIST_FAIL: "API_USER_REG_DASHBOARD_LIST_FAIL",
  API_USER_REG_DASHBOARD_LIST_ERROR: "API_USER_REG_DASHBOARD_LIST_ERROR",

  // User Friend List
  API_USER_FRIEND_SUCCESS: "API_USER_FRIEND_SUCCESS",
  API_USER_FRIEND_LOAD: "API_USER_FRIEND_LOAD",

  // User Refer Friend List
  API_USER_REFER_FRIEND_SUCCESS: "API_USER_REFER_FRIEND_SUCCESS",
  API_USER_REFER_FRIEND_LOAD: "API_USER_REFER_FRIEND_LOAD",

  API_CLEAR_ROUND_DATA: "API_CLEAR_ROUND_DATA",

  API_LIVE_SCORE_GET_FIXTURE_COMP_LOAD: "API_LIVE_SCORE_GET_FIXTURE_COMP_LOAD",
  API_LIVE_SCORE_GET_FIXTURE_COMP_SUCCESS: "API_LIVE_SCORE_GET_FIXTURE_COMP_SUCCESS",
  API_LIVE_SCORE_GET_FIXTURE_COMP_FAIL: "API_LIVE_SCORE_GET_FIXTURE_COMP_FAIL",
  API_LIVE_SCORE_GET_FIXTURE_COMP_ERROR: "API_LIVE_SCORE_GET_FIXTURE_COMP_ERROR",

  /////draws division grade names list
  API_DRAWS_DIVISION_GRADE_NAME_LIST_LOAD: "API_DRAWS_DIVISION_GRADE_NAME_LIST_LOAD",
  API_DRAWS_DIVISION_GRADE_NAME_LIST_SUCCESS: "API_DRAWS_DIVISION_GRADE_NAME_LIST_SUCCESS",

  /////stripe payment API
  API_STRIPE_API_FAIL: "API_STRIPE_API_FAIL",
  API_STRIPE_API_ERROR: "API_STRIPE_API_ERROR",


  /////stripe payment account balance API
  API_STRIPE_ACCOUNT_BALANCE_API_LOAD: "API_STRIPE_ACCOUNT_BALANCE_API_LOAD",
  API_STRIPE_ACCOUNT_BALANCE_API_SUCCESS: "API_STRIPE_ACCOUNT_BALANCE_API_SUCCESS",

  /////For stripe charging payment API
  API_STRIPE_CHARGING_PAYMENT_API_LOAD: "API_STRIPE_CHARGING_PAYMENT_API_LOAD",
  API_STRIPE_CHARGING_PAYMENT_API_SUCCESS: "API_STRIPE_CHARGING_PAYMENT_API_SUCCESS",

  API_DRAW_PUBLISH_LOAD: "API_DRAW_PUBLISH_LOAD",
  API_DRAW_PUBLISH_SUCCESS: "API_DRAW_PUBLISH_SUCCESS",
  API_GET_INVOICE_LOAD: "API_GET_INVOICE_LOAD",
  API_GET_INVOICE_SUCCESS: "API_GET_INVOICE_SUCCESS",
  ////Competition Team Delete 
  API_COMPETITION_TEAM_DELETE_LOAD: "API_COMPETITION_TEAM_DELETE_LOAD",
  API_COMPETITION_TEAM_DELETE_SUCCESS: "API_COMPETITION_TEAM_DELETE_SUCCESS",

  ////Competition Team Action
  API_COMPETITION_TEAM_DELETE_ACTION_LOAD: "API_COMPETITION_TEAM_DELETE_ACTION_LOAD",
  API_COMPETITION_TEAM_DELETE_ACTION_SUCCESS: "API_COMPETITION_TEAM_DELETE_ACTION_SUCCESS",
  //PhotoType
  API_GET_PHOTO_TYPE_LOAD: "API_GET_PHOTO_TYPE_LOAD",
  API_GET_PHOTO_TYPE_SUCCESS: "API_GET_PHOTO_TYPE_SUCCESS",


  ///save stripe account
  API_SAVE_STRIPE_ACCOUNT_API_LOAD: "API_SAVE_STRIPE_ACCOUNT_API_LOAD",
  API_SAVE_STRIPE_ACCOUNT_API_SUCCESS: "API_SAVE_STRIPE_ACCOUNT_API_SUCCESS",

  // Get Org Photo 
  API_GET_ORG_PHOTO_SUCCESS: "API_GET_ORG_PHOTO_SUCCESS",
  API_GET_ORG_PHOTO_LOAD: "API_GET_ORG_PHOTO_LOAD",

  // Save Org Photo
  API_SAVE_ORG_PHOTO_SUCCESS: "API_SAVE_ORG_PHOTO_SUCCESS",
  API_SAVE_ORG_PHOTO_LOAD: "API_SAVE_ORG_PHOTO_LOAD",

  // Delete Org Photo
  API_DELETE_ORG_PHOTO_SUCCESS: "API_DELETE_ORG_PHOTO_SUCCESS",
  API_DELETE_ORG_PHOTO_LOAD: "API_DELETE_ORG_PHOTO_LOAD",

  //Draws Matches List export
  API_DRAW_MATCHES_LIST_LOAD: "API_DRAW_MATCHES_LIST_LOAD",
  API_DRAW_MATCHES_LIST_SUCCESS: "API_DRAW_MATCHES_LIST_SUCCESS",

  ////stripe login link
  API_GET_STRIPE_LOGIN_LINK_API_LOAD: "API_GET_STRIPE_LOGIN_LINK_API_LOAD",
  API_GET_STRIPE_LOGIN_LINK_API_SUCCESS: "API_GET_STRIPE_LOGIN_LINK_API_SUCCESS",

  ////stripe payments transfer list
  API_GET_STRIPE_PAYMENTS_TRANSFER_LIST_API_LOAD: "API_GET_STRIPE_PAYMENTS_TRANSFER_LIST_API_LOAD",
  API_GET_STRIPE_PAYMENTS_TRANSFER_LIST_API_SUCCESS: "API_GET_STRIPE_PAYMENTS_TRANSFER_LIST_API_SUCCESS",


  //Appy To Reference
  API_GET_APPY_TO_LOAD: "API_GET_APPY_TO_LOAD",
  API_GET_APPY_TO_SUCCESS: "API_GET_APPY_TO_SUCCESS",

  //Extra Time Draws Reference
  API_GET_EXTRA_TIME_DRAW_LOAD: "API_GET_EXTRA_TIME_DRAW_LOAD",
  API_GET_EXTRA_TIME_DRAW_SUCCESS: "API_GET_EXTRA_TIME_DRAW_SUCCESS",

  //Finals fixture Template Reference
  API_GET_FINAL_FIXTURE_TEMPLATE_LOAD: "API_GET_FINAL_FIXTURE_TEMPLATE_LOAD",
  API_GET_FINAL_FIXTURE_TEMPLATE_SUCCESS: "API_GET_FINAL_FIXTURE_TEMPLATE_SUCCESS",

  API_ALLOW_TEAM_REGISTRATION_TYPE_LOAD: "API_ALLOW_TEAM_REGISTRATION_TYPE_LOAD",
  API_ALLOW_TEAM_REGISTRATION_TYPE_SUCCESS: "API_ALLOW_TEAM_REGISTRATION_TYPE_SUCCESS",

  /////forgot password
  API_FORGOT_PASSWORD_LOAD: "API_FORGOT_PASSWORD_LOAD",
  API_FORGOT_PASSWORD_SUCCESS: "API_FORGOT_PASSWORD_SUCCESS",

  ///clear login reducer
  ACTION_TO_CLEAR_AUTHENTICATION_REDUCER: "ACTION_TO_CLEAR_AUTHENTICATION_REDUCER",
  Update_QuickCompetition_Data: "Update_QuickCompetition_Data",

  //////stripe payout list
  API_GET_STRIPE_PAYOUT_LIST_API_LOAD: "API_GET_STRIPE_PAYOUT_LIST_API_LOAD",
  API_GET_STRIPE_PAYOUT_LIST_API_SUCCESS: "API_GET_STRIPE_PAYOUT_LIST_API_SUCCESS",
  ///Own Competition Teams Export
  API_EXPORT_FINAL_TEAMS_LOAD: "API_EXPORT_FINAL_TEAMS_LOAD",
  API_EXPORT_FINAL_TEAMS_SUCCESS: "API_EXPORT_FINAL_TEAMS_SUCCESS",

  ///Participating Competition Teams Export
  API_EXPORT_PROPOSED_TEAMS_LOAD: "API_EXPORT_PROPOSED_TEAMS_LOAD",
  API_EXPORT_PROPOSED_TEAMS_SUCCESS: "API_EXPORT_PROPOSED_TEAMS_SUCCESS",

  ///Own Competition Payers Export
  API_EXPORT_FINAL_PLAYERS_LOAD: "API_EXPORT_FINAL_PLAYERS_LOAD",
  API_EXPORT_FINAL_PLAYERS_SUCCESS: "API_EXPORT_FINAL_PLAYERS_SUCCESS",

  ///Participating Competition Players Export
  API_EXPORT_PROPOSED_PLAYERS_LOAD: "API_EXPORT_PROPOSED_PLAYERS_LOAD",
  API_EXPORT_PROPOSED_PLAYERS_SUCCESS: "API_EXPORT_PROPOSED_PLAYERS_SUCCESS",

  //////stripe single payout transaction list
  API_GET_STRIPE_TRANSACTION_PAYOUT_LIST_API_LOAD: "API_GET_STRIPE_TRANSACTION_PAYOUT_LIST_API_LOAD",
  API_GET_STRIPE_TRANSACTION_PAYOUT_LIST_API_SUCCESS: "API_GET_STRIPE_TRANSACTION_PAYOUT_LIST_API_SUCCESS",

  ////Add Edit Coach
  API_LIVE_SCORE_UPDATE_COACH: "API_LIVE_SCORE_UPDATE_COACH",
  API_LIVE_SCORE_COACH_FAIL: "API_LIVE_SCORE_COACH_FAIL",
  API_LIVE_SCORE_COACH_ERROR: "API_LIVE_SCORE_COACH_ERROR",

  API_LIVE_SCORE_COACH_LIST_LOAD: "API_LIVE_SCORE_COACH_LIST_LOAD",
  API_LIVE_SCORE_COACH_LIST_SUCCESS: "API_LIVE_SCORE_COACH_LIST_SUCCESS",
  API_GET_DIVISION_LOAD: "API_GET_DIVISION_LOAD",
  API_GET_DIVISION_SUCCESS: "API_GET_DIVISION_SUCCESS",
  API_COMPETITION_FIXTURE_FAIL: "API_COMPETITION_FIXTURE_FAIL",
  API_COMPETITION_FIXTURE_ERROR: "API_COMPETITION_FIXTURE_ERROR",
  API_GET_FIXTURE_LOAD: "API_GET_FIXTURE_LOAD",
  API_GET_FIXTURE_SUCCESS: "API_GET_FIXTURE_SUCCESS",
  clearFixtureData: "clearFixtureData",
  API_UPDATE_COMPETITION_FIXTURE_LOAD: "API_UPDATE_COMPETITION_FIXTURE_LOAD",
  API_UPDATE_COMPETITION_FIXTURE_SUCCESS: "API_UPDATE_COMPETITION_FIXTURE_SUCCESS",

  API_LIVE_SCORE_ADD_EDIT_COACH_LOAD: "API_LIVE_SCORE_ADD_EDIT_COACH_LOAD",
  API_LIVE_SCORE_ADD_EDIT_COACH_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_COACH_SUCCESS",

  API_LIVESCORE_COACH_SEARCH_LOAD: "API_LIVESCORE_COACH_SEARCH_LOAD",
  API_LIVESCORE_COACH_SEARCH_SUCCESS: "API_LIVESCORE_COACH_SEARCH_SUCCESS",

  // Delete Organisation Contact
  API_DELETE_ORG_CONTACT_SUCCESS: "API_DELETE_ORG_CONTACT_SUCCESS",
  API_DELETE_ORG_CONTACT_LOAD: "API_DELETE_ORG_CONTACT_LOAD",

  // Export Organisation Registration Questions 
  API_EXPORT_ORG_REG_QUESTIONS_SUCCESS: "API_EXPORT_ORG_REG_QUESTIONS_SUCCESS",
  API_EXPORT_ORG_REG_QUESTIONS_LOAD: "API_EXPORT_ORG_REG_QUESTIONS_LOAD",


  API_COMPETITION_DIVISION_DELETE_LOAD: "API_COMPETITION_DIVISION_DELETE_LOAD",
  API_COMPETITION_DIVISION_DELETE_SUCCESS: "API_COMPETITION_DIVISION_DELETE_SUCCESS",

  // Change division Team
  API_CHANGE_COMPETITION_DIVISION_TEAM_LOAD: "API_CHANGE_COMPETITION_DIVISION_TEAM_LOAD",
  API_CHANGE_COMPETITION_DIVISION_TEAM_SUCCESS: "API_CHANGE_COMPETITION_DIVISION_TEAM_SUCCESS",

  // Change division Player
  API_CHANGE_COMPETITION_DIVISION_PLAYER_LOAD: "API_CHANGE_COMPETITION_DIVISION_PLAYER_LOAD",
  API_CHANGE_COMPETITION_DIVISION_PLAYER_SUCCESS: "API_CHANGE_COMPETITION_DIVISION_PLAYER_SUCCESS",

  UPDATE_PLAYER_GRADING_DATA: "UPDATE_PLAYER_GRADING_DATA",

  // AffiliateDirectory List
  API_AFFILIATE_DIRECTORY_SUCCESS: "API_AFFILIATE_DIRECTORY_SUCCESS",
  API_AFFILIATE_DIRECTORY_LOAD: "API_AFFILIATE_DIRECTORY_LOAD",

  API_COURT_LIST_LOAD: "API_COURT_LIST_LOAD",
  API_COURT_LIST_SUCCESS: "API_COURT_LIST_SUCCESS",
  // change draws lock
  API_UPDATE_DRAWS_LOCK_LOAD: "API_UPDATE_DRAWS_LOCK_LOAD",
  API_UPDATE_DRAWS_LOCK_SUCCESS: "API_UPDATE_DRAWS_LOCK_SUCCESS",

  // Export AffiliateDirectory
  API_EXPORT_AFFILIATE_DIRECTORY_SUCCESS: "API_EXPORT_AFFILIATE_DIRECTORY_SUCCESS",
  API_EXPORT_AFFILIATE_DIRECTORY_LOAD: "API_EXPORT_AFFILIATE_DIRECTORY_LOAD",

  // Send invite to reference
  API_GET_INVITE_TYPE_LOAD: "API_GET_INVITE_TYPE_LOAD",
  API_GET_INVITE_TYPE_SUCCESS: "API_GET_INVITE_TYPE_SUCCESS",

  API_GET_COMMENT_LIST_LOAD: "API_GET_COMMENT_LIST_LOAD",
  API_GET_COMMENT_LIST_SUCCESS: "API_GET_COMMENT_LIST_SUCCESS",

  //// Umpire Module
  API_UMPIRE_LIST_LOAD: "API_UMPIRE_LIST_LOAD",
  API_UMPIRE_LIST_SUCCESS: "API_UMPIRE_LIST_SUCCESS",

  API_UMPIRE_FAIL: "API_UMPIRE_FAIL",
  API_UMPIRE_ERROR: "API_UMPIRE_ERROR",

  API_UMPIRE_COMPETITION_LIST_LOAD: "API_UMPIRE_COMPETITION_LIST_LOAD",
  API_UMPIRE_COMPETITION_LIST_SUCCESS: "API_UMPIRE_COMPETITION_LIST_SUCCESS",

  API_ADD_UMPIRE_LOAD: "API_ADD_UMPIRE_LOAD",
  API_ADD_UMPIRE_SUCCESS: "API_ADD_UMPIRE_SUCCESS",

  UPDATE_ADD_UMPIRE_DATA: "UPDATE_ADD_UMPIRE_DATA",


  API_GET_UMPIRE_AFFILIATE_LIST_LOAD: "API_GET_UMPIRE_AFFILIATE_LIST_LOAD",
  API_GET_UMPIRE_AFFILIATE_LIST_SUCCESS: "API_GET_UMPIRE_AFFILIATE_LIST_SUCCESS",

  API_UMPIRE_SEARCH_LOAD: "API_UMPIRE_SEARCH_LOAD",
  API_UMPIRE_SEARCH_SUCCESS: "API_UMPIRE_SEARCH_SUCCESS",

  CLEAR_UMPIRE_SEARCH: "CLEAR_UMPIRE_SEARCH",

  SETTING_REGISTRATION_INVITEES_LOAD: "SETTING_REGISTRATION_INVITEES_LOAD",
  SETTING_REGISTRATION_INVITEES_SUCCESS: "SETTING_REGISTRATION_INVITEES_SUCCESS",

  API_LIVE_SCORE_COACH_IMPORT_LOAD: "API_LIVE_SCORE_COACH_IMPORT_LOAD",
  API_LIVE_SCORE_COACH_IMPORT_SUCCESS: "API_LIVE_SCORE_COACH_IMPORT_SUCCESS",
  API_GET_ALL_COMPETITION_LOAD: "API_GET_COMPETITION_LOAD",
  API_GET_ALL_COMPETITION_SUCCESS: "API_GET_ALL_COMPETITION_SUCCESS",

  // RegistrationRestrictionType Meta
  API_REGISTRATION_RESTRICTIONTYPE_LOAD: "API_REGISTRATION_RESTRICTIONTYPE_LOAD",
  API_REGISTRATION_RESTRICTIONTYPE_SUCCESS: "API_REGISTRATION_RESTRICTIONTYPE_SUCCESS",

  API_UMPIRE_ROASTER_LIST_LOAD: "API_UMPIRE_ROASTER_LIST_LOAD",
  API_UMPIRE_ROASTER_LIST_SUCCESS: "API_UMPIRE_ROASTER_LIST_SUCCESS",

  API_GET_UMPIRE_DASHBOARD_VENUE_LIST_LOAD: "API_GET_UMPIRE_DASHBOARD_VENUE_LIST_LOAD",
  API_GET_UMPIRE_DASHBOARD_VENUE_LIST_SUCCESS: "API_GET_UMPIRE_DASHBOARD_VENUE_LIST_SUCCESS",

  API_GET_UMPIRE_DASHBOARD_DIVISION_LIST_LOAD: "API_GET_UMPIRE_DASHBOARD_DIVISION_LIST_LOAD",
  API_GET_UMPIRE_DASHBOARD_DIVISION_LIST_SUCCESS: "API_GET_UMPIRE_DASHBOARD_DIVISION_LIST_SUCCESS",

  API_UMPIRE_ROASTER_ACTION_CLICK_LOAD: "API_UMPIRE_ROASTER_ACTION_CLICK_LOAD",
  API_UMPIRE_ROASTER_ACTION_CLICK_SUCCESS: "API_UMPIRE_ROASTER_ACTION_CLICK_SUCCESS",

  API_GET_UMPIRE_DASHBOARD_LIST_LOAD: "API_GET_UMPIRE_DASHBOARD_LIST_LOAD",
  API_GET_UMPIRE_DASHBOARD_LIST_SUCCESS: "API_GET_UMPIRE_DASHBOARD_LIST_SUCCESS",
  API_SHOP_API_LOAD: "API_SHOP_API_LOAD",
  API_SHOP_API_SUCCESS: "API_SHOP_API_SUCCESS",
  API_SHOP_API_ERROR: "API_SHOP_API_ERROR",
  API_SHOP_API_FAIL: "API_SHOP_API_FAIL",
  API_PAYMENT_TYPE_LIST_LOAD: "API_PAYMENT_TYPE_LIST_LOAD",
  API_PAYMENT_TYPE_LIST_SUCCESS: "API_PAYMENT_TYPE_LIST_SUCCESS",
  API_PAYMENT_TYPE_LIST_FAIL: "API_PAYMENT_TYPE_LIST_FAIL",
  API_PAYMENT_TYPE_LIST_ERROR: "API_PAYMENT_TYPE_LIST_ERROR",

  //Disability Reference List
  API_DISABILITY_REFERENCE_LOAD: 'API_DISABILITY_REFERENCE_LOAD',
  API_DISABILITY_REFERENCE_SUCCESS: "API_DISABILITY_REFERENCE_SUCCESS",
  API_UPDATE_QUICKCOMPETITION_TIMESLOT: "API_UPDATE_QUICKCOMPETITION_TIMESLOT",
  API_GET_COMMON_INIT_LOAD: "API_GET_COMMON_INIT_LOAD",
  API_GET_COMMON_INIT_SUCCESS: "API_GET_COMMON_INIT_SUCCESS",
  API_UPDATE_QUICKCOMPETITION_Division: "API_UPDATE_QUICKCOMPETITION_Division",

  API_LIVE_SCORE_UPDATE_INCIDENT_DATA: "API_LIVE_SCORE_UPDATE_INCIDENT_DATA",
  //Action Box
  API_GET_ACTION_BOX_LOAD: "API_GET_ACTION_BOX_LOAD",
  API_GET_ACTION_BOX_SUCCESS: "API_GET_ACTION_BOX_SUCCESS",

  //Update Action Box
  API_UPDATE_ACTION_BOX_LOAD: "API_UPDATE_ACTION_BOX_LOAD",
  API_UPDATE_ACTION_BOX_SUCCESS: "API_UPDATE_ACTION_BOX_SUCCESS",

  API_UMPIRE_IMPORT_LOAD: "API_UMPIRE_IMPORT_LOAD",
  API_UMPIRE_IMPORT_SUCCESS: "API_UMPIRE_IMPORT_SUCCESS",

  /////assign umpire in umpire module
  API_ASSIGN_UMPIRE_FAIL: "API_ASSIGN_UMPIRE_FAIL",
  API_ASSIGN_UMPIRE_ERROR: "API_ASSIGN_UMPIRE_ERROR",

  ///get assign umpire list
  API_GET_ASSIGN_UMPIRE_LIST_LOAD: "API_GET_ASSIGN_UMPIRE_LIST_LOAD",
  API_GET_ASSIGN_UMPIRE_LIST_SUCCESS: "API_GET_ASSIGN_UMPIRE_LIST_SUCCESS",

  /////assign umpire to a match
  API_ASSIGN_UMPIRE_FROM_LIST_LOAD: "API_ASSIGN_UMPIRE_FROM_LIST_LOAD",
  API_ASSIGN_UMPIRE_FROM_LIST_SUCCESS: "API_ASSIGN_UMPIRE_FROM_LIST_SUCCESS",

  ////unassign umpire from the match
  API_UNASSIGN_UMPIRE_FROM_LIST_LOAD: "API_UNASSIGN_UMPIRE_FROM_LIST_LOAD",
  API_UNASSIGN_UMPIRE_FROM_LIST_SUCCESS: "API_UNASSIGN_UMPIRE_FROM_LIST_SUCCESS",


  CHANGE_PLAYER_LINEUP_LOAD: "CHANGE_PLAYER_LINEUP_LOAD",
  API_CHNAGE_LINEUP_STATUS_SUCCESS: "API_CHNAGE_LINEUP_STATUS_SUCCESS",

  API_USER_EXPORT_FILES_LOAD: "API_USER_EXPORT_FILES_LOAD",
  API_USER_EXPORT_FILES_SUCCESS: "API_USER_EXPORT_FILES_SUCCESS",

  ////// shop product
  API_SHOP_PRODUCT_FAIL: "API_SHOP_PRODUCT_FAIL",
  API_SHOP_PRODUCT_ERROR: "API_SHOP_PRODUCT_ERROR",

  //////product listing get API 
  API_GET_SHOP_PRODUCT_LISTING_LOAD: "API_GET_SHOP_PRODUCT_LISTING_LOAD",
  API_GET_SHOP_PRODUCT_LISTING_SUCCESS: "API_GET_SHOP_PRODUCT_LISTING_SUCCESS",

  ////Add product 
  API_ADD_SHOP_PRODUCT_LOAD: "API_ADD_SHOP_PRODUCT_LOAD",
  API_ADD_SHOP_PRODUCT_SUCCESS: "API_ADD_SHOP_PRODUCT_SUCCESS",

  //////on change add/edit product details
  SHOP_PRODUCT_DETAILS_ONCHANGE: "SHOP_PRODUCT_DETAILS_ONCHANGE",


  API_LIVE_SCORE_UMPIRES_IMPORT_LOAD: "API_LIVE_SCORE_UMPIRES_IMPORT_LOAD",
  API_LIVE_SCORE_UMPIRES_IMPORT_SUCCESS: "API_LIVE_SCORE_UMPIRES_IMPORT_SUCCESS",

  API_UPDATE_QUICKCOMPETITION_COMPETITION: "API_UPDATE_QUICKCOMPETITION_COMPETITION",
  CHANGE_BULK_MATCH_SCORE: "CHANGE_BULK_MATCH_SCORE",
  BULK_SCORE_UPDATE_LOAD: "BULK_SCORE_UPDATE_LOAD",
  BULK_SCORE_UPDATE_SUCCESS: "BULK_SCORE_UPDATE_SUCCESS",
  BULK_SCORE_UPDATE_CANCEL: "BULK_SCORE_UPDATE_CANCEL",
  API_UMPIRE_SETTINGS_DATA_UPDATE: "API_UMPIRE_SETTINGS_DATA_UPDATE",

  ////////////registration main dashboard listing owned and participate registration
  API_GET_REGISTRATION_MAIN_DASHBOARD_LISTING_LOAD: "API_GET_REGISTRATION_MAIN_DASHBOARD_LISTING_LOAD",
  API_GET_REGISTRATION_MAIN_DASHBOARD_LISTING_SUCCESS: "API_GET_REGISTRATION_MAIN_DASHBOARD_LISTING_SUCCESS",

  API_LIVE_SCORE_ADD_EDIT_INCIDENT_LOAD: "API_LIVE_SCORE_ADD_EDIT_INCIDENT_LOAD",
  API_LIVE_SCORE_ADD_EDIT_INCIDENT_SUCCESS: "API_LIVE_SCORE_ADD_EDIT_INCIDENT_SUCCESS",

  API_LIVE_SCORE_INCIDENT_TYPE_LOAD: "API_LIVE_SCORE_INCIDENT_TYPE_LOAD",
  API_LIVE_SCORE_INCIDENT_TYPE_SUCCESS: "API_LIVE_SCORE_INCIDENT_TYPE_SUCCESS",

  UPDATE_LADDER_ADJUSTMENT: "UPDATE_LADDER_ADJUSTMENT",
  //////get reference type in the add product screen
  API_GET_TYPES_LIST_IN_ADD_PROUCT_LOAD: "API_GET_TYPES_LIST_IN_ADD_PROUCT_LOAD",
  API_GET_TYPES_LIST_IN_ADD_PROUCT_SUCCESS: "API_GET_TYPES_LIST_IN_ADD_PROUCT_SUCCESS",

  //////add type in the typelist array in reducer
  SHOP_ADD_TYPE_IN_TYPELIST_REDUCER: "SHOP_ADD_TYPE_IN_TYPELIST_REDUCER",
  API_YEAR_AND_QUICK_COMPETITION_LOAD: "API_YEAR_AND_QUICK_COMPETITION_LOAD",
  API_YEAR_AND_QUICK_COMPETITION_SUCCESS: "API_YEAR_AND_QUICK_COMPETITION_SUCCESS",
  API_CREATE_QUICK_COMPETITION_LOAD: "API_CREATE_QUICK_COMPETITION_LOAD",
  API_CREATE_QUICK_COMPETITION_SUCCESS: "API_CREATE_QUICK_COMPETITION_SUCCESS",

  ////////// quick competition
  API_QUICK_COMPETITION_FAIL: "API_QUICK_COMPETITION_FAIL",
  API_QUICK_COMPETITION_ERROR: "API_QUICK_COMPETITION_ERROR",

  ////post/save quick competition division
  API_SAVE_QUICK_COMPETITION_DIVISION_LOAD: "API_SAVE_QUICK_COMPETITION_DIVISION_LOAD",
  API_SAVE_QUICK_COMPETITION_DIVISION_SUCCESS: "API_SAVE_QUICK_COMPETITION_DIVISION_SUCCESS",

  //get quick competition data
  API_GET_QUICK_COMPETITION_LOAD: "API_GET_QUICK_COMPETITION_LOAD",
  API_GET_QUICK_COMPETITION_SUCCESS: "API_GET_QUICK_COMPETITION_SUCCESS",

  API_QUICK_COMPETITION_TIMESLOT_POST_SUCCESS: "API_QUICK_COMPETITION_TIMESLOT_POST_SUCCESS",
  API_QUICK_COMPETITION_TIMESLOT_POST_LOAD: "API_QUICK_COMPETITION_TIMESLOT_POST_LOAD",

  ////update quick competition
  API_UPDATE_QUICK_COMPETITION_LOAD: "API_UPDATE_QUICK_COMPETITION_LOAD",
  API_UPDATE_QUICK_COMPETITION_SUCCESS: "API_UPDATE_QUICK_COMPETITION_SUCCESS",

  ///////get state reference data
  API_GET_STATE_REFERENCE_DATA_LOAD: "API_GET_STATE_REFERENCE_DATA_LOAD",
  API_GET_STATE_REFERENCE_DATA_SUCCESS: "API_GET_STATE_REFERENCE_DATA_SUCCESS",

  //////////////delete product from the product listing API
  API_DELETE_SHOP_PRODUCT_LOAD: "API_DELETE_SHOP_PRODUCT_LOAD",
  API_DELETE_SHOP_PRODUCT_SUCCESS: "API_DELETE_SHOP_PRODUCT_SUCCESS",

  /// Payment Status
  API_REGISTRATION_PAYMENT_STATUS_LOAD: 'API_REGISTRATION_PAYMENT_STATUS_LOAD',
  API_REGISTRATION_PAYMENT_STATUS_SUCCESS: "API_REGISTRATION_PAYMENT_STATUS_SUCCESS",

  //update draws in quick competition
  API_UPDATE_QUICKCOMPETITION_DRAWS: "API_UPDATE_QUICKCOMPETITION_DRAWS",
  //update quick competition invitations

  API_UPDATE_QUICKCOMPETITION_INVITATIONS: "API_UPDATE_QUICKCOMPETITION_INVITATIONS",
  QUICKCOMP_IMPORT_DATA_CLEAN: "QUICKCOMP_IMPORT_DATA_CLEAN",
  QUICKCOMP_IMPORT_DATA_LOAD: "QUICKCOMP_IMPORT_DATA_LOAD",
  QUICKCOMP_IMPORT_DATA_SUCCESS: "QUICKCOMP_IMPORT_DATA_SUCCESS",

  /// Match print template type
  API_MATCH_PRINT_TEMPLATE_LOAD: "API_MATCH_PRINT_TEMPLATE_LOAD",
  API_MATCH_PRINT_TEMPLATE_SUCCESS: "API_MATCH_PRINT_TEMPLATE_SUCCESS",
  ////clear shop product reducer data
  SHOP_PRODUCT_CLEARING_REDUCER_DATA: "SHOP_PRODUCT_CLEARING_REDUCER_DATA",

  ////////delete product variant API
  API_DELETE_SHOP_PRODUCT_VARIANT_LOAD: "API_DELETE_SHOP_PRODUCT_VARIANT_LOAD",
  API_DELETE_SHOP_PRODUCT_VARIANT_SUCCESS: "API_DELETE_SHOP_PRODUCT_VARIANT_SUCCESS",

  //////add type in the typelist array in from the API
  API_SHOP_ADD_TYPE_IN_TYPELIST_LOAD: "API_SHOP_ADD_TYPE_IN_TYPELIST_LOAD",
  API_SHOP_ADD_TYPE_IN_TYPELIST_SUCCESS: "API_SHOP_ADD_TYPE_IN_TYPELIST_SUCCESS",

  //////product details on id API
  API_SHOP_GET_PRODUCT_DETAILS_BY_ID_LOAD: "API_SHOP_GET_PRODUCT_DETAILS_BY_ID_LOAD",
  API_SHOP_GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "API_SHOP_GET_PRODUCT_DETAILS_BY_ID_SUCCESS",

  // Match sheet print
  API_MATCH_SHEET_PRINT_LOAD: "API_MATCH_SHEET_PRINT_LOAD",
  API_MATCH_SHEET_PRINT_SUCCESS: "API_MATCH_SHEET_PRINT_SUCCESS",

  // Match sheet download
  API_MATCH_SHEET_DOWNLOADS_LOAD: "API_MATCH_SHEET_DOWNLOADS_LOAD",
  API_MATCH_SHEET_DOWNLOADS_SUCCESS: "API_MATCH_SHEET_DOWNLOADS_SUCCESS",

  /// Match sheet fail and error
  API_LIVE_SCORE_MATCH_SHEET_FAIL: "API_LIVE_SCORE_MATCH_SHEET_FAIL",
  API_LIVE_SCORE_MATCH_SHEET_ERROR: "API_LIVE_SCORE_MATCH_SHEET_ERROR",

  API_LADDER_ADJUSTMENT_POST_LOAD: "API_LADDER_ADJUSTMENT_POST_LOAD",
  API_LADDER_ADJUSTMENT_POST_SUCCESS: "API_LADDER_ADJUSTMENT_POST_SUCCESS",

  API_LADDER_ADJUSTMENT_GET_LOAD: "API_LADDER_ADJUSTMENT_GET_LOAD",
  API_LADDER_ADJUSTMENT_GET_SUCCESS: "API_LADDER_ADJUSTMENT_GET_SUCCESS",

  // User Module Activity Manager
  API_USER_MODULE_HISTORY_SUCCESS: "API_USER_MODULE_HISTORY_SUCCESS",
  API_USER_MODULE_HISTORY_LOAD: "API_USER_MODULE_HISTORY_LOAD",

  API_UPDATE_REG_REVIEW: "API_UPDATE_REG_REVIEW",

  UPDATE_INSTALMENT_DATE: "UPDATE_INSTALMENT_DATE",

  API_LIVE_SCORE_MANAGER_IMPORT_LOAD: "API_LIVE_SCORE_MANAGER_IMPORT_LOAD",
  API_LIVE_SCORE_MANAGER_IMPORT_SUCCESS: "API_LIVE_SCORE_MANAGER_IMPORT_SUCCESS",

  ////// shop settings
  API_SHOP_SETTINGS_FAIL: "API_SHOP_SETTINGS_FAIL",
  API_SHOP_SETTINGS_ERROR: "API_SHOP_SETTINGS_ERROR",

  ///////shop setting get API
  API_GET_SHOP_SETTING_LOAD: "API_GET_SHOP_SETTING_LOAD",
  API_GET_SHOP_SETTING_SUCCESS: "API_GET_SHOP_SETTING_SUCCESS",

  ///////shop setting create address API
  API_CREATE_SHOP_SETTING_ADDRESS_LOAD: "API_CREATE_SHOP_SETTING_ADDRESS_LOAD",
  API_CREATE_SHOP_SETTING_ADDRESS_SUCCESS: "API_CREATE_SHOP_SETTING_ADDRESS_SUCCESS",
  //////onchange settings screen daata
  SHOP_SETTINGS_DETAILS_ONCHANGE: "SHOP_SETTINGS_DETAILS_ONCHANGE",

  //update organisation charity round up
  UPDATE_ORGANISATION_CHARITY_ROUND_UP: "UPDATE_ORGANISATION_CHARITY_ROUND_UP",

  //api update organisation charity round up
  API_UPDATE_CHARITY_ROUND_UP_LOAD: "API_UPDATE_CHARITY_ROUND_UP_LOAD",
  API_UPDATE_CHARITY_ROUND_UP_SUCCESS: "API_UPDATE_CHARITY_ROUND_UP_SUCCESS",

  API_UPDATE_TERMS_AND_CONDITION_LOAD: "API_UPDATE_TERMS_AND_CONDITION_LOAD",
  API_UPDATE_TERMS_AND_CONDITION_SUCCESS: "API_UPDATE_TERMS_AND_CONDITION_SUCCESS",
  API_COMPETITION_STATUS_UPDATE_LOAD: "API_COMPETITION_STATUS_UPDATE_LOAD",
  API_COMPETITION_STATUS_UPDATE_SUCCESS: "API_COMPETITION_STATUS_UPDATE_SUCCESS",


  // Active Rounds
  API_GET_DRAWS_ACTIVE_ROUNDS_LOAD: "API_GET_DRAWS_ACTIVE_ROUNDS_LOAD",
  API_GET_DRAWS_ACTIVE_ROUNDS_SUCCESS: "API_GET_DRAWS_ACTIVE_ROUNDS_SUCCESS",

  API_UMPIRE_ROUND_LIST_LOAD: "API_UMPIRE_ROUND_LIST_LOAD",
  API_UMPIRE_ROUND_LIST_SUCCESS: "API_UMPIRE_ROUND_LIST_SUCCESS",

  API_INNER_HORIZONTAL_COMPETITION_LIST_LOAD: "API_INNER_HORIZONTAL_COMPETITION_LIST_LOAD",
  API_INNER_HORIZONTAL_COMPETITION_LIST_SUCCESS: "API_INNER_HORIZONTAL_COMPETITION_LIST_SUCCESS",
  API_INNER_HORIZONTAL_FAIL: "API_INNER_HORIZONTAL_FAIL",
  API_INNER_HORIZONTAL_ERROR: "API_INNER_HORIZONTAL_ERROR",

  API_LIVE_SCORE_POSITION_TRACKING_LOAD: "API_LIVE_SCORE_POSITION_TRACKING_LOAD",
  API_LIVE_SCORE_POSITION_TRACKING_SUCCESS: "API_LIVE_SCORE_POSITION_TRACKING_SUCCESS",
  API_LIVE_SCORE_POSITION_TRACKING_FAIL: "API_LIVE_SCORE_POSITION_TRACKING_FAIL",
  API_LIVE_SCORE_POSITION_TRACKING_ERROR: "API_LIVE_SCORE_POSITION_TRACKING_ERROR",


  // Check venue address duplication
  API_VENUE_ADDRESS_CHECK_DUPLICATION_LOAD: "API_VENUE_ADDRESS_CHECK_DUPLICATION_LOAD",
  API_VENUE_ADDRESS_CHECK_DUPLICATION_SUCCESS: "API_VENUE_ADDRESS_CHECK_DUPLICATION_SUCCESS",

  API_QUICK_COMPETITION_ADDVENUE_LOAD: "API_QUICK_COMPETITION_ADDVENUE_LOAD",
  API_QUICK_COMPETITION_ADDVENUE_SUCCESS: "API_QUICK_COMPETITION_ADDVENUE_SUCCESS",

  API_LIVE_SCORE_MAIN_DIVISION_LIST_LOAD:"API_LIVE_SCORE_MAIN_DIVISION_LIST_LOAD",
  API_LIVE_SCORE_MAIN_DIVISION_LIST_SUCCESS:"API_LIVE_SCORE_MAIN_DIVISION_LIST_SUCCESS",

  // Shop order summary
  API_SHOP_ORDER_SUMMARY_FAIL: "API_SHOP_ORDER_SUMMARY_FAIL",
  API_SHOP_ORDER_SUMMARY_ERROR: "API_SHOP_ORDER_SUMMARY_ERROR",

  // Shop order summary listing get API
  API_GET_SHOP_ORDER_SUMMARY_LISTING_LOAD: "API_GET_SHOP_ORDER_SUMMARY_LISTING_LOAD",
  API_GET_SHOP_ORDER_SUMMARY_LISTING_SUCCESS: "API_GET_SHOP_ORDER_SUMMARY_LISTING_SUCCESS",
  // Export payment
  API_PAYMENT_DASHBOARD_EXPORT_LOAD: "API_PAYMENT_DASHBOARD_EXPORT_LOAD",
  API_PAYMENT_DASHBOARD_EXPORT_SUCCESS: "API_PAYMENT_DASHBOARD_EXPORT_SUCCESS",

  UPDATE_UMPIRE_DASHBOARD: "UPDATE_UMPIRE_DASHBOARD",

  // Impersonation
  API_IMPERSONATION_LOAD: "API_IMPERSONATION_LOAD",
  API_IMPERSONATION_SUCCESS: "API_IMPERSONATION_SUCCESS",

  // Help and Support
  API_SUPPORT_FAIL: "API_SUPPORT_FAIL",
  API_SUPPORT_ERROR: "API_SUPPORT_ERROR",
  API_SUPPORT_CONTENT_LOAD: "API_SUPPORT_CONTENT_LOAD",
  API_SUPPORT_CONTENT_SUCCESS: "API_SUPPORT_CONTENT_SUCCESS",

   ////export order summary  API 
   API_GET_EXPORT_ORDER_SUMMARY_LOAD: "API_GET_EXPORT_ORDER_SUMMARY_LOAD",
   API_GET_EXPORT_ORDER_SUMMARY_SUCCESS: "API_GET_EXPORT_ORDER_SUMMARY_SUCCESS",
};

export default ApiConstants;
