/* eslint-disable max-len */
const AppConstants = {
    deprecated: "---",
    login: "Login",
    password: "Password",
    addAffiliate: "Add Affiliate",
    affiliatedTo: "Affiliated To",
    all: "All",
    organisationType: "Organisation Type",
    status: "Status",
    administrators: "Administrators",
    maintain: "Maintain",
    RegTo: "Reg. To",
    RegFrom: "Reg. From",
    venueAndCourts: "Venues & Courts",
    graphicalDashboard: "Graphical Display",
    textualDashboard: "Textual Display",
    userProfile: "User Profile",
    myProfile: "My Profile",
    affiliates: "Affiliates",
    affiliateApproveReject: "Affiliate - Approve / Reject",
    current: "Current",
    pendingForApproval: "Pending For Approval",
    club: "Club",
    name: "Name",
    address: "Address",
    phoneNumber: "Phone Number",
    contacts: "Contacts",
    ourOrganisation: "Our Organisation",
    dashboard: "Dashboard",
    contact1: "Contact 1",
    contact2: "Contact 2",
    contact: "Contact ",
    title: "Title",
    email: "Email",
    mobile: "Mobile",
    permissionLevel: "Permission Level",
    remove: "Remove",
    addContact: "Add Contact",
    cancel: "Cancel",
    save: "Save",
    association: "Association",
    addAffiliates: "Add Affiliates",
    updateAffiliates: "Update",
    add: "Add",
    postCode: "Postcode",
    enterPostCode: "Enter postcode",
    gender: "Gender",
    male: "Male",
    female: "Female",
    unspecified: "Unspecified",
    dob: "Date of Birth",
    competitionCategory: "Competition Category",
    competitionInvitees: "Competition Invitees",
    participant_id: "Participant ID",
    participant_fullName: "Participant Full Name",
    participant_firstName: "Participant First Name",
    participant_middleName: "Alternative or Middle Name",
    participant_lastName: "Participant Last Name",
    contactMobile: "Contact Mobile",
    contactEmail: "Contact Email",
    reenterEmail: "Re-enter Email",
    uploadPhoto: "Upload Photo",
    or: "or",
    takePhoto: "Take Photo",
    emergencyContacts: "Emergency Contacts",
    emergencyContactName: "Emergency Contact Name",
    emergencyContactMobile: "Emergency Contact Mobile",
    parents_guardians: "Parent/ Guardian Details",
    firstName: "First Name",
    lastName: "Last Name",
    sameAddress: "Use same Address as Participant",
    additionalInfoReqd: "Additional Information required",
    additionalPersonalInfoReqd: "Additional Personal Information required",
    haveYouEverPlayed: "Have you ever played Netball before:",
    confirmTransferTo: "Please confirm who you would like to transfer to",
    yes: "Yes",
    no: "No",
    loadMore: "Load more",
    grade: "Grade",
    year: "Year",
    clubOther: "Club/other",
    lastCaptainName: "Name your last Captain",
    playWithFriend: "Play with a friend",
    referFriend: "Refer a friend",
    friend: "Friend",
    referfriend_friendLiketoPlay: "Refer a friend : Do you have a friend you think would like to play?",
    friendLikeToPlay: "Do you have a friend you think would like to play?",
    existingMedConditions: "Existing Medical Conditions",
    regularMedicalConditions: "Regular Medications",
    hearAboutTheCompetition: "How did you hear about this Netball Competition?",
    who_fav_bird: "Who is your favourite Firebird?",
    consentForPhotos: "Do you give consent for photos to be taken and used for promotional purposes",
    addOtherReg: "Add Another Registration",
    favouriteTeam: "Favourite Netball Team",
    OtherInfoReqd: "Other information required",
    yourSupportImportant: "Your Support is important for the continued success of our Club. Can you help?",
    childrenNumber: "Children Check Number",
    checkExpiryDate: "Check Expiry Date",
    childrenCheckNumberInfo:
        "Working with Children Check Number (You are required to have a working with Children Number. If you don’t have one you will need to apply.)",
    childCountry: "Which country were you born",
    childNationality: "What nationality are you",
    childLangSpoken: "Languages spoken at home",
    haveDisability: "Do you have a disability?",
    addAnotherQuestion: "Add Another question",
    uniformAndMerchandise: "Uniforms and Merchandise",
    vouchers: "Vouchers",
    addVoucher: "Add voucher",

    agreeTerm: "I have read and agree to the  ",
    termsAndConditions: "Terms and Conditions",
    reviewOrder: "Review Order",
    checkOptions: "Checkout Options",
    voucherLink: "Voucher link",
    nearestCompetition: "Nearest Competition",
    photo: "Photo",
    addParent_guardian: "Add Parent/Guardian",
    addFriend: "Add Friend",

    usernamePasswordIncorrect: "Login Unsuccessful. Incorrect Username or Password",
    home: "Home",
    user: "User",
    registration: "Registration",
    competitions: "Competitions",
    liveScores: "Live Scores",
    events: "Events",
    shop: "Shop",
    umpires: "Umpires",
    incidents: "Incidents",
    finance: "Finance",
    totalRegistrations: "Total Registrations",
    totalUsers: "Total Users",
    edit: "Edit",
    familyDiscount: "Family Discount",
    appRegoForm: "App Rego Form",
    competition: "Competition",
    division: "Division",
    addTimeSlot: "Add another time slot",
    saveDraft: "Save Draft",
    next: "Next",
    participateInComp: "Participating-In Competitions",
    ownedCompetitions: "Owned Competitions",
    addCompetition: "Add Competition",
    replicateCompetition: "Replicate Competition",
    draws: "Draws",
    venue: "Venue",
    round: "Round",
    saveAsDraft: "Save as Draft",
    publish: "Publish",
    registrationForm: "Registration Form",
    quickCompetition: "Quick Competition",
    quickCompetition1: "Quick Competition (1/3)",
    quickCompetition2: "Teams & Players (2/3)",
    quickCompetitionFormat: "Competition Format (3/3)",
    proposedTeamGrading: "Proposed Team Grading",
    proposedGrade: "Proposed Grade",
    finalisedGrade: "Finalised Grade",
    comments: "Comments",

    ladder: "Ladder",
    competitionFormat: "Competition Format",
    membershipProduct: "Membership Product",
    membershipProductName: "Membership Product Name",
    validity: "Validity",
    membershipTypes: "Membership Types",
    membershipType: "Membership Type",
    playerHeading: "Player",
    witnesses: "Witnesses",
    offences: "Offences",
    clarifyingQuestions: "Clarifying Questions",
    foul: "Foul",
    foulPlayerName: "Foul Player Name",
    foulPlayerRole: "Foul Player Role",
    personal: "Personal",
    technical: "Technical",
    unsportsmanlike: "Unsportsmanlike",
    disqualifying: "Disqualifying",
    enterCountFouls: "Enter count of fouls",
    suspendedFrom: "Suspended From",
    suspendedTo: "Suspended Till",
    mandatePlayerAge: "Mandate Player Age Restrictions",
    team: "Team",
    umpire: "Umpire",
    coach: "Coach",
    addMembershipType: "Add Membership Type",
    membershipFees: "Membership Fees",
    applyMembershipFee: "Apply Seasonal Membership Fees to",
    casualFee: "Single Game Fee (inc GST)",
    singleGameFee: "Individual User Single Game Fee",
    casualFeeExclGst: "Single Game Fee (excl. GST)",
    gst: "GST",
    seasonalFee: "Individual User Seasonal Fee",
    type: "Type",
    fees: "Fees",
    feesPaid: "Fees Paid",
    feesOwing: "Fees Owing",
    discount: "Discount",
    discounts: "Discounts",
    generalDiscount: "General Discount",
    fixedAmount: "Fixed $ amount",
    percentageOff: "Percentage off",
    amount: "Amount",
    description: "Description",
    availableFrom: "Available From",
    availableTo: "Available To",
    discountCode: "Discount Code",
    code: "Code",
    earlyDiscount: "Early Discount",
    addChild: "Add Child",
    child1: "Child 1 %",
    child2: "Child 2 %",
    delete: "Delete",
    year2019: "2019",
    timeSlot: "Time Slots",
    timeBetweenGames: "Time between games",
    timeBetweenMatches: "Time between matches",
    mins: "mins",
    save_publish: "Save & Publish",
    back: "Back",
    finals: "Finals",
    useDefault: " Use Default",
    finalFixtures: "Finals Fixture Template",
    matchType: "Match Type",
    quarters: "Quarters",
    duration: "Duration",
    matchDuration: "Match Duration",
    mainBreak: "Main Break",
    quarterBreak: "Quarter Break",
    qtrBreak: "Qtr Break",
    betweenGames: "Between Games",
    assignManually: "Assign Manually",
    regenerateDraw: "Regenerate",
    saveDraw: "Save Draws",

    /// *****Competition Finals */
    extraTimeIfDraw1: "Extra time if a Draw - 1st Time",
    applyAllRounds: "Apply to all Rounds",
    applyAllSemiAndGrand: "Apply to Semi and Grand Final",
    applyGrandOnly: "Apply to Grand Final Only",
    extraTimeDuration: "Extra Time Duration",
    extraTimeMainBreak: "Extra Time Main Break",
    extraTimeBreak: "Extra Time Break",
    beforeExtraTime: "Before Extra Time",
    extraTimeIfDraw2: "Extra time if a Draw - 2nd Time",
    winByOneGoal: "Win by one Goal",
    winByTwoGoals: "Win by two Goals",
    addAnotherFinalFormat: "Add Another Finals Format",
    setAsDefault: "Set as Default",
    applyFinalFormat: "Apply Final Format",
    //* ****************Competition Fixtures */
    fixtures: "Fixtures",
    add_TimeSlot: "Add Timeslot",
    addCourt: "Add Court",
    RegistrationRestrictionType: "RegistrationRestrictionType",
    CompetitionRegistration: "Competition Registration",

    //* ****************Competition Format */
    newCompetition_name: "Competition Name you are Transferring to?",
    use_default_competitionFormat: "Use default Competition Format Settings",
    standard_round_robin: "Standard Round Robin",
    double_round_robin: "Double Round Robin",
    halves: "Halves",
    fixture_template: "Fixture Template",
    frequency: "Frequency",
    timeBetweenRounds: "Time between Rounds",
    days: "days",
    hours: "hours",
    applyMatchFormat: "Apply Match Format to",
    setUpFinalTemplate_optional: "Set Up Finals Template (Optional)",
    addNewCompetitionFormat: "Add New Competition Format",
    createDraftDraw: "Create Draft Draw",

    /** *****competition Ladder */
    addNewLadderScheme: "Add New Ladder Format",
    ladderAdjustment: "Ladder Adjustment",
    addNewAdjustment: "Add new Adjustment",
    recalculateLadder: "Recalculate Ladder",
    finalise: "Finalise",
    ladderFormatScheme: "Ladder Point Scheme Name",

    /** *competition matchSheet */
    matchSheets: "Match Sheets",
    teams: "Teams",
    gameTimeTracking: "Game Time Tracking",
    periods: "Periods",
    minutes: "Minutes",
    totalGames: "Games",
    positionTracking: "Position Tracking",
    shooting: "Shooting ",
    preview: "Preview",
    previews: "Previews",
    print: "Print",
    printAll: "Print All",

    /** ** competition Open Reg form */
    competitionDetails: "Competition Details",
    competitionLogo: "Competition Logo",
    addShortNotes_registering: "Write a brief description of the Competition..",
    addVenue: " Add Venue",
    typeOfCompetition: "Type of Competition",
    numberOfRounds: "Number of Rounds",
    enhancedRoundRobinType: "Enhanced Round Robin Type",
    registrationClose: "Registrations Close",
    registrationType: "Registration Type",
    nonPlayingDates: "Non-Playing Dates",
    addAnotherNonPlayingDate: "Add Another Non Playing Date",
    addAnotherDivision: "Add Another Division",
    ageRestrictions: "Age Restrictions",
    mandateAgeRestrictions: "Mandate Age Restrictions",
    netSetGo: "NetSetGo",
    dobFrom: "DOB From",
    dobTo: "DOB To",
    playerInEachTeam: "Players in each team",
    minNumber: "Minimum Number",
    maxNumber: "Maximum Number",
    teams_in_each_grade_pool: "Teams in each grade/pool",
    registrationInvitees: "Registration Invitees",
    anyOrganisation: "Any organisation",
    direct: "Direct",
    notApplicable: " Not Applicable",
    percentageOff_FixedAmount: "Percentage off or Fixed Amount",
    governmentVouchers: "Government Vouchers",
    charityRoundUp: "Charity round up",
    /** *****Competition Part Player grade calculate */
    minPlayersTeam: "Min. players/Team",
    numberOfTeams: "# Teams",
    extraPlayers: "Extra Players",

    playerGradingToggle: "Player Grading Toggle",
    playerGrading: "Player Grading",
    open: "Open",
    gradeAndNameTeams: "Grade and Name Teams",
    teamToggle: "Team Toggle",
    submit: "Submit",
    final: "Final",
    addDivisions: "Add Divisions",
    addTeams: "Add Teams",
    winter_2019: "Winter 2019",
    how_Add_teams_players: "How will you add teams and players?",
    addManually: "Add Manually",
    addCompetitionDetails: "Add Competition Details",
    SetUP_Template_Optional: "Set Up Finals Template (Optional) >",
    re_grading: "Re-grading",
    step1: "Step-1",
    step2: "Step-2",
    gradeToggle: "Grade Toggle",
    finalisedDraw: "Finalised Draw",
    confirm: "Confirm",
    replicateWhichCompetition: "Replicate which competition",
    year2018: "2018",
    winter2018: "2018 Winter",
    newCompetitionName: "New Competition Name",
    competitionType: "Competition Type",
    startDate: "Start Date",
    registrationFees: "Registration Fees",
    divisions: "Divisions",
    grades: "Grades",
    divisionAge: "Division/Age",
    divisionGrade: "Division Grade",
    div: "Div",
    competitionFormatGameTimes: "Competition Format & Game Times",
    review: "Review",
    Step_3: "Step 3",
    contactNumber: "Contact Number",
    addAnotherCourt: "Add another court",
    addAnotherVenue: "Add another venue",
    venueAndTimes: "Venue And Times",
    club_TeamName: "Club/Team Name",
    game_Days: "Game Day(s)",
    dayOfTheWeek: "Day of the week",
    startTime: "Start Time",
    endTime: "End Time",
    addAnotherDay: "Add Day",
    courts: "Courts",
    applyTo: "Apply to",
    addAnother: "Add another",
    courtDetails: "Court Details",
    inbox: "Actionbox",
    viewAll: "View All",
    eventsToday: "Events Today",
    competitionsOverview: "Competitions Overview",
    addNew: "Add New",
    participatingInCompetitions: "Participating In Competitions",
    playerProfile: "Player Profile",
    dateOfBirth: "Date of Birth",
    activity: "Activity",
    statistics: "Statistics",
    personalDetails: "Personal Details",
    medical: "Medical",
    addAnotherDetail: "Add another detail",
    register: "Register",
    username: "Username",
    products: "Products",
    productDetails: "Product Details",
    playingMember: "Playing Member",
    nonPlayingMember: "Non Playing Member",
    Umpire_Referee: "Umpire/Referee",
    category: "Category",
    applicableTo: "Applicable to",
    level1_Affiliate_Associations: "1st level Affiliate - Associations",
    rename: "Rename",
    Level2_Affiliate_Clubs: "2nd Level Affiliate - Clubs",
    paymentFrequency: "Payment Frequency",
    oncePerYear: "Once Per Year",
    eachMatch: "Each Match",
    eachCompetition: "Each Competition",
    enterShortDescription: "Enter a short description of the product...",
    dob__From: "DOB - From",
    dob__To: "DOB - To",
    addGst10: "Add GST (10%)",
    clubFees: "Club Fees",
    associationFees: "Association Fees",
    stateFees: "State Fees",
    allFees: "All Fees",
    addAnotherVoucher: "Add Another Voucher",

    /// registration membership fees list
    addMembershipProduct: "Add Membership Product",

    // comp court and times assign
    applyToAllVenues: "Apply to all venues",
    applySettingsToIndividualVenue: "Apply settings to individual venue",
    timeslotsAllocatedBasedOnGame: "Timeslots allocated based on game times",
    manuallyAddTimeslots: "Manually Add Timeslots",
    evenRotationTimeslots: "Even rotation of teams to timeslots",
    divisionAndGradeTimeslots: "Allocate Divisions and Grades to same timeslot",
    /* //registration// */
    addAFee: "Add a Fee",
    competitionFees: "Competition Fees",
    please_Sel_mem_pro: "Please select membership product",
    net_set_go: "Net Set Go",
    addDivision: "Add Division",
    allDivisions: "All Divisions",
    perDivision: "Per Division",
    paymentOptions: "Payment Options",
    organisationName: "Organisation Name",
    newOrganisationName: "Organisation Name you are Transferring to?",
    organisationLogo: "Organisation Logo",
    registrationOpen: "Registration Open",
    lockRegistrationsImmediately: "Lock Registrations Immediately",
    endUserRegistrationUrl: "End User Registration URL",
    training: "Training",
    trainingVenue: "Training Venue",
    specialNote: "Special Note",
    replyToContactDetails: "Reply to contact details",
    role: "Role",
    phone: "Phone",
    how_users_Register: "How Users Register",
    app: "App",
    advancedSettings: "Advanced Settings",
    ask_to_nominate: "Ask players to nominate two positions",
    disclaimers: "Disclaimers",
    addDisclaimer: "Add Disclaimer",
    disclaimerLink: "Disclaimer Link",
    addAnotherDisclaimerLink: "Add Another Disclaimer Link",
    openRegistrations: "Open Registrations",
    product: "Product",
    dOB: "DOB",
    year2020: "2020",
    year2017: "2017",
    year2016: "2016",
    registrationAccountSummary: "Registration Account Summary",
    paymentFor: "Payment For",
    dateFrom: "Date From ",
    dateTo: "Date To",
    umpireAllocation: "Umpire Allocation",
    users: "Users",
    ages: "Ages",
    roles: "Roles",
    genders: "Genders",
    alternate_location: "Alternative location (within 25km)",
    internet: "Internet",
    socialMedia: "Social Media",
    other: "Other",
    participant: "Participant",
    specialNotes: "Special Notes",
    courtPreferences: "Court preferences",
    details: "Details",
    membership: "Membership",
    payments: "Payments",
    general: "General",
    early: "Early",
    family: "Family",
    custom: "Custom",
    amountType: "Amount Type",
    addDiscount: "Add Discount",
    question: "Do you have a disability?",

    /// //formik validation/////

    pleaseSelectCompetition: "Please select competition",
    pleaseSelectYear: "Please Select Year",
    select: "Select",
    trainingDaysAndTimes: "Training days and Times",
    // ******** Live Score Matches **********
    matchList: "Match List",
    addMatches: "Add Matches",
    export: "Export",
    import: "Import",
    matchName: "WSA 2 VS WSA 1",
    addMatch: "Add Match",
    date: "Date",
    divisionName: "Division Name",
    matchID: "mnbMatchId",
    homeTeam: "Home Team",
    awayTeam: "Away Team",
    umpire1Name: "Umpire 1 Name",
    enterUmpire1name: "Enter Umpire 1 Name",
    umpire2Name: "Umpire 2 Name",
    enterUmpire2name: "Enter Umpire 2 Name",
    umpire1Club: "Umpire 1 Organisation",
    umpire2Club: "Umpire 2 Organisation",
    scorer1: "Scorer 1",
    scorer2: "Scorer 2",
    umpireName: "Umpire Name",
    umpireClubName: "Umpire's Organisation Name",
    scorerName: "Scorer Name",
    score: "Score",
    players: "Players",

    addScorer: "Add Scorer",
    selectTeam: "Select Team",
    emailAdd: "Email Address",
    enterEmail: "Enter Email",
    contactNO: "Contact no",
    contact_No: "Contact No",

    enterContactNo: "Enter Valid Contact Number",
    scorers: "Scorers",

    addTeam: "Add Team",
    teamName: "Team Name",
    enterTeamName: "Enter Team Name",
    teamLogo: "Team Logo",
    selectCompetition: "Select Competition",
    selectDivision: "Select Division",
    managerHeading: "Manager",
    new: "New",
    existing: "Existing",
    teamList: "Team List",

    managersList: "Manager List",
    addManager: "Add Manager",
    importManager: "Import Manager",
    upload: "Upload",
    aboutManager: "About Manager",
    managerProfile: "Manager Profile",
    emailAddress: "email@gmail.com",
    teamManagers: "Team Manager",
    emailValue: "email@gmail.com",
    nameValue: "test score",
    contactValue: "9646097979",
    enterFirstName: "Enter First Name",
    enterLastName: "Enter Last Name",
    enterDateOfBirth: "Enter date of birth",
    assignToMatch: "Assign To Match",
    aboutScorer: "About Scorer",
    importMatch: "Import Match",
    fileInput: "File Input",
    importTeam: "Import Team",
    exampleBlock: "Example block-level help text here.",
    noImage: "No Image",
    homeTeamFinalScore: "Home Team Final Score",
    awayTeamFinalScore: "Away Team Final Score",
    enterHomeTeamFinalScore: "Enter Home Team Final Score",
    enterAwayTeamFinalScore: "Enter Away Team Final Score",
    editMatch: "Edit Match",
    editTeam: "Edit Team",
    editManager: "Edit Manager",
    editScorer: "Edit Scorer",
    umpireList: "Umpire List",
    filterByDivision: "Filter By Division",
    competitionLadders: "Competition Ladders",
    playerList: "Player List",
    importPlayer: "Import Player",
    addPlayer: "Add Player",
    editPlayer: "Edit Player",
    profilePic: "Profile Picture",
    enterPlayerID: "Enter player ID",
    playerId: "Player ID",
    shootingState: "Shooting Stats",
    incidentDetails: "Incident Detail",
    photos: "Photos",
    // 24-Jan
    forfeit: "Forfeit",
    abandon: "Abandon",
    endMatch: "End match",
    addNews: "Add News",
    editNews: "Edit News",
    newsTitle: "News Title",
    enterNewsTitle: "Enter News Title",
    newsBody: "News Body",
    author: "Author",
    enterAuthor: "Enter Author",
    recipients: "Recipients",
    selectRecipients: "Select Recipients",
    newsImage: "News Image",
    newsVideo: "News Video",
    newsExpiryDate: "News Expiry Date",
    newsExpiryTime: "News Expiry Time",
    newsDetail: "News Detail",
    settings: "Settings",
    sponsorshipBanners: "Sponsorship Banners",
    venues: "Venues",
    matchSettings: "Match Settings",
    wouldLikeRecord: "Would you like to record?",
    record: "Record",
    report: "Report",
    attendance_record_report: "Attendance Recording and Reporting",
    scoring: "Scoring",
    whoScoring: "Who scoring",
    managersToScore: "Managers to score",
    courtToScope: "Court to score",
    acceptScores: "Accept scores",
    refereeAcceptScores: "Referee to Accept Scores",
    scorerAcceptScores: "Scorer to Accept Scores",
    scoringAndTimer: 'Scoring and Timer',
    single: "Single",
    timer: "Timer",
    ladderSettings: "Ladder Settings",
    publish_notify: "Publish and Notify",
    backToNews: "Back to all news",
    app: "App",

    scorerHeading: "Scorer",
    banners: "Banners",
    uploadImage: "Upload Image",
    bannerLink: "Banner Link",
    horizontalBannerLink: "Horizontal Banner Link",
    squareBannerLink: "Square Banner Link",
    sponsorName: "Sponsor Name",
    numberOfAdvertisingBanners: "Number of Advertising Banners",
    stateBody: "State Body",
    competitionOrganiser: "Competition Organiser",
    removeBanner: "Remove Banner",
    showHomePage: "Show On Home Page",
    showOnDrawsPage: "Show On Draws Page",
    showOnLadderPage: "Show On Ladder Page",
    showOnNewsPage: "Show On News Page",
    showOnChatPage: "Show On Chat Page",
    bannerFormat: "Banner Format",
    teamAttendance: "Team Attendance",
    newsList: "News List",
    gameTime: "Game Time",
    goalState: "Goal Statistics",
    bulkMatchChange: "Bulk Match Change",
    whatDoWantDO: "What do you want to do?",
    selectOption: "Select Option",
    whichMatchChange: "Which matches do you want to change?",
    matchOnDate: "Matches on this date",
    forTimeRange: "For this time range",
    byVenue: "By Venue (optional)",
    hour: "Hours",
    seconds: "Seconds",
    toThisTime: "Or to this time",
    pushBack: "Push Back",
    court: "Court",
    selectCourt: "Select Court",
    endMatches: "End Matches",
    selectResultType: "Select Result Type",
    round_1: "Round 1",
    round_2: "Round 2",
    selectRoundOne: "Select Round 1",
    selectRoundTwo: "Select Round 2",
    bringForward: "Bring forward",
    changeMatchCriteria: "Change matches with the following criteria",
    selectReason: "Select Reason",
    newsPost: "News Post",
    scorerProfile: "Scorer Profile",
    affiliate: "Affiliate",
    selectAffiliate: "Select Affiliate",
    useClubLogo: "Use Affiliate Logo",
    activeNews: "Active News",
    addNewRound: "Add New Round",
    twoHalves: "TWO_HALVES",
    fourQuarters: "FOUR_QUARTERS",
    editBanners: "Edit Banners",
    editBanner: "Edit Banner",
    addBanners: "Add Banners",
    /// /export URl
    exportUrl: "/players/csv?",

    membershipTypeName: "Membership Type Name",
    pleaseEnterMembershipTypeName: "Please Enter Membership Type Name",

    // venue new constants
    evenRotation: "Even rotation",
    allocateToSameCourt: "Allocate to same court",
    noPreference: "No Preference",
    anyGradePreference: "Do you have any court preferences for divisions or grades?",
    timeSlotRotation: "TimeSlot rotation",
    proceedLowerGrade: "Precede lower grades with higher grades",

    saveAsDefault: "Save as Default",

    // time slot constants
    anyTimePreference: "Do you have any timeslot preferences for divisions or grades?",
    none: "None",
    timeslotsAllocatedBasedOnMatches: "Timeslots allocated based on match duration",
    enterTimeMatchesEachDay: "Enter time matches should run each day",
    allocateToSameTimeslot: "Allocate to same time slot",
    newCompetition: "New Competition",
    teamPreferences: "Team Preferences",

    // team grading summary
    teamGradingSummary: "Team Grading Summary",
    addGrade: "Add Grade",

    // new changes in venue
    linkToHomeAffiliate: "Link To Home Affiliate",
    addressOne: "Address Line 1",
    addressTwo: "Address Line 2",
    suburb: "Suburb",
    postcode: "Postcode",

    editCompetition: "Edit Competition",
    selectVenue: "Select Venue",

    /// //live scores
    teamSearch: "Team Search",
    managerSearch: "Manager Search",
    scorerSearch: "Scorer Search",

    organisationTypeRefId: "organisationTypeRefId",
    affiliatedToOrgId: "affiliatedToOrgId",
    street1: "street1",
    street2: "street2",
    suburbField: "suburb",
    stateRefId: "stateRefId",
    middleName: "Middle Name",

    /// /Team Grading
    finalTeamGrading: "Final Team Grading",

    /// /Team Grading summary
    updateGradeName: "Update Grade Name",
    gradeName: "Grade Name",
    pleaseEnterGradeName: "Please enter grade name",

    /// livescores
    todaysIncidents: "Today's Incidents",
    todaysMatch: "Today's Matches",
    recipientSelection: "Select Recipients",

    /// /added 2 march
    ByMatch: "By Match",
    total: "Total",
    // End User Registration
    areYouRegisteringYourself: "Are you registering yourself?",
    whoAreYouRegistering: "Who are you registering?",
    child: "Child",
    whatTypeOfRegistration: "What type of registration?",
    nonPlayer: "Non Player",
    yesAsAPlayer: "Yes, as a Player",
    yesAsANonPlayer: "Yes, as a Non-Player",
    registeringSomeoneElse: "No, Registering someone else",
    competitionMembershipProductDivision: "Competition, Membership Product and Division",
    participantDetails: "Participant Details",
    indicatePreferredPlayerPosition: "Indicate two preferred playing positions:",
    fullName: "Full Name",
    playWithFriendSubtitle:
        "We may be able to accommodate friends playing with each other. Please note, this is normally only available for lower graded teams. You can choose up to three friends.",
    addAnotherProduct: "ADD ANOTHER PRODUCT",
    addAnotherParticipant: "ADD ANOTHER PARTICIPANT",
    organisation: "Organisation",
    favouriteTeamReference: "FavouriteTeam",
    firebirdPlayer: "FirebirdPlayer",
    registrationOtherInfo: "RegistrationOtherInfo",
    countryReference: "Country",
    nationalityReference: "Nationality",
    heardByReference: "HeardBy",
    playerPosition: "PlayerPosition",
    position1: "Position 1",
    position2: "Position 2",
    venuesList: "Venue List",
    venueDeleteConfirm: "Are you sure you want to delete this venue?",
    enhancedRoundRobin: "EnhancedRoundRobin",

    createTeam: "Create Team",
    unassigned: "Unassigned",
    gameTimeStatistics: "Game Time Statistics",
    searchManager: "Search Manager",
    searchScorer: "Search Scorer",
    divisionList: "Division List",

    /// add news

    notifyAgain: "Notify again",
    notify: "Notify",

    editDivision: "Edit Division",

    /// ///Organisation Levels enums
    national: "national",
    state: "state",

    /// //user roles enums
    super_admin: "super_admin",
    admin: "admin",
    manager: "Manager",
    scorer: "scorer",
    member: "member",
    spectator: "spectator",
    attendance_recorder: "attendance_recorder",
    player: "player",
    parent: "parent",
    parentHeading: "Parent",
    web_communications_admin: "web_communications_admin",
    web_umpires_admin: "web_umpires_admin",
    web_results_admin: "web_results_admin",
    web_finance_admin: "web_finance_admin",

    // game time statistics list

    period: "PERIOD",
    minute: "MINUTE",
    matches: "MATCH",
    totalGame: "TOTAL GAMES",
    voucherDeleteConfirmMsg: "Are you sure you want to delete this voucher?",
    productDeleteConfirmMsg: "Are you sure you want to delete this product?",
    participantDeleteConfirmMsg: "Are you sure you want to delete this participant?",
    friendDeleteConfirmMsg: "Are you sure you want to delete this friend?",
    registrationOptionConfirmMsg:
        "Changing the registration type will clear the information you have entered already. Please confirm you wish to proceed.",
    pleaseEnterTeamName: "Please Enter Team Name",

    selectPlayer: "Select Player",
    injury: "Injury",
    selectInjury: "Select Injury",
    claim: "Claim",
    yesNo: "Yes/No",
    playerConst: "Player",
    addImages: "Add Images",
    addVideos: "Add Video",
    time: "Time",
    sinBin: "Sin bin",
    includeInPersonalFouls: "Include in Personal Fouls",
    addIncident: "Add Incident",
    refereeReport: "Referee report",
    addRefereeReport: "Add Referee Report",
    selectRound: "Select Round",
    linked: "Linked",
    importDivision: "Import Division",
    primaryContact: "Primary Contacts",
    assignMatches: "Assign Matches",
    venueChange: "Venue Change",
    importIncident: "Import Incident",
    endDate: "End Date",
    please_Sel_Fee: "Please complete fees on the previous tab",

    short_Name: "Short Name",
    backToScorer: "Back to all Scorers",
    otherInformation: "Other Information",
    countryOfBirth: "Country of Birth",
    disability: "Disability",
    additionalQuestions: "Additional Questions",
    otherQuestions: "Other Netball Questions",
    netballQuestions: "Netball Questions",
    demographicQuestions: "Demographic Questions",
    addDivisionsAndGrades: "Add Divisions and Grades",
    useAffiliateLogo: "Use Affiliate logo",
    add_edit_comment: "Add/Edit Comment",
    addYourComment: "Please add your comment.",
    fixedDuration: "Fixed Duration",
    specificTime: "Specific Time",
    selectOrganisation: "Select Organisation",

    goalExport: "/stats/export/scoringByPlayer?competitionId=",
    gameTimeExport: "/stats/export/gametime?competitionId=",
    teamAttendanceExport: "/players/export/teamattendance?competitionId=",
    proceed: "Skip and Proceed",
    invalidPlayers: "Invalid Records",
    matchExport: "/matches/export?competitionId=",
    courtChange: "Court Change",

    totalCompetitions: "Total Competitions",
    livescoreCompetitions: "Live score competitions",
    toEditRegistrationDetails: "To edit registration details, please go to",
    registrationArea: "registration area",

    friends: "Friends",
    referFriends: "Referred Friends",

    logoImageSize: "Selected file must be less then 2 MB",
    logoType: "Selected file must be PNG, GIF or JPEG format",
    logo_size: 2000000,
    referaFriend: "Refer a Friend",
    playWithAFriend: "Play with a Friend",

    divisionsTimeSlot: "Add Divisions (in timeslot order - first to last)",
    gradesTimeSlot: "Add Grades (in timeslot order - first to last)",
    poolsTimeSlot: "Add Pools (in timeslot order - first to last)",

    seasonFixture: "Season Fixture",
    season: "Season",
    types: "Types",
    payment: "Payment",

    firstlevelAffiliate: "Affiliates - 1st level Affiliates - Association/Leagues",
    secondlevelAffiliate: "Affiliates - 2nd level Affiliates - Club/ School",
    anyOrgAssociation: "Any organisation - Association/Leagues",
    anyOrgClub: "Any organisation - Clubs/ Schools",
    NoRegistrations: "No Registrations",
    submitPayment: "Submit Payment",
    connectToStripe: "Connect to Stripe",
    goToStripeDashboard: "Go to Stripe Dashboard",
    exportPayments: "Export Payments",
    exportWithdrawals: "Export Withdrawals",
    stripePaymentDashboard: "Stripe Payments Dashboard",
    stripeWithdrawalsDashboard: "Stripe Withdrawals Dashboard",
    setupStripeForPayments: "Set up Stripe for Payments",
    setupStripeForWithdrawals: "Set up Stripe for Withdrawals",
    dispute_description: "Result in dispute",
    draft_description: "Final result entered and unconfirmed",
    final_description: "Final result entered and confirmed",
    deleteTeam: "Delete Team",
    addPhoto: "Add Photo",
    editPhoto: "Edit Photo",
    photoType: "PhotoType",
    matchesList: "Matches List",
    orgPhotosText: "These photos will display on the User Registration Form",
    compStartDate: "Competition Start Date",
    compCloseDate: "Competition End Date",
    importTeams: "Import Teams",
    noPhotosAvailable: "No photos available",
    downloadTemplate: "Download Template",
    finalsStartDate: "Finals Start Date",
    extraTimeMatchType: "Extra Time Type",
    applyToRef: "ApplyToFinals",
    extraTimeDrawRef: "ExtraTimeDraw",
    finalsFixtureTemplateRef: "FinalsFixtureTemplate",
    allowTeamRegistrationTypeRefId: "TeamRegistrationType",
    matchPreference: "Match Preference",
    teamA: "Team A",
    teamB: "Team B",
    lockedDraws: "Specific Match Preference",
    addDay: "Add Day",
    backToLiveScore: "Back To Live Score",
    venueConstraintModalMsg: "Do you want to remove fixture?",
    removeFixture: "Remove Fixture",
    addPreference: "Add Preference",
    forgotResetPassword: "Forgot/ Reset Password",
    returnToLogin: "Return to login",
    sendEmail: "Send Email",
    forgotPassword: "Forgot Password",
    logo: "Logo",
    registrationFormQuestions: "Registration Form Questions",
    noInformationProvided: "No information provided",
    bankAccountForWithdrawals: "Bank Account for Withdrawals",

    previous: "Previous",
    totalPages: "Total pages",
    currentPage: "Current page",
    buzzer: "Buzzer",
    extraTimeLabel: "Extra Time",
    extraTimeCheckboxTitle: "Extra time for a Draw in Round Matches",
    oneExtraTimeForDraw: "Allow only one extra time for a draw",
    extraTimeForAllDraws: "Allow extra time for all draws in this Match",
    timeouts: "Timeouts",
    applyToHalves: "Apply to Halves",
    applyToQuarters: "Apply to Quarters",
    turnOffBuzzer: "Turn off Buzzer",
    turnOff_30Second: "30 second warning",
    payouts: "Payouts",

    coachExport: "/users/byRole/export?roleId=17&entityTypeId=6&entityId=",
    managerExport: "/users/byRole/export?roleId=3&entityTypeId=6&entityId=",
    scorerExport: "/roster/exportScorer?entityTypeId=",
    positionExport: "/stats/positionTracking/export?",
    teamExport: "/teams/export?competitionId=",
    playersToPay: "Players to Pay",
    exportTeams: "Export Teams",
    exportPlayers: "Export Players",
    transactions: "Transactions",
    addCharityDescription: "Write a brief description of the Charity..",
    addCoach: "Add Coach",
    editCoach: "Edit Coach",
    coachList: "Coach List",
    exportRegQuestion: "Reg. Form Questions",
    noDataAvailable: "No Data Available",
    recordUmpire: "Record Umpire",
    deleteDivision: "Delete Competition Division",
    changeDivision: "Change Division",
    action: "Action",
    competitionDivisionValidation: "If there are any players graded to this division, they will be unassigned.",
    exception: "Exception",
    exceptionHeading: "This allows you to schedule a match at a venue or time outside the automatic scheduling",

    // Add Venue ToolTip Messages

    LatitudeMsg: `1. Go to google maps https://www.google.com/maps\n\n'
      2. Click on satellite view.\n\n
      3. Search for your venue.\n\n
      4. Click and drop a pin on the centre of the court then copy and paste both the Longitude and Latitude.`,

    overRideSlotMsg:
        "Only click if the Court has different availability to the Venue ie. Court 1 is only available for matches from 9am but the other courts are free from 8am",
    gameDayMsg: "Add the days of the week, matches can be played at this venue. Click + Add Day.",
    courtsMsg:
        "Add the Courts at this venue. For effective use of the Live Scoring App please add Longitude and Latitude of the Court.",

    activeNewsMsg: "A list of all of the news that currently appears in the Game Day App",
    todayMatchMsg:
        "A list of all the matches being played on this day. This list shows whether scorers have been set, attendance has been taken and if umpires have been recorded(optional). Please refresh your screen to get the latest updates.",
    playersToPayMsg: "A list of Players who have registered and are required to pay either with cash or a voucher.",
    todayIncidentMsg:
        "If enabled, a list of all of the incidents that have occurred on this day including injuries and disciplinary.",
    matchDurationMsg: "Game time only (in minutes). This time should exclude time for breaks.",
    mainBreakMsg: "Half time break (in minutes).",
    qtrBreatMsg: "Break after 1st and 3rd quarters (in minutes).",
    teamAliasMsg: "The name that is used for the Team on the draw and media.",
    bulkMatchMsg: `Push Back - Push back one, a number or all games to a day or time that suits.\n\n
      Bring Forward - Bring forward one, a number or all games to a day or time that suits.\n\n
      Abandon Matches - Abandon one, a number or all matches that are incomplete or not played.\n\n
      End Matches - End one, a number or all matches.\n\n
      Double Header - Create a double header where two rounds are played in the one round allocation ie. Round 2 is rained out and the association decides to play Round 2 and Round 3 together as two half matches.`,

    courtChangeMsg: "Move the matches on one, many or all Venues, Courts to another Venue, Court.",
    shortNameMsg: "The short name is used in the APP to make it easier for users to search.",
    recordUmpireMsg: "The Scorer or Manager of a match will document the Umpire names and the Clubs they belong to.",
    gameTimeTrackMsg:
        "If selected it portrays the Game Time played by the team and players of that team in the Game Day App.",
    positionTrackMsg: "If Selected allows tracking of team positions by player.",
    recordGoalAttemptMsg:
        "If selected allows for the recording of Goal Attempts, Misses and Penalty Misses by player.",
    centerPassEnableMsg: "Enable Centre Pass display. ",
    incidentEnableMsg:
        "Enable the tracking of incidents including disciplinary, injury- first aid and injury - ambulance.",
    recordMsg:
        "Choose between allowing scorers to record their own team, both teams or the oppositions team attendance.",
    reportMsg:
        "Determine which game time report you would like managers and coaches to see - choose between minute, period or games.",
    singleScoringMsg: "Team A is the only team scoring the match.",
    fiftyScoringMsg: "Team A scores first half and Team B scores second half",

    timerMsg: `Central  - games start, break and end at the same time. The Scorer has no ability to pause.\n\n
      Central with per match override - games all start at the designated time but can be paused and resumed by the Scorer anytime throughout the game.\n\n
      Per Match - games are started and paused by the Scorer.`,

    buzzerMsg: `Click on Turn off the Buzzer so it doesnt signal the start, breaks or end of the game.\n\n
      Click on 30 second warning so it doesnt sound with a 30 second warning for players to take the court.`,
    newsPublishMsg: "Publish the news/ message to the App only.",
    newsPublishNotifyMsg: "Publish the news/ message to the App and notify App users.",
    participateCompMsg: "A list of all Competitions your Organisation is competing in.",
    ownedCompetitionMsg: "A List of all Competitions your Organisation is responsible for.",
    compDetailsMsg:
        "If you have opened Registrations for this Competition than Competition Details fields will be pre-populated but you can change key details as appropriate. If you have not opened Registrations for this competition, then you need to complete these screens.",
    knockOutMsg:
        "A competition where teams are eliminated progressively. Each winner will play another in the next round until the final two teams meet.",
    roundRobinMsg: "Teams play each other one time. Finals are optional.",
    enhancedRoundRobinMsg:
        "Teams play each as many times as required in the number of rounds specified. Finals are optional.",
    compDivisionMsg:
        "You must add a Division to move to the next screen.Divisions can be age related or any category you choice. Example could include 11,12,13 etc or Junior, Senior. ",
    genderRestrictionMsg: "Restricts Users who register to a particular division based on their gender.",
    ageRestrictionMsg: "Restricts Users who register to a particular division based on their DOB.",
    playerGradingMsg:
        "For Direct Competitions only. Create Teams and then Drag and Drop Players from Unassigned in to their teams.",
    playerGradingToggleMsg:
        "Displays a running tally of the number of teams required for each division and the number of players in each team.",
    teamGradingSummaryMsg:
        "Teams will remain ungraded until you move them into Grades. Click on the square titled 'Unassigned' (which contains the number of teams) to begin grading.You can also re-name grades by clicking on the letter or name.",
    timeSlotNoPrefMsg: "There is no preference for the timeslots Divisions, Grades and Teams play in.",
    timeSlotEvenRotationMsg: "Divisions, Grades and Teams equally rotate through the timeslots.",
    allocateToSameTimeslotMsg: "Divisions and Grades can be allocated to a Timeslot.",

    affiliateDirectory: "Affiliate Directory",

    evenRotationMsgFor_V_T: "Evenly rotate Divisions or Grades to Courts.",
    allocateToSameCourtMsg: "Allocate Divisions or Grades to the same courts.",
    noPreferenceMsgFor_V_T: "There is No Preference for Court Rotations or Allocations",

    newTeamUserMsg: "Add a user who has NOT created an account in the App, is an administrator or has registered.",
    existingTeamUserMsg: "Add a user who has either created an account in the App, is an administrator or has registered.",
    doubleRoundRobinMsg: "Teams play each other twice. Finals are optional.",
    timeSlote_BasedOnMatchDurationMsg: "Timeslots are determined based on the match duration.",
    manuallyAddTimeSloteMsg: "Manually create Timeslots. You can apply these timeslots to all or individual Venues.",
    equallyRotateHomeAwayMsg:
        "Choose Equally rotate teams home/away venue competition if competition features Home and Away venues.",
    equallyRotateCentralizedVenueMsg:
        "Choose Equally rotate teams - centralised venue competition if competition is run at centralised venues.",

    /// /Competition Format Screen
    applyMatchFormatMsg:
        "Choose whether the match format is applied to all Divisions or whether it is different for particular Divisions.",
    applyFinalFormatMsg:
        "Choose to enable Finals. Apply Final format to all Divisions or by particular Division. ",
    matchDurationCompFormatMsg: "Total Match time NOT including breaks.",
    mainBreakCompFormatMsg: "Break Duration at half-time.",
    qtrBreakCompFormatMsg: "Break Duration at end of 1st and 3rd quarters.",

    /// /Registration Competition Fees
    regInviteesAffiliatesMsg:
        "Organisations that are affiliated below your organisation. They will invite Users (Players, Coaches, Umpires etc) to register to their organisation and they will then submit them to your competition.",
    regInviteesAnyOrgMsg:
        "Add Organisation(s) not linked below your organisation in your State.They will invite Users (Players, Coaches, Umpires etc) to register to their organisation and they will then submit them to your competition.",
    regInviteesDirectMsg:
        "Users (Players, Coaches, Umpire etc) will register direct to your organisation and you will place them into teams (if they are not directly registering teams to your organisation).",

    /// /Registration Form List
    regFormDashBoardMsg:
        "After you have added your Competition Fees, locate the Competition in the Registration Form table and click on edit (three dots in Action) to add Registration details and open registrations.",
    regFormOpenMsg: "List the date you want Registrations to open and be made available to users.",
    regFormCloseMsg:
        "List the date you want Registrations to close. Please note registrations can still be taken after this date if required.",
    regLockMsg: "Registration Lock immediately closes registration for those divisions it is applied to.",
    regFormTrainingMsg: "Show users training details like Date, Time and Venue.",
    regFormSpecialNoteMsg: "Detail any special notes you would like to include on the Registration Form.",
    regFormPhotoMsg:
        'These are stored in "Our Organisation" Photos. You can display as many photos as you would like to Users to show them your uniform, courts, logo etc.',
    replyContactDetailMsg:
        "Let Users know who to contact if they have any questions. You can choose to list their Name, Role, Email and or Phone number.",
    howUserRegisterMsg: "Define how Users can Register for your Competition.",
    additionQuesMsg: "Click on the Questions you would like to ask Users who are Registering to your Competition.",
    allDivisionsMsg: "All Divisions are charged the same Fees.",
    perDivisionMsg: "Each Division can be charged a different Fee. ",
    paymentSeasonalFeeMsg:
        "Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.",
    paymentCausalFeeMsg:
        "Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.",
    charityRoundUpMsg:
        "Add the ability for users Registering to round up their registration to the nearest $1, $5 or $10 to support the pre-defined charity.",
    discountMsg:
        "Choose the discount you would like to apply to your Competition Fee. Please note, this discount only applies to your organisations Competition Fee. You can choose which membership Product and Type this fee is applied to.",
    discountTypeMsg:
        "Currently the only choices are - Discount Code or Family. You can offer both discounts for the one competition but Family will be applied first. ",

    /// /Registration Membership Fee

    membershipProductNameMsg: "Add a name that your affiliated organisations can resonate with e.g. Annual Membership Fee",
    validityMsg: `Add how long you want the membership product to be available:\n\n
      * Calendar Year - 1st Jan to 31st Dec in that year\n\n
      * 12 months from date of Registration`,

    membershipCasualFeeMsg: "Fee charged to participate in a single game.",
    membershipSeasonalFeeMsg: "Fee charged to join a Netball competition.",
    firstComRegOnlyMsg:
        "Fee charged to the User for the first competition they join in the defined period (whether it be calendar year or 12 months from date of registration). It will not be charged if they join another competition in that defined period.",
    allCompRegMsg:
        "Fee charged to the User every time they join a competition in the defined period (whether it be calendar year or 12 months from date of registration).",
    membershipDiscountMsg:
        "Discounts applied here apply to Player Membership Fees only.",

    /// /For Users Module
    orgTypeMsg:
        "Detail the type of organisation being added. State Organisations can add Associations/ Leagues and Clubs/ Schools, Associations can only add Clubs/ Schools.",
    addAffiliatePermissionLevelMsg: `Choose the permission level for each contact.\n\n
      Admin - can access all areas in the platform.\n\n
      Umpires Admin - can access the Umpires platform.\n\n
      Finance Admin - can access Payments and the Registration platform.`,

    ourOrgPermissionLevelMsg: `Choose the permission level for each contact.\n\n
      Admin - can access all areas in the platform.\n\n
      Umpires Admin - can access the Umpires platform.\n\n
      Finance Admin - can access Payments and the Registration platform.`,

    selectedTeams: "Selected Teams Array",
    importCoach: "Import Coaches",
    ladderLink: "Ladder Link",
    inviteTypeRef: "InviteType",
    inviteType: "Type",
    DobMoreThan: "DOB more than",
    DobLessThan: "DOB less than",
    NoDobPreference: "No DOB Preference",
    DobPreference: "DOB Preference",
    both: "Both",
    sendInvitesTo: "Send invites to",
    registrationWizard: "Registration Wizard",
    createPublish: "Create and Publish",
    set: "Set",
    setup: "Set up",
    setupStripe: "Stripe account",
    resultStatus: "Result Status",
    whichTeamForfeited: "Which team forfeited?",
    matchAbandoned: "Match Abandoned?",

    addUmpire: "Add Umpire",
    editUmpire: "Edit Umpire",
    umpireSearch: "Umpire Search",
    nonPlayerDivisionMessage: "Divisions are not required for your selected membership type.",
    drawsLink: "Draws Link",
    finalsMessage: "Finals has not been enabled for this Competition",
    allowTeamRegistration: "Allow Team Registrations",
    individualRegistrations: "Individual User Registrations",

    /// //////shop
    importUmpire: "Import Umpire",

    addAProduct: "Add a Product",
    addProduct: "Add Product",
    enterTitle: "Enter Title",
    pricing: "Pricing",
    price: "Price",
    costPerItem: "Cost per item",
    chargeTaxesOnProduct: "Charge taxes on product",
    inventory: "Inventory",
    enableInventoryTracking: "Enable inventory tracking",
    StockKeepingUnit: "Stock keeping unit",
    skuHeader: "SKU(stock keeping unit)",
    barcodeHeading: "Barcode(ISBN, UPC, GTIN etc)",
    barcode: "Barcode",
    quantity: "Quantity",
    allowCustomerToPurchase: "Allow customers to purchase this product when it's out of stock",
    variants: "Variants",
    enableVariants: "Enable Variants",
    variantName: "Variant Name",
    variant_name: "Variant name",
    orders: "Orders",
    orderSummary: "Order Summary",
    orderStatus: "Order Status",
    parentOrGuardianDetail: "Parent/Guardian Details",
    useChildEmail: "Same as child’s email",
    useParentEmail: "Use parent’s email address",
    childMsg2Parent:
        "You have elected to use the same email for your Child and yourself. You child will not get their own log-in. If you would like them to have their own log-in please give them a separate email address.",
    childMsg2Admin:
        "You have elected to use the same email for the Child and Parent. The child will not get their own log-in. If you would like them to have their own log-in please give them a separate email address.",
    parentMsg2Child:
        "You have elected to use the same email for your Parent and yourself. You will lose your login unless you update your own email address first.",
    parentMsg2Admin:
        "You have elected to use the same email for the Child and Parent. The child will not retain their own login. If you would like them to have their own login please give them a separate email address first.",
    numbersOfOrders: "Number of ORDERS",
    valueOfOrders: "Value of ORDERS",
    orderId: "Order Id",
    netProfit: "Net Profit",
    paid: "Paid",
    notPaid: "Not Paid",
    addOrder: "Add Order",
    paymentStatus: "Payment Status",

    fulfilmentStatus: "Fulfilment Status",
    attendanceRecordingTime: "Attendance Recording Time",
    lineupSelection: "Lineup Selection",
    _days: "Days",
    _hours: "Hours",
    _minutes: "Minutes",

    lineUpSelectionMsg: "We can’t enable lineup selection without position tracking",
    // umpireListExport: "https://users-api-dev.worldsportaction.com/users/byRole/export/org?",
    umpireListExport: "users/byRole/export/org?",
    disabilityCareNumber: "Disability care Number",
    typeOfDisability: "Type of Disability",
    pickUpAddress: "Pick up address",
    productTypes: "Product Types",
    topSellers: "Top Sellers",
    productType: "Product Type",
    divisionGradeAndTeams: "Division, Grade and Teams",
    numbersOfTeams: "Number of teams",

    shipping: "Shipping",
    pickup: "Pickup",
    pickupInstructions: "Pick Up Instructions",
    productDimensionsWeight: "Product dimensions and weight",
    dimensions: "Dimensions",
    size: "Size",
    sku: "SKU",
    option: "Option",
    addVariantOption: "Add variant option",
    deleteProduct: "Delete Product",
    deleteProductDescription: "Please confirm you want to delete this product?",
    umpireDashboardExport: "/matchUmpire/dashboard/export?",
    updateAction: "Update Action",
    actionBoxConfirmMsg: "Are you sure you want to complete this activity?",
    backToUmpire: "Back to all Umpires",
    assignMatch: "Assign Match",
    generateRoster: "Generate Roster",
    howUmpiresAllocated: "How are Umpires Allocated",
    umpirePreferences: "Umpire Preferences:",
    noOfMatches: "Number of Matches they can ",
    timeBetweenUmpireMatch: "Time between Umpiring Matches",
    umpireReservePref: "Umpire Reserve",
    reserveAllocationTiming: "Reserve Allocation timing",
    activeUmpireCoach: "Activate Umpire Coaches",
    umpirePoolsDivision: "Umpire Pools Allocation To Divisions/Grades",
    allocateUmpires: 'Allocate Umpires',
    allocationAlgorithmModaltitle: 'Apply allocation algorithm to these rounds',
    noPoolAdded: "Pools were not added to this competition yet.",
    allocatePools: "Allocate Pools To",
    badgeAA: "Badge AA",
    badgeA: "Badge A",
    badgeB: "Badge B",
    badgeC: "Badge C",
    umpireCoach: "Umpire Coach",
    juniorUnbadge: "Junior Unbadge",
    umpirePools: "Umpire Pools",
    competitionVenueAllocation: "Competition Venue allocation",
    divisionToFieldLinkage: "Division to Field Linkage",
    fieldSizes: "Field sizes",
    eighths: "Eighths",
    full: "Full",
    squadSelection: "Squad Selection",
    umpireExport: "/umpire/export?competitionId=",
    invite: "Invite",
    send: "Send",
    noSend: "No Send",
    tax: "Tax",
    dragImageToUpload: "Drag image to upload",
    addType: "Add type",
    coachSearch: "Coach Search",
    incident: "Incidents",
    selectIncident: "Select Incident",
    _spectator: "Spectator",
    discipline: "Discipline",
    injuryAmbulance: "Injury - Ambulance",
    injuryFirstAdd: "Injury - First Aid",
    emailExp: "/^-?(0|[1-9][0-9]*)(.[0-9]*)?$/",
    childDetails: "Child Details",
    addRegDivision: "Add Registration Divisions",
    downLoadImportHeading: "Download the matches list first then populate umpires details to upload ",
    assignUmpireToMatch: "Assign Umpires To Matches",
    participateInCompReg: "Participating-In Competition Registrations",
    ownedCompetitionsReg: "Owned Competition Registrations",
    newCompetitionReg: "New Competition Registration",
    rosterExport: "/roster/export/umpire?",
    Registrations: "Registrations",
    ladderAllDivisionRmvMsg: "Would you like to set this ladder format for 'All Divisions'?",
    ladderFormat: "Ladder Format",
    ladderRemoveMsg: "Are you sure you want to remove ladder format?",
    competitionEnabled: "Competition not enabled for Integrated Umpires, Click here to enable.",
    bulkScoreUpload: "Bulk Scores Upload",
    umpireRoster: "Umpire Roster",
    registrationDivisions: "Registration Divisions",
    activeUmpireReserves: "Activate Umpire reserves",
    simultaneousMatchAllocations: "Simultaneous match allocations",
    poolName: "Pool Name",
    umpireReserve: "Umpire Reserve",
    points: "Points",
    reasonForChange: "Reason For Change",
    editIncident: "Edit Incident",
    addCompetitionFormat: "Add Competition Format",
    fileUploadPdf: "File Upload (File Type: PDF)",
    link: "Link",
    qrCodeHeader: "Code from authenticator",
    paymentStatusReference: "PaymentStatus",
    positionTrackReport: "Position Tracking Report",
    periodFilter: "Period",
    byGame: "By Game",
    importTeamPlayer: "Import Team and Players",
    matchPrintTemplateType: "Match Print Template Type",
    templateType: "Template Type",
    playerBorrowing: "Player Borrowing",
    borrowPlayer: "Borrow player",
    gamesBorrowed: "Games Borrowed",
    minutesBorrowed: "Minutes Borrowed",
    premierCompLink: "Premier Competition Link",
    productAddedMessage: "Product added successfully.",
    productDeletedMessage: "Product deleted successfully.",
    typeAddedMessage: "Type added successfully.",
    registrationChange: "Registration Change",
    cost: "Cost",
    history: "History",
    somethingWentWrong: "Something went wrong.",
    payoutTimedoutError: "Your report is still being generated, please check back in half an hour!",
    variantDeletedMessage: "Variant deleted successfully.",
    refreshDownloads: "Refresh Downloads",

    // Account
    account: "Account",
    profileMenu: "Profile",
    passwordMenu: "Password",
    profileHeader: "Your Profile",
    passwordHeader: "Change your password",
    enterPhoneNumber: "Enter phone number",
    currentPassword: "Current password",
    enterCurrentPassword: "Enter current password",
    newPassword: "New password",
    enterNewPassword: "Enter new password",
    confirmPassword: "Confirm password",
    enterConfirmPassword: "Enter confirm password",
    userIsRegisteredTo: "User is registered to",
    competitionAdministrator: "Competition Administrator",
    regChangeDetail: "REGISTRATION CHANGE DETAILS",
    dateRegChange: "Date Registration Change",
    dateCompStart: "Date Competition Start",
    regChangeType: "Registration Change Type",
    generateFixtures: "Generate Fixtures",
    doTheySayForGame: "Do they say they have taken the court for training, grading or a competition game?",
    reasonToDeRegister: "Reasons why they would like to de-register?",
    overCommitted: "I am over committed with other activities and can't fit in time for netball",
    injuredOrHealthReason: "I have been injured or health reason (not netball related)",
    decideNotToParticipate: "Decided not to participate in netball",
    moveToDiffGeographicalArea: "Moving to different geographical area",
    otherReason: "Other",
    approvals: "Approvals",
    approve: "APPROVE",
    decline: "DECLINE",
    stateWideMsg: "State-wide messages",
    allOrganisation: "All Organisations",
    individualOrganisation: "Individual Organisation",
    firstLevelAffiliatesAssociationLeague: "1st Level Affiliates - Association/ League",
    secondLevelAffiliatesClubSchool: "2nd Level Affiliates - Club/ School",
    teamSeasonalFee: "Team Seasonal Fee",
    instalmentDate: "Instalment Date",
    addInstalmentDate: "+ Add Instalment date",
    settingsAddedMessage: "Settings added successfully.",
    addressAddedMessage: "Address added successfully.",
    deleteVariantOption: "Delete variant option",
    deleteVariantOptionDescription: "Please confirm you want to delete this variant option?",
    deleteProductType: "Delete product type",
    deleteProductTypeDescription: "Please confirm you want to delete this product type?",
    emailChangedWarning: "You will need to log in with your new email address on your next login.",
    settingsUpdatedMessage: "Settings updated successfully.",
    charity: "Charity",
    termsAndCond: "T&Cs",
    roundUp: "Round Up",

    /// id for home dashboard
    whatDoYouWantToPublish: "What do you want to Publish?",
    part: "Part",
    home_page_heading: "home_page_heading",
    homeTab: "home_tab",
    maintain_tab: "maintain_tab",
    venue_courtId: "venue&court",
    home_icon: "home_icon",
    competition_icon: "competition_icon",
    competitions_label: "competitions_label",
    registration_icon: "registration_icon",
    registrations_label: "registrations_label",
    user_profile_icon: "user_profile_icon",
    log_out: "log_out",
    impersonation: "Impersonation",
    acct_settings_label: "acct_settings_label",
    help_support_label: "help&support_label",
    home_table_view: "home_table_view",
    //* ************************ */

    editRegrade: "Edit/Regrade",
    fullCompetition: "Full Competition",
    competitionStartDate: "Competition Start Date",
    statusPublishHover:
        "This competition needs to be unlocked using the Edit / Regrade option on the competition dashboard in order to be edited",

    venueAddressDetailsError: "Please input venue address in details",
    venueAddressError: "Please select a venue from the venue search",
    venueAddressSelect: "Please select a venue from the venue search",
    venueSearch: "Venue Search",
    matchSheetsNoPrintError: "There is no match sheets to print.",
    selectTemplateTypeError: "Please select template type.",
    selectTemplateType: "Select template type",
    liveScoreMatchSheetPreviewModalTitle: "LiveScores Match Sheet",
    tableMatchID: "Match ID",
    tableSheetID: "Sheet ID",
    createdAt: "Created at",
    download: "Download",
    downloads: "Downloads",
    pleaseInputAddress: "Please input address",
    roundsNotAvailable: "Rounds not available",
    venueSavedSuccessfully: "Successfully Saved",
    checkVenueAddressDuplication: "Check venue address duplication",
    successMessage: "Successfully inserted",
    videoSize: "Selected file must be less then 2 MB",
    video_size: 2048000,
    qcTimeslotNotApplicable: "Timeslots are not applicable for quick competition",
    qcVenueConstraintNotApplicable: "Venue Constraints are not applicable for quick competition",
    publishModalInfo: "You have changed the grade of the following teams:",
    publishModalConfirmationMsg: "Would you like to adjust their ladder points?",
    videoSizeMessage: "The maximum file size can be 2 MB",
    childrenCheckNumber: "Requires Working with Children Check",
    regenerateDrawTitle: "Regenerate draw from which Round?",
    impersonationOrgSelect: "Choose an organization to access",
    numberOfOrders: "Number of Orders",
    teamRegistrations: "Team Registrations",

    umpirePayments: "Umpire Payments",
    bulkPayment: "Bulk Payment",
    whoAssignsUmpire: "Who Assigns Umpires",
    umpireRate: "Umpire Rate",
    umpireResRate: "Ump. Reserve Rate",
    umpireCoachRate: "Ump. Coach Rate",
    addAnotherGroup: "Add Another Group",
    umpirePaymentSetting: "Umpire Payment Settings",
    refundFullAmount: "Refund Full Amount",
    refundPartialAmount: "Refund Partial Amount",
    pickedUp: "Picked up",
    shipped: "Shipped",
    orderDetails: "Order Details",
    order: "Order",
    shippingAndBillingAddress: "Shipping and Billing Address",
    orderFulfilment: "Order Fulfilment",
    capturePayment: "Capture Payment",
    receiptUrl: "Receipt Url",
    extraTime: "Extra Extra Time",
    compDeleteConfirm: "Are you sure you want to delete (COMP_NAME)?",
    createRoster: "Create Roster",
    addLiveStream: "Add Live-Stream",
    liveStreamlink: "Live-Stream Link",
    uponRegistration: "Upon Registration",
    reg: "REG",
    dateRange: "Date Range",
    publishToLivescore:
        "Do you want to publish teams and players to Match Day so managers and coaches can communicate with their teams (prior to the draw being finalised)?",
    finalGrading: "Publish - Final Grading",
    onlyCompMngmt: "Only Competition Management",
    deletePublishToLsMsg:
        "Are you sure you want to delete (COMP_NAME)? (COMP_NAME) has also been published to Match Day. Would you like to Delete?",
    deleteCompetition: "Delete Competition",
    enterCode: "Registration Code",
    finalExtraTime: "Final Extra Time",
    statusContextMsg: `“Pending Membership” (when the membership fee hasn’t been paid by the individual)\n\n
      “Pending Registration Fee” (when the individual fee is pending)\n\n
      “Registered” (when all fees have been paid)`,
    totalFeeMsg:
        "A fee charged to a player each time they take the court (where the seasonal fee is not being charged).",
    telExp: "^[0-9]{10}$",
    update: "Update",
    invalidRecords: "Invalid Records",
    resetLadder: "Reset Ladder",
    resetLadderConformation: "Please select one of the following to Reset Ladder",
    selectedDivision: "Selected Division",
    fullReset: "Full Reset",
    divisionSettings: "Division settings",
    finalMatch: "Finals Match",
    extra_Time: "Extra Time",
    extraTimeType: "Extra Time Type",
    extraTimeqtrBreak: "Extra Time Quarter Break",
    alsoAssignAsUmpireCoach: "Also assign as Umpire Coach",
    recordGoalAttempt: "Record goal attempt",
    addAnotherPool: "Add Pool",
    mergeCompetition: "Merge Competition",
    differencesBetween: "There are some differences between",
    oneHasPreference: "Which one has preference:",
    divisionAndGrades: "Division and Grades",
    combine: "Combine",
    whatRegistrationChange: "What registration change do you need to make?",
    registrationChangeRef: "RegistrationChange",
    reasonWhyYourAreDecline: "Reason why you are declining the request for de-registration?",
    whoPayUmpire: "Who pays Umpires",
    refundAmount: "Refund Amount",
    toDate: "To date",
    fromDate: "From date",
    apply: "Apply",
    noFixturesMessage: "No fixtures are available within the provided date range",
    noCompetitionYear: "There are no competitions for the selected year",
    attendance: "Attendance",
    umpireAllocationSettings: "Umpire Assignment Settings",
    whoAssignsUmpires: "Who Assigns Umpires",
    affiliateOrganisations: "Affiliate Organisations",
    noUmpires: "No Umpires",
    takenCourtForTraining: "Have you taken the court for training, grading or a competition game?",
    exportAttendance: "Export Attendance",
    exportAttendanceMessage: "Attendance exported successfully",
    singleUseDiscount: "Single Use Discount - No Fee Charged",
    singleUseDiscountSubject: "Your Single Use discount voucher to use with your Netball Registration",
    addCode: "Add Code",
    go: "Go",
    matchCalender: "Match Calendar",
    showByMatches: "Show By Matches",
    hideFilter: "Hide Filter",
    showAll: "Show all",
    showLess: "Show less",
    competitionDates: "Competition Dates",
    replicateSetting: "Replicate Settings",
    venuePreferences: "Venue Preferences",
    competitionName: "Competition Name",
    pools: "Pools",
    gradesOrPools: "Grades / Pools",
    playOff3rdPosition: "Playoff for 3rd position",
    whoPlaysWho: "Who plays who",
    whoPlaysWhoValidation: "Please remove duplicate from who plays who",
    umpireActivity: "Umpire Activity",
    showFilter: "Show Filter",
    hide: "Hide",
    importDraws: "Import Draws",

    heroImageForCompetition: "Hero Image for Registration Form",
    heroImageSizeText: "Approximate Dimension: Width: 1200px  Height: 400px",
    poolSettingsWhoPlaysWho: "Pool Settings - Who Plays Who",
    mailBodyText:
        "Hi,\n \nPlease use the following discount Code when you register in order to have your fee waived.",
    fixtureTemplate: "Fixture Template",
    reasonForTransfer: "Reason for Transfer",
    registrationCloseDate: "Registration close date",
    filterDates: "Filter Dates",
    showOnlyScheduledMatches: "Show only scheduled matches",
    showByDivision: "Show by Division/Grade",
    invertAxis: 'Invert Axis',
    notAllowed: 'Not allowed',
    uploadBankAccount: "Upload Bank Account",
    editBankAccount: "Edit Bank Account",
    theyAlreadyTakenCourt:
        "They have already taken the court for training, grading or a competition game",
    theyOweMonies: "They owe monies",
    noTeamAvailable: "No team available",
    suspended: "Suspended",
    suspendedQuestion: "How long will this player be suspended for?",
    reasonWhyYourAreDeclineFromTransfer:
        "Reason why you are declining the request to transfer from your organisation",
    reasonWhyYourAreDeclineToTransfer:
        "Reason why you are declining the request to transfer to you organisation",
    playerImport: "Import Players",
    teamFeePerMatch: "Team Fee Per Match",
    atPointOfRegistration: "At point of Registration",
    nominationFee: "Nomination Fee",
    nominationFeeTeam:
        "Please note - The manager can choose to pay the nomination fee or can split it with the players at the time of registration",
    paymentMethods: "Payment Methods",
    paymentMethod: "Payment Method",
    singleGamePerTeamMember: "Single Game Fee per Team Member(inc GST)",
    setMembershipProducts: "Set Membership Product(s)",
    chargedForFullSeason: "Charge All Fees at Registration",
    chargedPerMatch:
        "Charge at Match (Competition Fees only. Membership and Nomination Fees are charged at Registration)",
    feesPaidAtEachMatchByUser: "Total Team Fee for each match (Enter Team Fee)",
    feesPaidAtEachMatchByPlayer:
        "Individual Player Fee for each match (Enter Player Fee)",
    membershipPaymentOptions: "MembershipPaymentOption",
    membershipFeesPaymentOptions: "Membership Fee Payment Options",
    whenPaymentsRequired: "When Payments are Required",
    Communication: "Communication",
    fullCashAmount: "Full cash amount",
    partialCashAmount: "Partial cash amount",
    squadSelectionEnabled:
        "Squad selection will be disabled for this division if position tracking is disabled",
    affiliateAddressAddressSelect: "Please input affiliate address",
    editOrganisationMessage:
        "If you edit the organisations, please ensure all teams are linked to the correct organisation so that managers, scorers, umpires and coaches remain correctly linked to this competition. Would you like to proceed?",
    backToHome: "Back to home",
    pool: "Pool",
    wantYouRegenerateDraw: "Do you want to Regenerate the draw and:",
    retainException: "Retain Exception",
    removeException: "Remove Exception",
    reasonRegisterTitle: "Why would you like to de-register?",
    useRound1Template: "Use Round 1 template",

    purchase: "Purchases",
    membershipFeesRepayConfirmMsg:
        "Users have already registered to this membership fee. Do you want to proceed?",
    whichCompetitionSettingPrecedence:
        "Please select which competition’s settings will take precedence",
    quickCompetitionMismatchMsg:
        "The venue you have selected for this quick competition will override the competition you are merging to",
    regoFormConfirmMsg:
        "Some users may receive this email a second time. Do you want to proceed with an email notification?",
    emailNotificationUpdate: "Email Notification Update",

    unavailable: "Unavailable",
    teamGrading: "Team Grading",
    usernameEmail: "Username/Email",
    proceedText: "Proceed",
    categories: "Categories",

    umpirePaymentExport: "/matchUmpire/payments/export?",

    communicationList: "Communication List",
    addCommunication: "Add Communication",
    notification: "Notification",
    news: "News",
    sms: "SMS",
    backToCommunication: "Back to all communication",
    active: "Active",
    published: "Published",
    publishedDate: "Published Date",

    matchDay: "Match Day",
    matchDayComp: "Match Day Competitions",
    backToMatchDay: "Back To Match Day",
    umpireAccreditation: "Umpire Accreditation",
    expiry: "Expiry",
    incidentExport: "/incident/export?entityId=",
    minNoDays: "Minimum number of days",
    extendEndDate: "Extend End Date",
    membershipFeeCap: "Membership Fee Cap",
    perMatchFeesCannotSet:
        "Per match fees per player can't be set as this competition includes unnamed player type",
    applyMembershipProducts: "Apply to Membership Products",
    allMembershipProducts: "All Membership Products",
    fromDob: "From DOB",
    toDob: "To DOB",
    maxMembershipFeePayable: "Maximum Membership Fee Payable (excl. GST)",
    addAnotherMembershipProduct: "Add Another Membership Product",
    becsSetupNotificationTitle: "BECS Debit setup done",
    becsSetupNotificationBody:
        "Congratulations, you have successfully completed BECS debit setup",
    becsAlreadyCompletedMessage: "BECS setup already done",
    logo_Image_Size: "Selected file must be less then 2 MB",
    logo_Image_Format: "Only jpg, jpeg, png, webp formats are supported",
    imageSizeFormatText:
        "Selected file must be less then 2 MB and jpg, jpeg, png, webp formats are supported.",
    childUnlinkMessage:
        "Your Parent needs to re-link your Accounts. Please ask them to press link next to you name in their User Profile.",
    parentUnlinkMessage:
        "Your Child needs to re-link your Accounts. Please ask them to press link next to you name in their User Profile.",
    ok: "OK",
    tfaSuccessfullyReset: "TFA was reset successfully",
    errorInTFAReset: "There was an issue with resetting TFA",
    becsTnC:
        "By providing your bank account details and confirming this payment, you agree to this Direct Debit Request and the Direct Debit Request service agreement, and authorise Stripe Payments Australia Pty Ltd ACN 160 180 343 Direct Debit User ID number 507156 (“Stripe”) to debit your account through the Bulk Electronic Clearing System (BECS) on behalf of Word Sport Action Pty Ltd (the “Merchant”) for any amounts separately communicated to you by the Merchant. You certify that you are either an account holder or an authorised signatory on the account listed above.",
    mergeUser: "Merge User",
    userToMerge: "User to Merge",
    possibleMatches: "Possible Matches",
    possibleMatchesDescription: "Select the user you want to merge with and press Next",
    selectDetailsToKeep: "Select which details to keep",
    merge: "Merge",
    userMergedSuccessfully: "User merged successfully",
    selectAllFromThisUser: "Select all from this user",
    userInformation: "User Information",
    success: "Success",
    id: "ID",
    bankAccount: "Bank Account",
    pleaseSelectUserToMerge: "Please select user to merge",
    unableToContinue: "Unable to continue",
    selectAYear: "Select a year",
    resetTFA: "Reset TFA",
    actions: "Actions",
    ownRegistration: "Own Registration",
    otherRegistration: "Other Registration",
    yourProfile: "Your Profile",

    paidBy: "Paid by",
    feeType: "Fee Type",
    paymentType: "Payment Type",
    membershipType: "Membership type",
    totalFeeIncGst: "Total Fee (inc GST)",
    governmentVoucher: "Govt. Voucher",
    portion: "Portion",
    redeemVoucher: "Redeem Voucher",
    cashPaymentReceived: "Cash Payment received",
    pendingMembership: "Pending Membership",
    pendingRegistrationFee: "Pending Registration Fee",
    registered: "Registered",
    playerRegistration: "Player Registration",
    coachRegistration: "Coach Registration",
    teamRegistration: "Team Registration",
    childRegistration: "Child Registration",
    pending: "Pending",
    declined: "Declined",
    owing: "Owing",
    enterAddressManually: "Enter Address Manually",
    addressSearch: "Address Search",
    returnAddressSearch: "Return to Address Search",
    games: "Games",
    singleGameFees: "Single Game Fees",
    gamesPaid: "Games Paid",
    gamesRedeemed: "Games Redeemed",
    gamesToRedeem: "Games to redeem",
    howManyGames: "How many games?",

    divisionRemoveMsg: "Are you sure you want to remove division settings?",
    divisionAllDivisionMsg: "This will clear your other settings. Ok to proceed?",
    manuallyAllocate: "Manually Allocate",
    allocateViaPools: "Allocate Via Pools",
    umpireYourOwnTeam: "Umpire Your Own - Team",
    umpireYourOwnOrganisation: "Umpire Your Own - Organisation",
    maxNumberOfMatches: "Maximum number of matches",

    coachAccreditation: "Coach Accreditation",
    teamMembers: "Team Members",
    addTeamMembers: "Add Team Members",
    refunds: "Refunds",
    transferId: "Transfer Id",
    transactionId: "Transaction Id",
    payoutId: "Payout Id",
    refundId: "Refund Id",
    teamMember: "Team Member",
    addTeamMember: "Add Team Member",
    addPool: "Add Pool",
    pleaseEnterPoolName: "Please Enter Pool Name",
    nationalAccreditationLevelUmpireQ: "What is your national accreditation level (Umpire)?",
    nationalAccreditationLevelUmpire: "National accreditation level (Umpire)",
    accreditationUmpire: "accreditationUmpire",
    payPerMatch: "Pay per Match",
    teamMemberParentCheck: "I am the Parent/ Guardian",
    payingForMember: "I am paying all fees for this member",
    addNewParentGuardian: "Add New Parent/Guardian",
    newParentOrGuardian: "New Parent/Guardian",
    emergencyContact: "Emergency Contact",
    mobileNumber: "Mobile Number",
    selectedPaymentOption: "Please select a payment option",
    directDebit: "Direct Debit",
    creditCard: "Credit/Debit Card",
    directDebitMsg: "A transaction fee of 1.5% +30c applies (capped at $3.50).",
    creditCardMsg:
        "A transaction fee of 2.25% + 30c is charged for domestic credit cards and 3.0% + 30c for International. For American express cards a fee of 2.7% + 30c applies.",
    stripeMandate1: `By providing your bank account details and confirming this payment,
  you agree to this Direct Debit Request and the`,
    stripeMandate2: `, and authorise Stripe Payments Australia Pty Ltd ACN 160 180 343 Direct Debit User ID number 507156(“Stripe”) to debit your account through the Bulk Electronic Clearing System (BECS) on behalf of World Sport Action Pty Ltd (the "Merchant") for any amounts separately communicated to you by the Merchant.You certify that you are either
  an account holder or an authorised signatory on the account listed
  above.`,
    securePaymentMsg: "There is no payment required",
    securePaymentOptions: "Secure Payment Options",
    somethingWentWrongErrorMsg: "Something went wrong.Please contact Administrator",
    tShirtSizeList: "TShirtSize",
    nationalAccreditationLevelCoachQ: "What is your national accreditation level (Coach)?",
    nationalAccreditationLevelCoach: "National accreditation level (Coach)",
    expiryDate: "Expiry Date",
    byBadge: "By Badge",
    byPool: "By Pool",
    noPoolMsg: "There are no pools in this competition",

    thankYouRegistering: "Thank you for registering!",
    emailConfirmNewUserMessage:
        "We have sent you an email confirmation with your new login details. Please log in to the website to manage your profile.",
    emailConfirmExistingUserMessage:
        "We have sent you an email confirmation. You can view your registrations and manage your profile on our website.",

    subTotal: "Sub-total",
    transactionFee: "Transaction Fee",
    totalPaymentDue: "Total Payment Due",

    warning: "Warning",
    confirmSaveMessage: "Would you like to save your changes?",

    removed: "Removed",
    removeFromTeam: "Remove from Team",
    removedFromGame: "Removed from game",
    addToTeam: "Add to Team",
    removeFromTeamPopUpMsg: "Do you want to remove this user from the team?",

    deletePool: "Delete pool",
    removePoolMsg: "Are you sure you want to delete this pool?",
    removeMsg: "Are you sure you want to delete",
    addToAnotherPool: "Add to another pool",
    removeFromPool: "Remove from pool",
    addUmpireToPool: "Add umpire to pool",
    toPool: "to pool",
    umpireAlreadyInPool: "This umpire is already added to this pool.",
    confirmUnassignMsg:
        "This umpire is also added to another pool. Would you like to move him to Unassigned section?",
    removeFromAllPools: "Remove from all pools",
    poolAddedSuccessMsg: "New pool was added successfully",
    poolRemovedSuccessMsg: "Pool was removed successfully",

    yourOrder: "Your Order",

    paymentSummary: "Payment Summary",
    salesSummary: "Sales Summary",
    summaryByParticipant: "Summary by participant",
    nominationFeesPaid: "Nomination Fees Paid",
    nominationFeesDeclined: "Nomination Fees Declined",
    nominationFeesOwing: "Nomination Fees Owing",
    competitionFeesPaid: "Competition Fees Paid",
    competitionFeesDeclined: "Competition Fees Declined",
    competitionFeesOwing: "Competition Fees Owing",
    affiliateIfApplicable: "Affiliate (if applicable)",

    userDetailsInvalid: "User Details Invalid",
    pleaseInputAmount: "Please input amount",

    cashReceived: "Cash Received",
    retryPayment: "Retry Payment",

    parentDetails: "Parent details",
    noOfRegisteredUsersInfo: "Number of individual users who are registered to your organisation or 1st / 2nd level affiliates (if applicable)",
    noOfRegistrationsInfo: "Note: number of registrations are counted per role / competition",
    refund: "Refund",
    maximumAmountPopupTxt: "Refund cannot be processed since the requested amount is more than the applicable amount.",
    enterRefundAmount: "Please enter the amount to be Refunded.",
    enterAmount: "Enter the Amount",
    partialRefund: "Partial Refund",
    enterValidAmount: "Please enter valid amount",

    // Communication
    communicationDetails: 'Communication Details',
    communicationtitle: 'Communication Title',
    enterCommunicationtitle: 'Enter Communication Title',
    communicationBody: 'Communication Body',
    communicationImage: 'Communication Image',
    communicationVideo: 'Communication Video',
    communicationExpiryDate: 'Communication Expiry Date',
    communicationExpiryTime: 'Communication Expiry Time',
    editCommunication: 'Edit Communication',
    cancelDeRegistrtaion: "Cancel De-registration",
    cancelTransferReg: "Cancel Transfer registration",
    feePaid: "Fee Paid",
    regFailedModalMsg: "Do you want to mark the invoice as failed?",
    regRetryInstalmentModalMsg: "Do you want to retry the failed instalment?",
    failed: "Failed",
    wouldYouLikeToApprove: "Would you like to Approve?",
    regRetryModalMsg: "Do you want to retry the failed registration?",
    addDivOrGrade: "Add Div/Grade",
    markAsFailedReg: "Mark as Failed Registration",
    addAnotherMembershipCap: "Add Another Membership Cap",
    successfullyUpdated: "Successfully updated",

    // LiveScoreAddNew
    allManagers: "All Managers",
    allScorers: "All Scorers",
    allManagersAndScorers: "All Managers and Scorers",
    allUsers: "All Users",
    individualManager: "Individual Manager",
    individualScorer: "Individual Scorer",
    publishPastMatches: "Publish past matches?",

    // Hard-Coded Title
    communicationDeleteConfirm: "Are you sure you want to delete this communication?",
    competitionDeleteConfirm: "Are you sure you want to delete this competition?",
    divisionDeleteConfirm: "Are you sure you want to delete this division?",
    matchDeleteConfirm: "Are you sure you want to delete this match?",
    newsDeleteConfirm: "Are you sure you want to delete this news?",
    playerDeleteConfirm: "Are you sure you want to delete this player?",
    teamDeleteConfirm: "Are you sure you want to delete this team?",
    umpireProceedConfirm: "Assigning this umpire will unassign them from their current match assignment. Proceed?",
    registrationAddConfirm: "Do you want to add registration?",
    proceedConfirm: "You have teams ‘Not in Draw’. Would you still like to proceed?",
    makePaymentsConfirm: "Are you sure you want to make payments?",
    affiliateDeleteConfirm: "Are you sure you want to delete this affiliate?",

    affiliateName: "Affiliate Name",
    rank: "Rank",
    seasonResults: "Season Results",
    currentGrade: "Current Grade",
    newGrade: "New Grade",
    summary: "Summary",
    teamNumbers: "Team Numbers",
    minTeamsGradeOrDivision: "Min. Teams/Grade or Division",
    message: "Message",
    longitude: "Longitude",
    latitude: "Latitude",
    liveScoreAddConfirm: "By making this change you may cause the draw to duplicate or create a conflict. We strongly recommend you make all match changes in the Competition Management Draws screen. Do you want to Proceed anyway?",
    team1: "Team 1",
    team2: "Team 2",
    away: "Away",
    goalAttempts: "Goal Attempts",
    playTime: "Play Time",
    playPercent: "Play %",
    position: "Position",
    misses: "Misses",
    goals: "Goals",
    attempts: "Attempts",
    goalPercent: "Goals%",
    start: "Start",
    results: "Results",
    played: "Played",
    playedAttendance: "Played?",
    playingAttended: "Playing?",
    period1: "Period 1",
    period2: "Period 2",
    period3: "Period 3",
    period4: "Period 4",
    playedFullPeriod: "Played Full Period",
    timestamp: "Timestamp",
    missedPenalties: 'Penalty Misses',
    dateTime: "Date/Time",
    matchResult: "Match Result",
    matchStatus: "Match Status",
    playerName: "Player Name",
    signature: "Signature",
    borrowingTeam: "Borrowing Team",
    teamAliasName: "Team Alias Name",
    contact: "Contact",
    firstUmpireName: "First Umpire Name",
    firstUmpireClub: "First Umpire Club",
    secondUmpireName: "Second Umpire Name",
    secondUmpireClub: "Second Umpire Club",
    stateTitle: "State",
    nationalTitle: "National",
    registrationDetailsRequired: "Registration Details Required",
    medicalHistory: "Medical History",
    medicareNumber: "Medicare Number",
    privateInsurance: "Private Insurance Provider & Number",
    governmentRebate: "Government Rebate",
    nswActiveKids: "NSW Active Kids",
    fairPlayVoucher: "QLD Fair Play Voucher",
    totalFee: "Total Fee",
    paidAmount: "Paid Amount",
    membershipFeesGST: "Membership Fees (excl. GST)",
    nominationFeesExclGst: "Nomination Fees (excl. GST)",
    competitionFeesExclGst: "Competition Fees (excl. GST)",
    affiliateCompetitionFeesExclGst: "Affiliate Competition Fees (excl. GST)",
    affiliateNominationFeesExclGst: "Affiliate Nomination Fees (excl. GST)",
    associationNominationFeesExclGst: "Association Nomination Fees (excl. GST)",
    clubNominationFeesExclGst: "Club Nomination Fees (excl. GST)",
    genderRestriction: "Gender Restriction",
    organiser: "Organiser",
    totalFeeSeasonalIncGst: "Total Fee - Seasonal (inc GST)",
    totalFeeSingleGameIncGst: "Total Fee - Single Game (inc GST)",
    form: "Form",
    regDate: "Reg. date",
    fee: "Fee",
    seasonalFeeIncGst: "Individual User Seasonal Fee (inc GST)",
    bookingId: "Booking ID",
    customer: "Customer",
    refundedAmount: "Refunded Amount",
    umpire1: "Umpire 1",
    umpire2: "Umpire 2",
    accreditation: "Accreditation",
    verifiedBy: "Verified By",
    timeDatePaid: "Time/Date Paid",
    pay: "Pay",
    registrationDate: "Registration Date",
    registeredUser: "Registered User",
    friendName: "Friend Name",
    friendStatus: "Friend Status",
    friendEmail: "Friend Email",
    friendPhone: "Friend Phone",
    venueName: "Venue Name",
    address1: "Address1",
    address2: "Address2",
    postalCode: "Postal Code",
    ofCourts: "# Of Courts",
    historicalGrade: "Historical Grade",
    historicalResult: "Historical Result",
    errorMessage: "Error Message",
    line: "Line #",
    playingUp: "Playing Up %",
    primary: "primary",
    affiliateFeeNotSet: "Affiliate fee not set!",
    courtNumbers: "Court Numbers",
    courtName: "Court Name",
    overrideVenueTimeslots: "Override Venue Timeslots?",
    playerAttTeamA: "Player Att. Team A",
    playerAttTeamB: "Player Att. Team B",
    breakDuration: "Break Duration",
    mainBreakDuration: "Main Break Duration",
    gmtTimezone: "Timezone GMT",
    mnbPlayerId: "mnbPlayerId",
    bench: "Bench",
    noPlay: "No Play",
    enableUseOfVouchers: "Enable use of vouchers",
    qldActiveKids: "QLD Active Kids",
    noValue: "N/A",
    paidFeeInclGst: "Paid Fee (incl. GST)",
    pendingFeeInclGst: "Pending Fee (incl. GST)",
    duePerMatch: "Due per Match",
    duePerInstalment: "Due per Instalment",
    invoiceFail: "Invoice Fail",
    failedInstalmentRetry: "Failed Instalment Retry",
    failedRegistrationRetry: "Failed Registration Retry",
    transfer: "Transfer",
    registrationCap: "Registration Cap",
    registeredBy: "Registered By",
    toggleTimeline: "Toggle timeline",
    timeline: "Timeline",
};

export default AppConstants;
