const AppConstants = {
  login: 'Login',
  password: 'Password',
  addAffiliate: 'Add Affiliate',
  affiliatedTo: 'Affiliated To',
  all: 'All',
  organisationType: 'Organisation Type',
  status: 'Status',
  administrators: 'Administrators',
  maintain: 'Maintain',
  Regto: 'Reg. To',
  Regfrom: 'Reg. From',
  venueAndCourts: 'Venues & Courts',
  graphicalDashboard: 'Graphical Display',
  textualDashboard: 'Textual Display',
  userProfile: 'User Profile',
  affiliates: 'Affiliates',
  affiliateApproveReject: 'Affiliate - Approve / Reject',
  current: 'Current',
  pendingForApproval: 'Pending For Approval',
  club: 'Club',
  peninsulaNetballAssociation: 'Peninsula Netballl Club',
  name: 'Name',
  address: 'Address',
  phoneNumber: 'Phone Number',
  contacts: 'Contacts',
  ourOrganisation: 'Our Organisation',
  dashboard: 'Dashboard',
  affilatedTo: 'Affiliated To',
  contact1: 'Contact 1',
  contact2: 'Contact 2',
  contact: 'Contact ',
  title: 'Title',
  email: 'Email',
  mobile: 'Mobile',
  permissionLevel: 'Permission Level',
  remove: 'Remove',
  addContact: 'Add Contact',
  requestApproval: 'Request for Approval',
  cancel: 'Cancel',
  save: 'Save',
  association: 'Association',
  addAffiliates: 'Add Affiliates',
  updateAffiliates: 'Update',
  nsw: 'NSW',
  add: 'Add',
  postCode: 'Postcode',
  enterPostCode: 'Enter postcode',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  unspecified: 'Unspecified',
  dob: 'Date of Birth',
  competitionCategory: 'Competition Category',
  participant_firstName: 'Participant First Name',
  participant_middleName: 'Alternative or Middle Name',
  participant_lastName: 'Participant Last Name',
  contactMobile: 'Contact Mobile',
  contactEmail: 'Contact Email',
  reenterEmail: 'Re-enter Email',
  uploadPhoto: 'Upload Photo',
  or: 'or',
  takePhoto: 'Take Photo',
  emergencyContacts: 'Emergency Contacts',
  emergencyContactName: 'Emergency Contact Name',
  emergencyContactMobile: 'Emergency Contact Mobile',
  parents_guardians: 'Parent/ Guardian Details',
  firstName: 'First Name',
  lastName: 'Last Name',
  sameAddress: 'Use same Address as Participant',
  additionalInfoReqd: 'Additional Information required',
  additionalPersonalInfoReqd: 'Additional Personal Information required',
  haveYouEverPlayed: 'Have you ever played Netball before:',
  yes: 'Yes',
  no: 'No',
  grade: 'Grade',
  year: 'Year',
  clubOther: 'Club/other',
  lastCaptainName: 'Name your last Captain',
  playWithFriend: 'Play with a friend',
  referfriend: 'Refer a friend',
  friend: 'Friend',
  referfriend_friendLiketoPlay:
    'Refer a friend : Do you have a friend you think would like to play?',
  friendLiketoPlay: 'Do you have a friend you think would like to play?',
  existingMedConditions: 'Existing Medical Conditions',
  redularMedicalConditions: 'Regular Medications',
  hearAbouttheCompition: 'How did you hear about this Netball Competition?',
  who_fav_bird: 'Who is your favourite Firebird?',
  consentForPhotos:
    'Do you give consent for photos to be taken and used for promotional purposes',
  addOtherReg: 'Add Another Registration',
  favouriteTeam: 'Favourite Netball Team',
  OtherInfoReqd: 'Other information required',
  yourSupportImportant:
    'Your Support is important for the continued success of our Club. Can you help?',
  childrenCheckNumber: 'Working with Children Check Number',
  childrenNumber: 'Children Check Number',
  childrenCheckNumberInfo:
    'Working with Children Check Number (You are required to have a working with Children Number. If you don’t have one you will need to apply.)',
  childCountry: 'Which country were you born',
  childNationality: 'What nationality are you',
  childLangSpoken: 'Languages spoken at home',
  haveDisability: 'Do you have a disability?',
  addanotherQuestion: 'Add Another question',
  uniformAndMerchandise: 'Uniforms and Merchandise',
  vouchers: 'Vouchers',
  addvoucher: 'Add voucher',

  agreeTerm: 'I have read and agree to the  ',
  termsAndConditions: 'Terms and Conditions',
  reviewOrder: 'Review Order',
  checkOptions: 'Checkout Options',
  voucherLink: 'Voucher link',
  nearestCompetition: 'Nearest Competition',
  photo: 'Photo',
  addParent_guardian: 'Add Parent/Guardian',
  addfriend: 'Add Friend',

  usernamePasswordIncorrect:
    'Login Unsuccessful. Incorrect Username or Password',
  home: 'Home',
  user: 'User',
  registration: 'Registration',
  competitions: 'Competitions',
  liveScores: 'Live Scores',
  events: 'Events',
  shop: 'Shop',
  umpires: 'Umpires',
  incidents: 'Incidents',
  finance: 'Finance',
  totalRegistrations: 'Total Registrations',
  totalUsers: 'Total Users',
  edit: 'Edit',
  familyDiscount: 'Family Discount',
  appRegoForm: 'App Rego Form',
  spring2019: '2019 Spring',
  membershipCategory: 'Membership Category',
  netball: 'Netball',
  winter2019: '2019 Winter',
  competition: 'Competition',
  division: 'Division',
  years12: '12 Years',
  addTimeSlot: 'Add another time slot',
  saveDraft: 'Save Draft',
  next: 'Next',
  participateInComp: 'Participating-In Competitions',
  ownedCompetitions: 'Owned Competitions',
  addCompetition: 'Add Competition',
  replicateCompetition: 'Replicate Competition',
  draws: 'Draws',
  venue: 'Venue',
  round: 'Round',
  saveAsDraft: 'Save as Draft',
  publish: 'Publish',
  registrationForm: 'Registration Form',
  quickCompetition: 'Quick Competition',
  quickCompetition3: 'Competition Details (3/3)',
  quickCompetition2: 'Teams & Players (2/3)',
  quickCompetition1: 'Quick Competition (1/3)',
  proposedTeamGrading: 'Proposed Team Grading',
  proposedTeamGradingToggle: 'Proposed Team Grading Toggle',
  ladder: 'Ladder',
  competitionFormat: 'Competition Format',
  tournament: 'Tournament',
  weeklyCompetition: 'Weekly Competition',
  knockOut: 'Knock Out',
  roundRobin: 'Round Robin',
  membershipProduct: 'Membership Product',
  membershipProductName: 'Membership Product Name',
  validity: 'Validity',
  calendarYear: 'Calendar Year',
  twelveMonth: '12 months from registration',
  membershipTypes: 'Membership Types',
  membershipTYpe: 'Membership Type',
  playerHeading: 'Player',
  mandatePlayerAge: 'Mandate Player Age Restrictions',
  dob_from: 'DOB-From',
  dob_To: 'DOB-To',
  team: 'Team',
  umpire: 'Umpire',
  coach: 'Coach',
  addMembershipType: 'Add Membership Type',
  membershipFees: 'Membership Fees',
  applyMembershipFee: 'Apply Seasonal Membership Fees to',
  casualFee: 'Casual Fee',
  gst: 'GST',
  seasonalFee: 'Seasonal fee',
  type: 'Type',
  reg_1_comp: '1st Competition Registration only',
  reg_all_comp: 'All Competitions Registrations',
  reg_2_comp: 'Discount 2nd Competition Registration',
  reg_3_comp: 'Discount Seasonal Registration by Casual Fees paid',
  fees: 'Fees',
  discount: 'Discount',
  discounts: 'Discounts',
  gernalDiscount: 'General Discount',
  fixedAmount: 'Fixed $ amount',
  percentageOff: 'Percentage off',
  amount: 'Amount',
  description: 'Description',
  availableFrom: 'Available From',
  availableTo: 'Available To',
  discountCode: 'Discount Code',
  code: 'Code',
  earlyDiscount: 'Early Discount',
  addChild: 'Add Child',
  child1: 'Child 1 %',
  child2: 'Child 2 %',
  discountRename: 'Discount (rename)',
  delete: 'Delete',
  year2019: '2019',
  timeSlot: 'Time Slots',
  timeBetweenGames: 'Time between games',
  timeBetweenMatches: 'Time between matches',
  mins: 'mins',
  AbbottAddress: 'Abbott Road Curl,Curl',
  save_publish: 'Save & Publish',
  back: 'Back',
  finals: 'Finals',
  useDefault: ' Use Default',
  finalFixtures: 'Finals Fixture Template',
  matchType: 'Match Type',
  quarters: 'Quarters',
  matchDuration: 'Match Duration',
  mainBreak: 'Main Break',
  qtrBreak: 'Qtr Break',
  betweenGames: 'Between Games',
  assignManually: 'Assign Manually',
  regenerateDraw: 'Regenerate',

  ///*****Competition Finals */
  rounds4Top16: '4 Rounds-Top 16',
  rounds3Top4: '3 Rounds-Top 4',
  rounds2Top3: '2 Rounds-Top 3',
  round1Top2: '1 Round-Top 2',
  customise: 'Customise',
  extraTimeIfDraw1: 'Extra time if a Draw - 1st Time',
  applyAllRounds: 'Apply to all Rounds',
  applyAllSemiAndGrand: 'Apply to Semi and Grand Final',
  applyGrandOnly: 'Apply to Grand Final Only',
  extraTimeDuration: 'Extra Time Duration',
  extraTimeMainBreak: 'Extra Time Main Break',
  extraTimeBreak: 'Extra Time Break',
  beaforeExtraTime: 'Before Extra Time',
  extraTimeIfDraw2: 'Extra time if a Draw - 2nd Time',
  oneGoalWins: '1st Goal Wins',
  twoGoalWins: '2nd Goal Wins',
  addAnotherFinalFormat: 'Add Another Finals Format',
  setAsDefault: 'Set as Default',
  applyFinalFormat: 'Apply Final Format',
  //*****************Competition Fixtures */
  winterCompetition_7_8: 'Winter Competition (7/8)',
  fixtures: 'Fixtures',
  add_TimeSlot: 'Add Timeslot',
  addCourt: 'Add Court',
  RegistrationRestrictionType: 'RegistrationRestrictionType',
  CompetitionRegistration: 'Competition Registration',

  //******************user Add Affiliates */
  All_communications: 'All communications',
  competition_communcations: 'Competitions communications',
  secretary: 'Secretary',
  president: 'President',

  //*****************Competition Format */
  competition_name: 'Competition Name',
  use_default_competitionFormat: 'Use default Competition Format Settings',
  standard_round_robin: 'Standard Round Robin',
  double_round_robin: 'Double Round Robin',
  halves: 'Halves',
  fixture_template: 'Fixture Template',
  frequency: 'Frequency',
  weekly: 'Weekly',
  timeBetweenRounds: 'Time between Rounds',
  days: 'days',
  hours: 'hours',
  applyMatchFormat: 'Apply Match Format to',
  setUpFinalTemplate_optional: 'Set Up Finals Template (Optional)',
  addNewCompetitionFormat: 'Add New Competition Format',
  createDraftDraw: 'Create Draft Draw',
  applyLadderFor: 'Apply Ladder Format to',

  /*******competition Ladder */
  mwnaPointScheme: 'MWNA Points Scheme',
  applyLadderFormatTo: 'Apply Ladder Format to',
  addNewLadderScheme: 'Add New Ladder Format',
  useDefaultSettings: 'Use default settings',
  ladderAdjustment: 'Ladder Adjustment',
  addNewAdjustment: 'Add new Adjustment',
  recalculateLadder: 'Recalculate Ladder',
  finalise: 'Finalise',
  ladderFormatScheme: 'Ladder Point Scheme Name',

  /***competition matchSheet */
  matchSheets: 'Match Sheets',
  teams: 'Teams',
  gameTimeTracking: 'Game Time Tracking',
  periods: 'Periods',
  minutes: 'Minutes',
  totalGames: 'Total Games',
  positionTracking: 'Position Tracking',
  shooting: 'Shooting ',
  preview: 'Preview',
  print: 'Print',
  previewAll: 'Print All',

  /**** competition Open Reg form*/
  competitionDetails: 'Competition Details',
  competitionLogo: 'Competition Logo',
  addShortNotes_registering: 'Write a brief description of the Competition..',
  addVenue: ' Add Venue',
  typeOfCompetition: 'Type of Competition',
  numberOfRounds: 'Number of Rounds',
  enhancedRoundRobinType: 'Enhanced Round Robin Type',
  registration_close: 'Registrations Close',
  registration_type: 'Registration Type',
  nonPlayingDates: 'Non-Playing Dates',
  addAnotherNonPlayingDate: 'Add Another Non Playing Date',
  addAnotherDivision: 'Add Another Division',
  ageRestrictions: 'Age Restrictions',
  mandateAgeRestrictions: 'Mandate Age Restrictions',
  netSetGo: 'NetSetGo',
  walkingNetball: 'Walking Netball',
  socialNetball: 'Social Netball',
  fastFive: 'Fast Five',
  dobFrom: 'DOB From',
  dobTo: 'DOB To',
  gameSpecifics: 'Game Specifics',
  playerInEachTeam: 'Players in each team',
  minNumber: 'Minimum Number',
  maxNumber: 'Maximum Number',
  teams_in_each_grade_pool: 'Teams in each grade/pool',
  registrationInvitees: 'Registration Invitees',
  anyOrganisation: 'Any organisation',
  direct: 'Direct',
  notApplicable: ' Not Applicable',
  percentageOff_FixedAmount: 'Percentage off or Fixed Amount',
  governmentVouchers: 'Government Vouchers',
  nswActiveKids: 'NSW Active Kids',
  qldFairPlay: 'Qld Fair Play',
  charityRoundUp: 'Charity round up',
  roundTotheNearest$1: 'Round to the nearest $1',
  roundTotheNearest$5: 'Round to the nearest $5',
  roundTotheNearest$10: 'Round to the nearest $10',
  /*******Competition Part Player grade calculate */
  playerGradingToggle: 'Player Grading Toggle',
  playerGrading: 'Player Grading',
  open: 'Open',
  gradeAndNameTeams: 'Grade and Name Teams',
  teamtoggle: 'Team Toggle',
  submit: 'Submit',
  final: 'Final',
  addDivisions: 'Add Divisions',
  addTeams: 'Add Teams',
  winter_2019: 'Winter 2019',
  how_Add_teams_players: 'How will you add teams and players?',
  addManually: 'Add Manually',
  Merge_ExistingCompetition: 'Merge with an Existing Competition',
  inviteRegistration: 'Invite Registrations',
  addCompetitionDetails: 'Add Competition Details',
  SetUP_Template_Optional: 'Set Up Finals Template (Optional) >',
  re_grading: 'Re-grading',
  step1: 'Step-1',
  step2: 'Step-2',
  gradeToggle: 'Grade Toggle',
  finalisedDraw: 'Finalised Draw',
  confirm: 'Confirm',
  replicateWhichCompetition: 'Replicate which competition?',
  year2018: '2018',
  winter2018: '2018 Winter',
  newCompetitionName: 'New Competition Name',
  competitionType: 'Competition Type',
  startDate: 'Start Date',
  registrationFees: 'Registration Fees',
  divisions: 'Divisions',
  grades: 'Grades',
  Venues_Courts: 'Venues & Courts',
  competitionFormatGameTimes: 'Competition Format & Game Times',
  review: 'review',
  Step_3: 'Step 3',
  contactNumber: 'Contact Number',
  addAnotherCourt: 'Add another court',
  addAnotherVenue: 'Add another venue',
  venueAndTimes: 'Venue And Times',
  Venue1: 'Venue 1',
  club_TeamName: 'Club/Team Name',
  game_Days: 'Game Day(s)',
  dayOfTheWeek: 'Day of the week',
  startTime: 'Start Time',
  endTime: 'End Time',
  addAnotherDay: 'Add another day',
  courts: 'Courts',
  lesHughesSportingComplex: 'Les Hughes Sporting Complex',
  applyTo: 'Apply to',
  courtPrioritisation: 'Court Prioritisation',
  randomAllocation: 'Random Allocation',
  automaticallyAssign_LowestCourt_highestGrade:
    'Automatically assign - lowest court  to highest grade',
  automaticallyAssign_LowestCourt_LowerGrade:
    'Automatically assign - lowest court to lowest grade',
  preferenceSettings: 'Preference Settings',
  addAnother: 'Add another',
  courtDetails: 'Court Details',
  inbox: 'Actionbox',
  viewAll: 'View All',
  eventsToday: 'Events Today',
  competitionsOverview: 'Competitions Overview',
  addNew: 'Add New',
  participatingInCompetitions: 'Participating In Competitions',
  playerProfile: 'Player Profile',
  josefineMartinez: 'Josefine Martinez',
  dateOfBirth: 'Date of Birth',
  Date03032000: '03/03/2000',
  no0456765765: '0456 765 765',
  belrose08: 'Belrose 08',
  activity: 'Activity',
  statistics: 'Statistics',
  personalDetails: 'Personal Details',
  medical: 'Medical',
  addAnotherDetail: 'Add another detail',
  register: 'Register',
  username: 'Username',
  products: 'Products',
  productDetails: 'Product Details',
  playingMember: 'Playing Member',
  nonPlayingMember: 'Non Playing Member',
  Umpire_Referee: 'Umpire/Referee',
  category: 'Category',
  applicableTo: 'Applicable to',
  level1_Affiliate_Associations: '1st level Affiliate - Associations',
  rename: 'Rename',
  Level2_Affiliate_Clubs: '2nd Level Affiliate - Clubs',
  paymentFrequency: 'Payment Frequency',
  oncePerYear: 'Once Per Year',
  eachMatch: 'Each Match',
  eachCompetition: 'Each Competition',
  enterShortDescription: 'Enter a short description of the product...',
  dob__From: 'DOB - From',
  dob__To: 'DOB - To',
  addGst10: 'Add GST (10%)',
  clubFees: 'Club Fees',
  associationFees: 'Association Fees',
  stateFees: 'State Fees',
  allFees: 'All Fees',
  addAnotherVoucher: 'Add Another Voucher',

  ///registartion membership fees list
  addMembershipProduct: 'Add Membership Product',

  //comp court and times assign
  applyToAllVenues: 'Apply to all venues',
  applySettingsToIndividualVenue: 'Apply settings to individual venue',
  timeslotsAllocatedBasedOnGame: 'Timeslots allocated based on game times',
  manuallyAddTimeslots: 'Manually Add Timeslots',
  evenRotationTimeslots: 'Even rotation of teams to timeslots',
  divisionAndGradeTimeslots: 'Allocate Divisions and Grades to same timeslot',
  /*//registraion//*/
  addAFee: 'Add a Fee',
  competitionFees: 'Competition Fees',
  please_Sel_mem_pro: 'Please select membership product',
  net_set_go: 'Net Set Go',
  addDivision: 'Add Division',
  allDivisions: 'All Divisions',
  perDivision: 'Per Division',
  paymentOptions: 'Payment Options',
  organisationName: 'Organisation Name',
  organisationLogo: 'Organisation Logo',
  registrationOpen: 'Registration Open',
  registrationLock: 'Registration Lock',
  endUserRegistrationUrl: 'End User Registration URL',
  addMembershipCategory: 'Add Membership Category',
  training: 'Training',
  trainingVenue: 'Training Venue',
  specialNote: 'Special Note',
  replyToContactDetails: 'Reply to contact details',
  role: 'Role',
  phone: 'Phone',
  how_users_Register: 'How Users Register',
  app: 'App',
  website: 'Website',
  atEvent: 'At event',
  advancedSettings: 'Advanced Settings',
  shopIntegration: 'Shop integration',
  ask_to_nominate: 'Ask players to nominate two positions',
  disclaimers: 'Disclaimers',
  addDisclaimer: 'Add Disclaimer',
  disclaimerLink: 'Disclaimer Link',
  addAnotherDisclaimerLink: 'Add Another Disclaimer Link',
  openRegistrations: 'Open Registrations',
  product: 'Product',
  dOB: 'DOB',
  year2020: '2020',
  year2017: '2017',
  year2016: '2016',
  registrationAccountSummary: 'Registration Account Summary',
  paymentFor: 'Payment For',
  dateFrom: 'Date From ',
  dateTo: 'Date To',
  umpireAllocation: 'Umpire Allocation',
  users: 'Users',
  ages: 'Ages',
  roles: 'Roles',
  genders: 'Genders',
  alternate_location: 'Alternative location (within 25km)',
  internet: 'Internet',
  socialMedia: 'Social Media',
  other: 'Other',
  participant: 'Participant',
  specialNotes: 'Special Notes',
  sunday: 'Sunday',
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  anyGradePreference: 'Do you have any grade preference for courts?',
  rotateCourt: 'Do you want to rotate courts',
  preferenceTimeSlot: 'Do you have any grade preference for timeslots?',
  timeslotPreferences: 'Timeslot preferences',
  courtPreferences: 'Court preferences',
  homeTeamRotation: 'Home Team Rotation',
  rotateTeam: 'Rotate teams based on venue link',
  notRotateTeam: 'Rotate teams without venue link',
  noRotation: 'No rotation',
  drawPreferences: 'Draw Preferences',
  mandateTeamAge: 'Mandate Team Age Restrictions',
  mandateUmpireAge: 'Mandate Umpire Age Restrictions',
  mandateCoachAge: 'Mandate Coach Age Restrictions',
  details: 'Details',
  membership: 'Membership',
  payments: 'Payments',
  general: 'General',
  early: 'Early',
  family: 'Family',
  custom: 'Custom',
  amountType: 'Amount Type',
  addDiscount: 'Add Discount',
  question: 'Do you have a disability?',

  /////formik validation/////

  pleaseSelectCompetition: 'Please select competition',
  pleaseSelectYear: 'Please Select Year',
  select: 'Select',
  trainingDaysAndTimes: 'Training days and Times',
  // ******** Live Score Matches **********
  matchList: 'Match List',
  addMatches: 'Add Matches',
  export: 'Export',
  import: 'Import',
  matchName: 'WSA 2 VS WSA 1',
  addMatch: 'Add Match',
  date: 'Date',
  divisionName: 'Division Name',
  matchID: 'mnbMatchId',
  homeTeam: 'Home Team',
  awayTeam: 'Away Team',
  umpire1Name: 'Umpire 1 Name',
  enterUmpire1name: 'Enter Umpire 1 Name',
  umpire2Name: 'Umpire 2 Name',
  enterUmpire2name: 'Enter Umpire 2 Name',
  umpire1Club: 'Umpire 1 Organisation',
  umpire2Club: 'Umpire 2 Organisation',
  scorer1: 'Scorer 1',
  scorer2: 'Scorer 2',
  umpireName: 'Umpire Name',
  umpireClubName: "Umpire's Organisation Name",
  scorerName: 'Scorer Name',
  score: 'Score',
  players: 'Players',

  addScorer: 'Add Scorer',
  selectTeam: 'Select Team',
  emailAdd: 'Email Address',
  enterEmail: 'Enter Email',
  contactNO: 'Contact no',
  enterContactNo: 'Enter valid contact number',
  scorers: 'Scorers',

  addTeam: 'Add Team',
  teamName: 'Team Name',
  enterTeamName: 'Enter team name',
  teamLogo: 'Team Logo',
  selectComptition: 'Select Competition',
  selectDivision: 'Select Division',
  club_Association: 'Club/Association/State Body',
  selectClub: 'Select Club/Association/State Body',
  managerHeading: 'Manager',
  new: 'New',
  exsiting: 'Existing',
  teamList: 'Team List',

  managersList: 'Manager List',
  addManager: 'Add Manager',
  importManager: 'Import Manager',
  upload: 'Upload',
  aboutManager: 'About Manager',
  managerProfile: 'Manager Profile',
  emailAddress: 'email@gmail.com',
  teamManagers: 'Team Manager',
  emailValue: 'email@gmail.com',
  nameValue: 'test score',
  contactValue: '9646097979',
  enterFirstName: 'Enter first name',
  enterLastName: 'Enter last name',
  assignToMatch: 'Assign To Match',
  aboutScorer: 'About Scorer',
  importMatch: 'Import Match',
  fileInput: 'File input',
  importTeam: 'Import Team',
  exampleBlock: 'Example block-level help text here.',
  noImage: 'No Image',
  homeTeamFinalScore: 'Home Team Final Score',
  awayTeamFinalScore: 'Away Team Final Score',
  enterHomeTeamFinalScore: 'Enter Home Team Final Score',
  enterAwayTeamFinalScore: 'Enter Away Team Final Score',
  editMatch: 'Edit Match',
  editTeam: 'Edit Team',
  editManager: 'Edit Manager',
  editScorer: 'Edit Scorer',
  umpireList: 'Umpire List',
  filterByDivision: 'Filter By Division',
  competitionladders: 'Competition Ladders',
  palyerList: 'Player List',
  importPlayer: 'Import Player',
  addPlayer: 'Add Player',
  editPlayer: 'Edit Player',
  profilePic: 'Profile Picture',
  enterPlayerID: 'Enter player id',
  playerId: 'Player Id',
  shootingState: 'Shooting Stats',
  incidentDetails: 'Incident Detail',
  photos: 'Photos',
  // 24-Jan
  forfiet: 'Forfeit',
  abandon: 'Abandon',
  endMatch: 'End match',
  addNews: 'Add News',
  editNews: 'Edit News',
  newsTitle: 'News Title',
  enterNewsTitle: 'Enter News Title',
  newsBody: 'News Body',
  author: 'Author',
  enterAuthor: 'Enter Author',
  recipients: 'Recipients',
  selectRecipients: 'Select Recipients',
  newsImage: 'News Image',
  newsVideo: 'News Video',
  newsExpiryDate: 'News Expiry Date',
  newsExpiryTime: 'News Expiry Time',
  newsDetail: 'News Detail',
  settings: 'Settings',
  sponsorshipBanners: 'Sponsorship Banners',
  venues: 'Venues',
  matchSettings: 'Match Settings',
  wouldLikeRecord: 'Would you like to record?',
  record: 'Record',
  report: 'Report',
  attendence_reord_report: 'Attendance Recording and Reporting',
  scoring: 'Scoring',
  single: 'Single',
  timer: 'Timer',
  ladderSettings: 'Ladder Settings',
  publish_notify: 'Publish and Notify',
  backToNews: 'Back to all news',

  scorerHeading: 'Scorer',
  banners: 'Banners',
  uploadImage: 'Upload Image',
  selectImage: 'Select Image',
  bannerlink: 'Banner Link',
  removeBanner: 'Remove Banner',
  showHomePage: 'Show on Home Page',
  showonDrawsPage: 'Show on Draws Page',
  showonLadderPage: 'Show on Ladder Page',
  teamAttendane: 'Team Attendance',
  newsList: 'News List',
  gameTime: 'Game Time',
  goalState: 'Goal Statistics',
  bulkMatchChange: 'Bulk Match Change',
  whatDoWantDO: 'What do you want to do?',
  slectOption: 'Select Option',
  whichMatchChange: 'Which matches do you want to change?',
  matchOnDate: 'Matches on this date',
  forTimeRange: 'For this time range',
  byVenue: 'By Venue (optional)',
  hour: 'Hours',
  seconds: 'Seconds',
  toThisTime: 'Or to this time',
  pushBack: 'Push Back',
  court: 'Court',
  selectCourt: 'Select Court',
  endMatchs: 'End Matches',
  selectresultType: 'Select Result Type',
  round_1: 'Round 1',
  round_2: 'Round 2',
  selectRoundOne: 'Select Round 1',
  selectRoundTwo: 'Select Round 2',
  bringForward: 'Bring forward',
  changeMatchCriteria: 'Change matches with the following criteria',
  selectReason: 'Select Reason',
  newsPost: 'News Post',
  scorerProfile: 'Scorer Profile',
  affiliate: 'Affiliate',
  selectAffiliate: 'Select Affiliate',
  useClubLogo: 'Use Affiliate Logo',
  activeNews: 'Active News',
  addNewRound: 'Add New Round',
  twoHalves: 'TWO_HALVES',
  fourQuarters: 'FOUR_QUARTERS',
  editBanners: 'Edit Banners',
  editBanner: 'Edit Banner',
  addBanners: 'Add Banners',
  ////export URl
  // exportUrl: 'http://world-sport-action-socket.appspot.com/players/csv?competitionId=',
  exportUrl: '/players/csv?',

  ////Registartion
  membershipTypeName: 'Membership Type Name',
  pleaseEnterMembershipTypeName: 'Please Enter Membership Type Name',

  // venue new constants
  evenRotation: 'Even rotation',
  allocateToSameCourt: 'Allocate to same court',
  noPreference: 'No Preference',
  statringSaturday: 'Starting Sat 08/02',
  anyGradePreference2:
    'Do you have any court preferences for divisions or grades?',
  timeSlotRotation: 'TimeSlot rotation',
  proceedLowerGrade: 'Precede lower grades with higher grades',

  saveAsDefault: 'Save as Default',

  //time slot constants
  anyTimePreference:
    'Do you have any timeslot preferences for divisions or grades?',
  none: 'None',
  timeslotsAllocatedBasedOnMatchs:
    'Timeslots allocated based on match duration',
  enterTimeMatchesEachDay: 'Enter time matches should run each day',
  allocateToSametimeslot: 'Allocate to same time slot',
  newCompetition: 'New Competition',

  // team grading summary
  teamGradingSummary: 'Team Grading Summary',
  addgrade: 'Add Grade',

  //new changes in venue
  linkToHomeAffiliate: 'Link to Home Affiliate',
  addressOne: 'Address Line 1',
  addressTwo: 'Address Line 2',
  suburb: 'Suburb',
  stateHeading: 'State',
  postcode: 'Postcode',

  editCompetition: 'Edit Competition',
  selectVenue: 'Select Venue',

  /////live scores
  teamSearch: 'Team Search',
  managerSearch: 'Manager Search',
  scorerSearch: 'Scorer Search',

  organisationTypeRefId: 'organisationTypeRefId',
  affiliatedToOrgId: 'affiliatedToOrgId',
  street1: 'street1',
  street2: 'street2',
  suburbField: 'suburb',
  stateRefId: 'stateRefId',
  middleName: 'Middle Name',

  ////Team Grading
  finalTeamGrading: 'Final Team Grading',

  existing: 'Existing',

  ////Team Grading summary
  updateGradeName: 'Update Grade Name',
  gradeName: 'Grade Name',
  pleaseEnterGradeName: 'Please enter grade name',

  ///livescores
  todaysIncidents: "Today's Incidents",
  todaysMatch: "Today's Matches",
  recipientSelection: 'Enter Recipients',

  ////addedd 2 march
  ByMatch: 'By Match',
  total: 'Total',
  //End User Registration
  areYouRegisteringYourself: 'Are you registering yourself?',
  whoAreYouRegistering: 'Who are you registering?',
  child: 'Child',
  whatTypeOfRegistration: 'What type of registration?',
  nonPlayer: 'Non Player',
  yesAsAPlayer: 'Yes, as a Player',
  yesAsANonPlayer: 'Yes, as a Non-Player',
  registeringSomeoneElse: 'No, Registering someone else',
  competitionMembershipProductDivision:
    'Competition, Membership Product and Division',
  participantDetails: 'Participant Details',
  indicatePreferredPlayerPosition: 'Indicate two preferred playing positions:',
  fullName: 'Full Name',
  playWithFriendSubtitle:
    'We may be able to accommodate friends playing with each other. Please note, this is normally only available for lower graded teams. You can choose up to three friends.',
  addAnotherProduct: 'ADD ANOTHER PRODUCT',
  addAnotherParticipant: 'ADD ANOTHER PARTICIPANT',
  organisation: 'Organisation',
  favouriteTeamReference: 'FavouriteTeam',
  firebirdPlayer: 'FirebirdPlayer',
  registrationOtherInfo: 'RegistrationOtherInfo',
  countryReference: 'Country',
  nationalityReference: 'Nationality',
  heardByReference: 'HeardBy',
  playerPosition: 'PlayerPosition',
  position1: 'Position 1',
  position2: 'Position 2',
  venuesList: 'Venue List',
  venueDeleteConfirm: 'Are you sure you want to delete this venue?',
  enhancedRoundRobin: 'EnhancedRoundRobin',

  createTeam: 'Create Team',
  unassigned: 'Unassigned',
  gameTimeStatistics: 'Game Time Statistics',
  searchManager: 'Search Manager',
  divisionList: 'Division List',

  /// add news

  notifyAgain: 'Notify again',
  notify: 'Notify',

  editDivision: 'Edit Division',

  //////Organisation Levels enums
  national: 'national',
  state: 'state',

  /////user roles enums
  super_admin: 'super_admin',
  admin: 'admin',
  manager: 'Manager',
  scorer: 'scorer',
  member: 'member',
  spectator: 'spectator',
  attendance_recorder: 'attendance_recorder',
  player: 'player',
  parent: 'parent',
  parentHeading: 'Parent',
  web_communications_admin: 'web_communications_admin',
  web_umpires_admin: 'web_umpires_admin',
  web_results_admin: 'web_results_admin',
  web_finance_admin: 'web_finance_admin',

  //game time statistics list

  period: 'PERIOD',
  minute: 'MINUTE',
  matches: 'MATCH',
  totalGame: 'TOTAL GAMES',
  voucherDeleteConfirmMsg: 'Are you sure you want to delete this voucher?',
  productDeleteConfirmMsg: 'Are you sure you want to delete this product?',
  participantDeleteConfirmMsg:
    'Are you sure you want to delete this participant?',
  friendDeleteConfirmMsg: 'Are you sure you want to delete this friend?',
  registrationOptionConfirmMsg:
    'Changing the registration type will clear the information you have entered already. Please confirm you wish to proceed.',
  pleaseEnterteamName: 'Please Enter Team Name',

  selectPlayer: 'Select Player',
  injury: 'Injury',
  selectInjury: 'Select Injury',
  claim: 'Claim',
  yesNo: 'Yes/No',
  playerConst: 'Player',
  addImages: 'Add Images',
  addVideos: 'Add Video',
  time: 'Time',
  addIncident: 'Add Incident',
  selectRound: 'Select Round',
  linked: 'Linked',
  importDivision: 'Import Division',
  primaryContact: 'Primary Contacts',
  assignMatches: 'Assign Matches',
  venueChange: 'Venue Change',
  importIncident: 'Import Incident',
  endDate: 'End Date',
  please_Sel_Fee: 'Please fill the fees First',

  short_Name: 'Short Name',
  backToScorer: 'Back to all Scorers',
  otherInformation: 'Other Information',
  countryOfBirth: 'Country of Birth',
  disability: 'Disability',
  additionalQuestions: 'Additional Questions',
  otherQuestions: 'Other Questions',
  netballQuestions: 'Netball Questions',
  demographicQuestions: 'Demographic Questions',
  addDivisionsAndGrades: 'Add Divisions and Grades',
  useAffiliateLogo: 'Use Affiliate logo',
  add_edit_comment: 'Add/Edit Comment',
  addYourComment: 'Please add your comment.',
  fixedDuration: 'Fixed Duration',
  specificTime: 'Specific Time',
  selectOrganisation: 'Select Organisation',

  goalExport: '/stats/export/scoringByPlayer?competitionId=',
  gameTimeExport: '/stats/export/gametime?competitionId=',
  teamAttendaneExport: '/players/export/teamattendance?competitionId=',
  proceed: 'Skip and Proceed',
  invalidPlayers: 'Invalid Records',
  matchExport: `/matches/export?competitionId=`,
  courtChange: 'Court Change',

  publicLadderUrl: `https://netball-comp-admin-dev.worldsportaction.com/liveScorePublicLadder?competitionId=20b91f98-3f12-41c1-aeeb-70c9d6f4fa3d`,
  totalCompetitions: 'Total Competitions',
  livescoreCompetitions: 'Live score competitions',
  toEditRegistrationDeatils: 'To edit registration details, please go to',
  registrationArea: 'registration area',

  friends: 'Friends',
  referFriends: 'Referred Friends',

  logoImageSize: 'Selected file must be less then 250 KB',
  logoType: 'Selected file must be PNG, GIF or JPEG formate',
  logo_size: 250000,
  referaFriend: 'Refer a Friend',
  playWithAFriend: 'Play with a Friend',

  divisionsTimeSlot: 'Add Divisions (in timeslot order - first to last)',
  gradesTimeSlot: 'Add Grades (in timeslot order - first to last)',

  seasonFixture: 'Season Fixture',
  season: 'Season',
  types: 'Types',
  payment: 'Payment',

  SeasonFixtureUrl: `https://netball-comp-admin-dev.worldsportaction.com/liveScoreSeasonFixture?organisationId=3`,
  anyAssociation: 'anyAssociation',
  anyClub: 'anyClub',

  firstlevelAffiliate:
    'Affiliates - 1nd level Affiliates - Association/Leagues',
  secondlevelAffiliate: 'Affiliates - 2nd level Affiliates - Club/ School',
  anyOrgAssociation: 'Any organisation - Association/Leagues',
  anyOrgClub: 'Any organisation - Clubs/ Schools',
  NoRegistrations: 'No Registrations',
  submitPayment: 'Submit Payment',
  connectToStripe: 'Connect to Stripe',
  goToStripeDashboard: 'Go to Stripe Dashboard',
  disput_description: 'Result in dispute',
  draft_description: 'Final result entered and unconfirmed',
  final_description: 'Final result entered and confirmed',
  deleteTeam: 'Delete Team',
  addPhoto: 'Add Photo',
  editPhoto: 'Edit Photo',
  photoType: 'PhotoType',
  matchesList: 'Matches List',
  orgPhotosText: 'These photos will display on the User Registration Form',
  compStartDate: 'Competition Start Date',
  compCloseDate: 'Competition End Date',
  importTeams: 'Import Teams',
  noPhotosAvailable: 'No photos available',
  downloadTemplate: 'Download Template',
  finalsStartDate: 'Finals Start Date',
  extraTimeMatchType: 'Extra Time Type',
  applyToRef: 'ApplyToFinals',
  extraTimeDrawRef: 'ExtraTimeDraw',
  finalsFixtureTemplateRef: 'FinalsFixtureTemplate',
  allowTeamRegistrationTypeRefId: 'TeamRegistrationType',
  matchPreference: 'Match Preference',
  teamA: 'Team A',
  teamB: 'Team B',
  lockedDraws: 'Specific Match Preference',
  addDay: 'Add Day',
  backToLiveScore: 'Back To Live Score',
  venueConstraintModalMsg: 'Do you want to remove fixture?',
  removeFixture: 'Remove Fixture',
  addPreference: 'Add Preference',
  forgotResetPassword: 'Forgot/ Reset Password',
  returnToLogin: 'Return to login',
  sendEmail: 'Send Email',
  forgotPassword: 'Forgot Password',
  logo: 'Logo',
  registrationFormQuestions: 'Registration Form Questions',
  noInformationProvided: 'No information provided',

  previous: 'Previous',
  totalPages: 'Total pages',
  currentPage: 'Current page',
  buzzer: 'Buzzer',
  turnOffBuzzer: 'Turn off Buzzer',
  turnOff_30Second: '30 second warning',
  payouts: 'Payouts',

  coachExport: `/users/byRole/export?roleId=17&entityTypeId=1&entityId=`,
  managerExport: `/users/byRole/export?roleId=3&entityTypeId=1&entityId=`,
  scorerExport: `/roster/exportScorer?competitionId=`,
  teamExport: `/teams/export?competitionId=`,
  playersToPay: 'Players to Pay',
  exportTeams: 'Export Teams',
  exportPlayers: 'Export Players',
  transactions: 'Transactions',
  addCharityDescription: 'Write a brief description of the Charity..',
  addCoach: 'Add Coach',
  editCoach: 'Edit Coach',
  coachList: 'Coach List',
  exportRegQuestion: 'Reg. Form Questions',
  noDataAvailable: 'No Data Available',
  recordUmpire: 'Record Umpire',
  deleteDivision: 'Delete Competition Division',
  changeDivision: 'Change Division',
  action: 'Action',
  competitionDivisionValidation:
    'If there are any players graded to this division, they will be unassigned.',
  exception: 'Exception',
  exceptionHeading:
    'This allows you to schedule a match at a venue or time outside the automatic scheduling',

  //Add Venue ToolTip Messages

  LatitudeMsg: `1. Go to google maps https://www.google.com/maps\n\n'
  2. Click on satellite view.\n\n
  3. Search for your venue.\n\n
  4. Click and drop a pin on the centre of the court then copy and paste both the Longitude and Latitude.`,

  overRideSlotMsg:
    'Only click if the Court has different availability to the Venue ie. Court 1 is only available for matches from 9am but the other courts are free from 8am',
  gameDayMsg:
    'Add the days of the week, matches can be played at this venue. Click + Add Day.',
  courtsMsg:
    'Add the Courts at this venue. For effective use of the Live Scoring App please add Longitude and Latitude of the Court.',

  activeNewsMsg:
    'A list of all of the news that currently appears in the Game Day App',
  todayMatchMsg:
    'A list of all the matches being played on this day. This list shows whether scorers have been set , attendance has been taken and if umpires have been recorded(optional). Please refresh your screen to get the latest updates.',
  playersToPayMsg:
    'A list of Players who have registered and are required to pay either with cash or a voucher.',
  todayIncidentMsg:
    'If enabled, a list of all of the incidents that have occured on this day including injuries and disciplinary.',
  matchDurationMsg:
    'Game time only (in minutes). This time should exclude time for breaks.',
  mainBreakMsg: 'Half time Break (in minutes).',
  qtrBreatMsg: 'Break after 1st and 3rd quaters (in minutes).',
  teamAliasMsg: 'The name that is used for the Team on the draw and media.',
  managerNewMsg:
    'Add a user who has not registered in the App or Web platform as a ',
  managerExsitingMsg:
    'Add a user who has already registered in the App or Web platform as a ',
  bulkMatchMsg: `Push Back - Push back one, a number or all games to a day or time that suits.\n\n
  Bring Forward - Bring forward one, a number or all games to a day or time that suits.\n\n
  Abandon Matches - Abandon one, a number or all matches that are incomplete or not played.\n\n
  End Matches - End one, a number or all matches.\n\n
  Double Header - Create a double header where two rounds are played in the one round allocation ie. Round 2 is rained out and the association decides to play Round 2 and Round 3 together as two half matches.`,

  courtChangeMsg:
    'Move the matches on one, many or all Venues, Courts to another Venue, Court.',
  shortNameMsg:
    'The short name is used in the APP to make it easier for users to search.',
  recordUmpireMsg:
    'The Scorer or Manager of a match will document the Umpire names and the Clubs they belong to.',
  gameTimeTrackMsg:
    'If selected it portrays the Game Time played by the team and players of that team in the Game Day App.',
  positionTrackMsg: 'If Selected allows tracking of team positions by player.',
  recordGoalAtteptMsg:
    'If selected allows for the recording of Goal Attempts, Misses and Penalty Misses by player.',
  centerPassEnableMsg: 'Enable Centre Pass display. ',
  incidentEnableMsg:
    'Enable the trackng of incidents including disciplinary, injury- first aid and injury - ambulance.',
  recordMsg:
    'Choose between allowing scorers to record their own team, both teams or the oppositions team attendance.',
  reportMsg:
    'Determine which game time report you would like managers and coaches to see - choose between minute, period or games.',
  singleScoringMsg: 'Team A is the only team scoring the match.',
  fiftyScoringMsg: 'Team A scores first half and Team B scores second half',

  timerMsg: `Central  - games start, break and end at the same time. The Scorer has no ability to pause.\n\n
  Central with per match override - games all start at the designated time but can be paused and resumed by the Scorer anytime throughout the game.\n\n
  Per Match - games are started and paused by the Scorer.`,

  buzzerMsg: `Click on Turn off the Buzzer so it doesnt signal the start, breaks or end of the game.\n\n
  Click on 30 second warning so it doesnt sound with a 30 second warning for players to take the court.`,
  newsPublishMsg: 'Publish the news/ message to the App only.',
  newsPublishNotifyMsg:
    'Publish the news/ message to the App and notify App users.',
  participateCompMsg:
    'A list of all Competitions your Organisations is Competing In.',
  ownedCompetitionMsg:
    'A List of all Competitions your Organisation is responsible for.',
  compDetailsMsg:
    'If you have opened Registrations for this Competition than Competition Details fields will be pre-populated but you can change key details as appropriate. If you have not opened Registrations for this competition, then you need to complete these screens.',
  knockOutMsg:
    'A competition where teams are eliminated progressively. Each winner will play another in the next round until the final two teams meet.',
  roundRobinMsg: 'Teams play each other one time. Finals are optional.',
  enhancedRoundRobinMsg:
    'Teams play each as many times as required in the number of rounds specified. Finals are optional.',
  compDivisionMsg:
    'You must add a Division to move to the next screen.Divisions can be age related or any category you choice. Example could include 11,12,13 etc or Junior, Senior. ',
  genderRestrictionMsg:
    'Restricts Users who register to a particular division based on their gender.',
  ageRestrictionMsg:
    'Restricts Users who register to a particular division based on their DOB.',
  playerGradingMsg:
    'For Direct Competitions only. Create Teams and then Drag and Drop Players from Unassigned in to their teams.',
  playerGradingToggleMsg:
    'Displays a running tally of the number of teams required for each division and the number of players in each team.',
  teamGradingSummaryMsg:
    "Teams will remain ungraded until you move them into Grades. Click on the square titled 'Unassigned' (which contains the number of teams) to begin grading.You can also re-name grades by clicking on the letter or name.",
  timeSloteNoPrefMsg:
    'There is no preference for the timeslots Divisions, Grades and Teams play in.',
  timeSloteEvenRotationMsg:
    'Divisions, Grades and Teams equally rotate through the timeslots.',
  allocateToSametimeslotMsg:
    'Divisions and Grades can be allocated to a Timeslot.',

  affiliateDirectory: 'Affiliate Directory',

  newMsgForScorerManager:
    'Add a user who has NOT created an account in the App, is an administrator or has registered.',
  existingMsgForScorerManager:
    'Add a user who has either created an account in the App, is an administrator or has registered.',
  evenRotationMsgFor_V_T: 'Evenly rotate Divisions or Grades to Courts.',
  allocateToSameCourtMsg: 'Allocate Divisions or Grades to the same courts.',
  noPreferenceMsgFor_V_T:
    'There is No Preference for Court Rotations or Allocations',

  teamNewMsg:
    'Add a user who has NOT created an account in the App, is an administrator or has registered.',
  teamExsitingMsg:
    'Add a user who has either created an account in the App, is an administrator or has registered.',
  doubleRoundRobinMsg: 'Teams play each other twice. Finals are optional.',
  timeSlote_BasedOnMatchDurationMsg:
    'Timeslots are determined based on the match duration. ',
  manuallyAddTimeSloteMsg:
    'Manually create Timeslots. You can apply these timeslots to all or individual Venues.',
  equallyRotateHomeAwayMsg:
    'Choose Equally rotate teams home/away venue competition if competition features Home and Away venues.',
  equallyRotateCentralizedVenueMsg:
    'Choose Equally rotate teams - centralised venue competition if competition is run at centralised venues.',

  ////Competition Format Screen
  applyMatchFormatMsg:
    'Choose whether the match format is applied to all Divisions or whether it is different for particular Divisions.',
  applyFinalFormatMsg:
    'Choose to enable Finals. Apply Final format to all Divsions or by particular Division. ',
  matchDurationCompFormatMsg: 'Total Match time NOT including breaks.',
  mainBreakCompFormatMsg: 'Break Duration at half-time.',
  qtrBreakCompFormatMsg: 'Break Duration at end of 1st and 3rd quarters.',

  ////Registration Competition Fees
  regInviteesAffiliatesMsg:
    'Organisations that are affiliated below your organisation. They will invite Users (Players, Coaches, Umpires etc) to register to their organisation and they will then submit them to your competition.',
  regInviteesAnyOrgMsg:
    'Add Organisation(s) not linked below your organisation in your State.They will invite Users (Players, Coaches, Umpires etc) to register to their organisation and they will then submit them to your competition.',
  regInviteesDirectMsg:
    'Users (Players, Coaches, Umpire etc) will register direct to your organisation and you will place them into teams (if they are not directly registering teams to your organisation).',

  ////Registration Form List
  regFormDashBoardMsg:
    'After you have added your Competition Fees, locate the Competition in the Registration Form table and click on edit (three dots in Action) to add Registration details and open registrations.',
  regFormOpenMsg:
    'List the date you want Registrations to open and be made available to users.',
  regFormCloseMsg:
    'List the date you want Registrations to close. Please note registrations can still be taken after this date if required.',
  regLockMsg:
    'Registration Lock immediately closes registration for those divisions it is applied to.',
  regFormTraningMsg: 'Show users training details like Date, Time and Venue.',
  regFormSpecialNoteMsg:
    'Detail any special notes you would like to include on the Registration Form.',
  regFormPhotoMsg:
    'These are stored in "Our Organisation" Photos. You can display as many photos as you would like to Users to show them your uniform, courts, logo etc.',
  replyContactDetailMsg:
    'Let Users know who to contact if they have any questions. You can choose to list their Name, Role, Email and or Phone number.',
  howUserRegisterMsg: 'Define how Users can Register for your Competition.',
  additionQuesMsg:
    'Click on the Questions you would like to ask Users who are Registering to your Competition.',
  allDivisionsMsg: 'All Divisions are changed the same Fees.',
  perDivisionMsg: 'Each Dvision can be charged a different Fee. ',
  paymentSeasonalFeeMsg:
    'Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.',
  paymentCausalFeeMsg:
    'Choose the payment options you would like to offer users to pay their Registration Fees with.You can choose multiple.',
  charityRoundUpMsg:
    'Add the ability for users Registering to round up their registration to the nearest $1, $5 or $10 to support the pre-defined charity.',
  discountMsg:
    'Choose the discount you would like to apply to your Compettion Fee. Please note, this discount only applies to your orgaisations Competition Fee. You can choose which membership Product and Type this fee is applied to.',
  discountTypeMsg:
    'Currently the only choices are -  Discount Code or Family. You can offer both discounts for the one competitiion but Family will be applied first. ',

  ////Registration Memership Fee

  membershipProductNameMsg:
    'Add a name that your affiliated organisations can resonate with e.g. Annual Membership Fee',
  validityMsg: `Add how long you want the membership product to be available:\n\n
  * Calendar Year - 1st Jan to 31st Dec in that year\n\n
  * 12 months from date of Registration`,

  membershipCasualFeeMsg: 'Fee charged to participate in a single game.',
  membershipSeasonalFeeMsg: 'Fee charged to join a Netball competition.',
  firstComRegOnlyMsg:
    'Fee charged to the User for the first competition they join in the defined period (whether it be calendar year or 12 months from date of registration). It will not be charged if they join another competition in that defined period.',
  allCompRegMsg:
    'Fee charged to the User every time they join a competition in the defined period (whether it be calendar year or 12 months from date of registration).',
  membershipDiscountMsg:
    'Discounts applied here apply to Player Membership Fees only.',

  ////For Users Module
  orgTypeMsg:
    'Detail the type of organisation being added. State Organisations can add Associations/ Leagues and Clubs/ Schools, Associations can only add Clubs/ Schools.',
  addAfiliatePermisionLevelMsg: `Choose the permission level for each contact.\n\n
  Admin - can access all areas in the platform.\n\n
  Communications Admin - can access the advertising platform and the Home Screen for News and Notifications.\n\n
  Umpires Admin - can access the Umpires platform.\n\n
  Results Admin - can access the Live Scores Platform to upload match results and player information.\n\n
  Finance Admin - can access Payments and the Registration platform.`,

  ourOrgPermissionLevelMsg: `Choose the permission level for each contact.\n\n
  Admin - can access all areas in the platform.\n\n
  Communications Admin - can access the advertising platform and the Home Screen for News and Notifications.\n\n
  Umpires Admin - can access the Umpires platform.\n\n
  Results Admin - can access the Live Scores Platform to upload match results and player information.\n\n
  Finance Admin - can access Payments and the Registration platform.`,

  selectedTeams: 'Selected Teams Array',
  importCoach: 'Import Coaches',
  ladderLink: 'Ladder Link',
  public_Ladder_Url: `https://netball-registration-dev.worldsportaction.com/liveScorePublicLadder?`,
  inviteTypeRef: 'InviteType',
  inviteType: 'Type',
  DobMoreThan: 'DOB more than',
  DobLessThan: 'DOB less than',
  NoDobPreference: 'No DOB Preference',
  DobPreference: 'DOB Preference',
  both: 'Both',
  sendInvitesTo: 'Send invites to',
  registrationWizard: 'Registration Wizard',
  createPublish: 'Create and Publish',
  set: 'Set',
  setup: 'Set up',
  setupStripe: 'Stripe account',
  resultStatus: 'Result Status',
  whichTeamForfieted: 'Which team forfeited?',
  matchAbandoned: 'Match Abandoned?',

  addUmpire: 'Add Umpire',
  editUmpire: 'Edit Umpire',
  umpireSearch: 'Umpire Search',
  nonPlayerDivisionMessage:
    'Divisions are not required for your selected membership type.',
  drawsLink: 'Draws Link',
  public_draws_Url: `https://netball-registration-dev.worldsportaction.com/livescoreSeasonFixture?`,
  finalsMessage: 'Finals has not been enabled for this Competition',
  allowTeamRegistration: 'Allow Team Registrations',
  teamRegistration: "Team Registrations",
  individualRegistrations: "Individual Registrations",

  /////////shop
  listProducts: "List Products",

  importUmpire: 'Import Umpire',

  addAProduct: 'Add a Product',
  addProduct: 'Add Product',
  enterTitle: 'Enter Title',
  pricing: 'Pricing',
  price: 'Price',
  costPerItem: 'Cost per item',
  chargeTaxesOnProduct: 'Charge taxes on product',
  inventory: 'Inventory',
  enableInventoryTracking: 'Enable inventory tracking',
  StockKeepingUnit: 'Stock keeping unit',
  skuHeader: 'SKU(stock keeping unit)',
  barcodeHeading: 'Barcode(ISBN,UPC,GTIN,etc)',
  barcode: 'Barcode',
  quantity: 'Quantity',
  allowCustToPurchase:
    "Allow customers to purchase this product when it's out of stock",
  variants: 'Variants',
  enableVariants: 'Enable Variants',
  variantName: 'Variant Name',
  orders: 'Orders',
  orderSummary: 'Order Summary',
  orderStatus: 'Order Status',
  parentOrGuardianDetail: 'Parent/Guardian Details',
  numbersOfOrders: "Number of ORDERS",
  valueOfOrders: "Value of ORDERS",
  orderId: "Order Id",
  netProfit: "Net Profit",
  paid: "Paid",
  addOrder: "Add Order",
  paymentStatus: "Payment Status",

  fullFillmentStatus: "Fullfilment Status",
  attendence_Recording_Time: "Attendance Recording Time",
  lineupSelection: "Lineup Selection",
  _days: "Days",
  _hours: "Hours",
  _minutes: "Minutes",

  lineUpSelectionMsg: "We can’t enable lineup selection without position tracking",
  // umpireListExport: "https://users-api-dev.worldsportaction.com/users/byRole/export/org?",
  umpireListExport: "users/byRole/export/org?",
  disabilityCareNumber: "Disability care Number",
  typeOfDisability: "Type of Disability",
  pickUpAddress: "Pick up address",
  productTypes: "Product Types",
  topSellers: "Top Sellers",
  productType: "Product Type",
  divisionGradeAndTeams: "Division, Grade and Teams",
  numbersOfTeams: "Number of teams",

  shipping: "Shipping",
  pickup: "Pickup",
  productDimensionsWeight: "Product dimensions and weight",
  dimensions: "Dimensions",
  size: "Size",
  sku: "SKU",
  option: "Option",
  addvariantoption: "Add variant option",
  deleteProduct: "Delete Product",
  deleteProductDescription: "Please confirm you want to delete this product?",
  umpireDashboardExport: "/matchUmpire/dashboard/export?",
  updateAction: "Update Action",
  actionBoxConfirmMsg: "Are you sure you want to complete this activity?",
  backToUmpire: 'Back to all Umpires',
  assignMatch: 'Assign Match',
  generateRoster: 'Generate Roster',
  howUmpiresAllocated: 'How Umpires Allocated',
  umpirePrefences: "Umpire Preferences:",
  noOfMatches: 'Number of Matches they can ',
  timeBetweenUmpireMatch: 'Time between Umpiring Matches',
  umpireReservePref: 'Umpire Reserve',
  reserveAllocationTiming: 'Reserve Allocation timing',
  activeUmpireCoach: "Activate Umpire Coaches",
  umpirePoolsDivision: "Umpire Pools Allocation To Divisions/Grades",
  allocatePools: "Allocate Pools To",
  badgeAA: "Badge AA",
  badgeA: "Badge A",
  badgeB: "Badge B",
  badgeC: "Badge C",
  umpireCoach: "Umpire Coach",
  juniorUnbadge: "Junior Unbadge",
  umpirePools: "Umpire Pools",
  competitionVenueAllocation: "Competition Venue allocation",
  sqadSelection: 'Squad Selection',
  umpireExport: `/umpire/export?competitionId=`,
  invite: "Invite",
  send: "Send",
  noSend: "No Send",
  tax: "Tax",
  dragImageToUpload: "Drag image to upload",
  addType: "Add type",
  coachSearch: 'Coach Search',
  incident: "Incident",
  selectIncident: "Select Incident",
  _spectator: "Spectator",
  discipline: "Discipline",
  injuryAmbulance: "Injury - Ambulance",
  injuryFirstAdd: "Injury - First Aid",
  emailExp: "/^-?(0|[1-9][0-9]*)(\.[0-9]*)?$/",
  childDetails: "Child Details",
  registrationDivision: "Registration Divisions",
  addRegDivision: 'Add Registration Divisions',
  downLoadImportHeading: "Download the matches list first then populate umpires details to upload ",
  assignUmpireToMatch: "Assign Umpires To Matches",
  participateInCompReg: 'Participating-In Competition Registrations',
  ownedCompetitionsReg: 'Owned Competition Registrations',
  newCompetitionReg: 'New Competition Registration',
  rosterExport: '/roster/export/umpire?',
  Registrations: "Registrations",
  ladderAllDivisionRmvMsg: "Would you like to set this ladder format for 'All Divisions'?",
  ladderFormat: "Ladder Format",
  ladderRemoveMsg: "Are you sure you want to remove ladder format?",
  competitionEnabled: 'Competition not enabled for Integrated Umpires, Click here to enable.',
  bulkScoreUpload: 'Bulk Scores Upload',
  umpireRoster: 'Umpire Roster',
  registrationDivisions: "Registration Divisions",
  activeUmpireReserves: "Activate Umpire reserves",
  simultaneousMatchAllocations: "Simultaneous match allocations",
  poolName: "Pool Name",
  umpireReserve: "Umpire Reserve",
  points: "Points",
  reasonForChange: 'Reason for change',
  editIncident: 'Edit Incident',
  addCompetitionFormat: 'Add Competition Format',
  fileUploadPdf: "File Upload (File Type: PDF)",
  link: "Link",
  qrCodeHeader: 'Code from authenticator',
  paymentStatusReference: 'PaymentStatus',
  positionTrackReport: "Position Tracking Report",
  periodFilter: 'Period',
  byGame: 'By Game',
  importTeamPlayer: "Import Team and Players",
  quickCompetitionFormat: "Competition Format (3/3)",
  matchPrintTemplateType: 'Match Print Template Type',
  templateType: 'Template type',
  playerBorrowing: "Player Borrowing",
  gamesBorrowed: "Games Borrowed",
  minutesBorrowed: "Minutes Borrowed",
  premierCompLink: 'Premier Competition Link',
  productAddedMessage: "Product added successfully.",
  productDeletedMessage: "Product deleted successfully.",
  typeAddedMessage: "Type added successfully.",
  registrationChange: "Registration Change",
  cost: "Cost",
  history: "History",
  somethingWentWrong: "Something went wrong.",
  variantDeletedMessage: "Variant deleted successfully.",
  refreshDownloads: "Refresh Downloads",

  // Account
  account: "Account",
  profileMenu: "Profile",
  passwordMenu: "Password",
  profileHeader: "Your Profile",
  passwordHeader: "Change your password",
  enterPhoneNumber: "Enter phone number",
  currentPassword: "Current password",
  enterCurrentPassword: "Enter current password",
  newPassword: "New password",
  enterNewPassword: "Enter new password",
  confirmPassword: "Confirm password",
  enterConfirmPassword: "Enter confirm password",
  userIsRegisteredTo: "User is registered to",
  competitionAdimistrator: 'Competition Adimistrator',
  regChangeDetail: 'REGISTRATION CHANGE DETAILS',
  dateRegChange: 'Date Registration Change',
  dateCompStart: 'Date Competition Start',
  regChangeType: 'Registration Change Type',
  generateFixtures: "Generate Fixtures",
  doTheySayForGame: 'Do they say they have taken the court for training, grading or a competition game?',
  reasonToDeRegister: 'Reasons why they would like to de-register?',
  overCommited: `I am over commited with other activities and can't fit in time for netball`,
  injuredOrHealthReason: 'I have been injured or health reason (not netball related)',
  decideNotToParticipate: 'Decided not to participate in netball',
  moveToDiffGeographicalArea: 'Moving to different geographical area',
  otherReason: 'Other',
  approvals: 'Approvals',
  approve: 'APPROVE',
  decline: 'DECLINE',
  stateWideMsg: 'State-wide messages',
  allOrganisation: 'All Organisations',
  indivisualOrgnisation: 'Individual Organisations',
  firstLevelAffiliatesAssociationLeague: "1st Level Affiliates - Association/ League",
  secondLevelAffiliatesClubSchool: "2nd Level Affiliates - Club/School",
  teamSeasonalFee: 'Team Seasonal Fee',
  settingsAddedMessage: "Settings added successfully.",
  deleteVariantOption: "Delete variant option",
  deleteVariantOptionDescription: "Please confirm you want to delete this variant option?",
  deleteProductType: "Delete product type",
  deleteProductTypeDescription: "Please confirm you want to delete this product type?",
  emailChangedWarning: "You will need to log in with your new email address on your next login.",
  settingsUpdatedMessage: "Settings updated successfully.",
};

export default AppConstants;
